In [1161]:
import pandas as pd

In [1162]:
sales_data_orders=pd.read_excel(r"D:\Python Test\sales_data.xlsx", sheet_name="Orders")
sales_data_customers=pd.read_excel(r"D:\Python Test\sales_data.xlsx", sheet_name="Customers")
sales_data_products=pd.read_excel(r"D:\Python Test\sales_data.xlsx", sheet_name="Products")
sales_data_returns=pd.read_excel(r"D:\Python Test\sales_data.xlsx", sheet_name="Returns")

In [1163]:
sales_data_orders.head(2)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15

In [1164]:
sales_data_orders.groupby("channel").aggregate({"order_id":"count"})

         order_id
channel
Online        395
Partner       422
Store         391

In [1165]:
sales_data_orders['revenue'] = sales_data_orders['revenue'].astype(str).str.replace("₹", "", regex=False).astype(float)

In [1166]:
sales_data_orders.groupby("channel").aggregate({"revenue":"sum"})

             revenue
channel
Online   17804956.26
Partner  17247193.82
Store    17024621.10

In [1167]:
sales_data_orders.groupby("channel").aggregate({"revenue":"mean"})

              revenue
channel
Online   45075.838633
Partner  40870.127536
Store    43541.230435

In [1168]:
sales_data_orders.groupby("channel").aggregate({"quantity":"count"})

         quantity
channel
Online        395
Partner       422
Store         391

In [1169]:
sales_data_orders.groupby("payment_method").aggregate({"order_id":"count"})

                order_id
payment_method
COD                  238
Card                 241
NetBanking           253
UPI                  217
Wallet               239

In [1170]:
sales_data_orders.groupby("payment_method").aggregate({"order_id":"count"}).rename(columns={"order_id":"Orders Placed"})

                Orders Placed
payment_method
COD                       238
Card                      241
NetBanking                253
UPI                       217
Wallet                    239

In [1171]:
sales_data_orders.groupby("payment_method").aggregate({"revenue":"sum"}).rename(columns={"revenue":"Revenue Collected"})

                Revenue Collected
payment_method
COD                   10764083.04
Card                  10122294.82
NetBanking            10922704.99
UPI                    9363177.40
Wallet                10159386.84

In [1172]:
sales_data_orders.groupby("payment_method").aggregate({"revenue":"mean"}).rename(columns={"revenue":"Average Revenue"})

                Average Revenue
payment_method
COD                45227.239664
Card               42001.223320
NetBanking         43172.746996
UPI                43148.282949
Wallet             42507.894728

In [1173]:
sales_data_customers.head(2)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27
1,C0002,Customer 2,cust2@example.com,Wholesale,East,Patna,2023-05-04

In [1174]:
sales_data_customers.groupby("segment").aggregate({"customer_id":"count"})

           customer_id
segment
Corporate           40
Retail              34
Wholesale           45
retail               1

In [1175]:
sales_data_customers.groupby("segment").aggregate({"region":"count"})

           region
segment
Corporate      40
Retail         34
Wholesale      45
retail          1

In [1176]:
sales_data_customers.groupby("city").aggregate({"customer_id":"count"}).rename(columns={"customer_id":"Total Customers"})

             Total Customers
city
Ahmedabad                  6
Bengaluru                  5
Bhubaneswar                8
Chandigarh                12
Chennai                    6
Delhi                      8
Guwahati                   6
Hyderabad                  9
Jaipur                     9
Kochi                      6
Kolkata                    7
Lucknow                    6
MUMBAI                     1
Mumbai                     4
Patna                     10
Pune                      10
Surat                      7

In [1177]:
sales_data_products.head(2)

  product_id  product_name category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001  Grocery     2916.58     2252.96      True
1       P002  APP-Item-002  Apparel     3617.52     2100.87      True

In [1178]:
sales_data_products.groupby("category").aggregate({"product_id":"count"})

             product_id
category
Apparel              10
Beauty                4
Electronics           5
Grocery               9
Home                  6
Sports                6

In [1179]:
sales_data_products.groupby("category").aggregate({"unit_price":"mean"})

               unit_price
category
Apparel      14095.019000
Beauty        8509.382500
Electronics  15372.922000
Grocery      14052.264444
Home         12688.400000
Sports       14401.065000

In [1180]:
sales_data_returns.head(2)

  return_id order_id return_date         reason  refund_amount
0     R0001   O01050  2025-05-20  Late Delivery        1917.72
1     R0002   O00477  2025-02-11        Damaged       14780.26

In [1181]:
sales_data_returns.groupby("reason").aggregate({"return_id":"count"})

                  return_id
reason
Damaged                  20
Late Delivery            18
Not as described         20
Other                    12
Wrong Item               20

In [1182]:
sales_data_returns.groupby("reason").aggregate({"refund_amount":"sum"})

                  refund_amount
reason
Damaged               591433.16
Late Delivery         524675.43
Not as described      678083.68
Other                 293763.68
Wrong Item            654568.82

In [1183]:
sales_data_returns.groupby("reason").aggregate({"refund_amount":"mean"})

                  refund_amount
reason
Damaged            29571.658000
Late Delivery      29148.635000
Not as described   33904.184000
Other              24480.306667
Wrong Item         32728.441000

In [1184]:
sales_data_orders.head(5)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15
2,O00003,2025-11-13 00:00:00,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98
3,O00004,2025-10-29 00:00:00,C0049,P029,4,21540.38,0.0,Store,COD,86161.52
4,O00005,2025-02-20 00:00:00,C0073,P040,1,13262.69,10.0,Online,Card,11936.42

In [1185]:
sales_data_orders.groupby("channel").aggregate(
    {"order_id":"count",
    "revenue":['sum','mean'],
    #"revenue":"mean",
    "quantity":"count"})

        order_id      revenue               quantity
           count          sum          mean    count
channel
Online       395  17804956.26  45075.838633      395
Partner      422  17247193.82  40870.127536      422
Store        391  17024621.10  43541.230435      391

In [1186]:
sales_data_orders.groupby("channel").aggregate({"revenue":"sum"})

             revenue
channel
Online   17804956.26
Partner  17247193.82
Store    17024621.10

In [1187]:
sales_data_orders.groupby("payment_method").aggregate(
    {
    "order_id":"count",
    "revenue":['sum','mean']
    }
)

               order_id      revenue
                  count          sum          mean
payment_method
COD                 238  10764083.04  45227.239664
Card                241  10122294.82  42001.223320
NetBanking          253  10922704.99  43172.746996
UPI                 217   9363177.40  43148.282949
Wallet              239  10159386.84  42507.894728

In [1188]:
sales_data_products.head(2)

  product_id  product_name category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001  Grocery     2916.58     2252.96      True
1       P002  APP-Item-002  Apparel     3617.52     2100.87      True

In [1189]:
sales_data_products.groupby("category").aggregate(
    {
    "product_id":"count",
    "unit_price":"mean",
    "cost_price":"mean"
    }
)

             product_id    unit_price    cost_price
category
Apparel              10  14095.019000   9780.892000
Beauty                4   8509.382500   6796.690000
Electronics           5  15372.922000  11680.094000
Grocery               9  14052.264444  10177.105556
Home                  6  12688.400000   9660.716667
Sports                6  14401.065000   9116.828333

In [1190]:
sales_data_customers.head(2)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27
1,C0002,Customer 2,cust2@example.com,Wholesale,East,Patna,2023-05-04

In [1191]:
sales_data_customers.groupby("region").aggregate({
    "customer_id":"count",
    "city":"count"
})

        customer_id  city
region
East             31    31
North            35    35
South            27    27
West             26    26
north             1     1

In [1192]:
sales_data_returns.head(2)

  return_id order_id return_date         reason  refund_amount
0     R0001   O01050  2025-05-20  Late Delivery        1917.72
1     R0002   O00477  2025-02-11        Damaged       14780.26

In [1193]:
sales_data_returns.groupby("reason").aggregate({
    "return_id":['count'],
    "refund_amount":['sum','mean']
})

                 return_id refund_amount
                     count           sum          mean
reason
Damaged                 20     591433.16  29571.658000
Late Delivery           18     524675.43  29148.635000
Not as described        20     678083.68  33904.184000
Other                   12     293763.68  24480.306667
Wrong Item              20     654568.82  32728.441000

In [1194]:
sales_data_orders.head(2)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15

In [1195]:
sales_data_orders.groupby("channel").aggregate({
    "revenue":['min','max','mean','sum']
})

         revenue
             min        max          mean          sum
channel
Online   1705.05  147796.50  45075.838633  17804956.26
Partner  1525.57  143620.44  40870.127536  17247193.82
Store    1705.05  148437.96  43541.230435  17024621.10

In [1196]:
sales_data_orders.groupby("channel").aggregate({"revenue":"sum"}).sort_values(by="revenue", ascending=False)

             revenue
channel
Online   17804956.26
Partner  17247193.82
Store    17024621.10

In [1197]:
sales_data_orders.groupby("channel")["revenue"].sum().nlargest(1)

channel
Online    17804956.26
Name: revenue, dtype: float64

In [1198]:
sales_data_orders.groupby("channel").aggregate({"quantity":"mean"}).idxmax()

quantity    Online
dtype: str

In [1199]:
sales_data_orders.groupby("channel")["revenue"].mean().nlargest(1)

channel
Online    45075.838633
Name: revenue, dtype: float64

In [1200]:
sales_data_orders.groupby("payment_method")["revenue"].sum().nlargest(1)

payment_method
NetBanking    10922704.99
Name: revenue, dtype: float64

In [1201]:
sales_data_products.head(2)

  product_id  product_name category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001  Grocery     2916.58     2252.96      True
1       P002  APP-Item-002  Apparel     3617.52     2100.87      True

In [1202]:
sales_data_products.groupby("category")["unit_price"].mean().nlargest(1)

category
Electronics    15372.922
Name: unit_price, dtype: float64

In [1203]:
sales_data_customers.head(2)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27
1,C0002,Customer 2,cust2@example.com,Wholesale,East,Patna,2023-05-04

In [1204]:
sales_data_customers.groupby("region")["customer_id"].count().nlargest(1)

region
North    35
Name: customer_id, dtype: int64

In [1205]:
sales_data_customers.groupby("city")["customer_id"].nunique().reset_index(name="customer_count").query("customer_count>10")

         city  customer_count
3  Chandigarh              12

In [1206]:
sales_data_orders.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59

In [1207]:
sales_data_orders.groupby("channel")["order_id"].nunique().reset_index(name="count_orders").query("count_orders>200")

   channel  count_orders
0   Online           393
1  Partner           419
2    Store           388

In [1208]:
sales_data_orders.groupby("payment_method")['revenue'].sum().reset_index(name="Total_Revenue").query("Total_Revenue>10000000")

  payment_method  Total_Revenue
0            COD    10764083.04
1           Card    10122294.82
2     NetBanking    10922704.99
4         Wallet    10159386.84

In [1209]:
sales_data_products.head(2)

  product_id  product_name category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001  Grocery     2916.58     2252.96      True
1       P002  APP-Item-002  Apparel     3617.52     2100.87      True

In [1210]:
sales_data_products.groupby("category")["unit_price"].mean().reset_index(name="unit_price").query("unit_price>10000")

      category    unit_price
0      Apparel  14095.019000
2  Electronics  15372.922000
3      Grocery  14052.264444
4         Home  12688.400000
5       Sports  14401.065000

In [1211]:
sales_data_returns.head(2)

  return_id order_id return_date         reason  refund_amount
0     R0001   O01050  2025-05-20  Late Delivery        1917.72
1     R0002   O00477  2025-02-11        Damaged       14780.26

In [1212]:
sales_data_returns.groupby("reason")["refund_amount"].sum().reset_index(name="refund_amount").query("refund_amount>100000")

             reason  refund_amount
0           Damaged      591433.16
1     Late Delivery      524675.43
2  Not as described      678083.68
3             Other      293763.68
4        Wrong Item      654568.82

In [1213]:
sales_data_orders.head(2)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15

In [1214]:
sales_data_orders.groupby("product_id")["quantity"].sum().reset_index(name="Total_Quantity").nlargest(5,"Total_Quantity")

   product_id  Total_Quantity
24       P025             144
28       P029             144
30       P031             138
26       P027             132
39       P040             132

In [1215]:
sales_data_orders.groupby("product_id")["revenue"].sum().reset_index(name="Total_Revenue").nlargest(5,"Total_Revenue")

   product_id  Total_Revenue
28       P029     2935953.79
29       P030     2563463.42
31       P032     2273676.11
32       P033     2136775.68
19       P020     2045864.53

In [1216]:
sales_data_customers.head(1)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27

In [1217]:
sales_data_orders.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59

In [1218]:
sales_data_orders.columns[sales_data_orders.columns.duplicated()]

Index([], dtype='str')

In [1219]:
sales_data_customers.columns[sales_data_customers.columns.duplicated()]

Index([], dtype='str')

In [1220]:
top_customers = (
    sales_data_orders.groupby("customer_id")["order_id"]
    .count()
    .reset_index(name="Total_Orders")
    .nlargest(5, "Total_Orders")
)

top_customers = top_customers.merge(
    sales_data_customers.loc[:, ["customer_id", "customer_name"]]
    .loc[:, lambda df: ~df.columns.duplicated()],
    on="customer_id",
    how="left"
)

top_customers[["customer_id", "customer_name", "Total_Orders"]]

  customer_id customer_name  Total_Orders
0       C0077   Customer 77            19
1       C0061   Customer 61            16
2       C0068   Customer 68            16
3       C0072   Customer 72            16
4       C0074   Customer 74            16

In [1221]:
sales_data_orders.groupby("customer_id").size().reset_index(name="Total_Orders").nlargest(5, "Total_Orders")

   customer_id  Total_Orders
76       C0077            19
60       C0061            16
67       C0068            16
71       C0072            16
73       C0074            16

In [1222]:
sales_data_orders.groupby("customer_id")["revenue"].sum().reset_index(name="Total_Revenue").nlargest(5,"Total_Revenue")

   customer_id  Total_Revenue
63       C0064      905871.92
84       C0085      794674.06
51       C0052      790722.03
71       C0072      766393.26
48       C0049      739040.54

In [1223]:
sales_data_orders.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59

In [1224]:
sales_data_orders.groupby("product_id")["quantity"].sum().reset_index(name="Total_Quantity").query("Total_Quantity>100")

   product_id  Total_Quantity
1        P002             106
2        P003             108
4        P005             124
8        P009             126
9        P010             122
10       P011             104
13       P014             105
16       P017             123
18       P019             113
19       P020             109
20       P021             129
24       P025             144
25       P026             112
26       P027             132
28       P029             144
29       P030             126
30       P031             138
31       P032             114
34       P035             107
35       P036             105
36       P037             123
37       P038             119
39       P040             132

In [1225]:
sales_data_orders.groupby("customer_id")["order_id"].count().reset_index(name="Total_Orders").nlargest(10,"Total_Orders")

   customer_id  Total_Orders
76       C0077            19
60       C0061            16
67       C0068            16
71       C0072            16
73       C0074            16
83       C0084            16
48       C0049            15
52       C0053            15
63       C0064            15
88       C0089            15

In [1226]:
sales_data_orders.groupby("customer_id")["revenue"].sum().reset_index(name="Total_Revenue").query("Total_Revenue>500000")

    customer_id  Total_Revenue
3         C0004      579063.90
9         C0010      571518.25
10        C0011      586090.00
12        C0013      584925.98
16        C0017      682781.05
17        C0018      735339.80
19        C0020      516128.46
27        C0028      634440.84
30        C0031      504330.68
34        C0035      610691.29
35        C0036      545878.17
38        C0039      690114.71
41        C0042      576647.48
43        C0044      646869.25
45        C0046      500991.44
48        C0049      739040.54
51        C0052      790722.03
52        C0053      667668.36
53        C0054      627468.23
57        C0058      609779.72
58        C0059      724631.91
60        C0061      590860.97
61        C0062      539031.32
63        C0064      905871.92
65        C0066      529843.08
67        C0068      674831.18
71        C0072      766393.26
73        C0074      523827.40
76        C0077      641513.92
82        C0083      622460.20
84        C0085      794674.06
88        C0089      629800.85
92        C0093      551644.91
95        C0096      714861.20
96        C0097      532522.88
103       C0104      528949.73
106       C0107      529516.50
119       C0120      518616.86

In [1227]:
sales_data_orders.groupby("product_id")["customer_id"].nunique().reset_index(name="Total_Customers").query("Total_Customers>20")

   product_id  Total_Customers
1        P002               26
2        P003               26
3        P004               24
4        P005               32
5        P006               22
6        P007               29
7        P008               21
8        P009               29
9        P010               31
10       P011               27
11       P012               22
12       P013               23
13       P014               24
14       P015               25
15       P016               21
16       P017               34
18       P019               28
19       P020               26
20       P021               30
21       P022               23
22       P023               26
23       P024               26
24       P025               36
25       P026               28
26       P027               32
28       P029               35
29       P030               28
30       P031               29
31       P032               30
32       P033               28
33       P034               28
34       P035               23
35       P036               26
36       P037               34
37       P038               34
38       P039               24
39       P040               29

In [1228]:
sales_data_orders.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59

In [1229]:
sales_data_orders.groupby("channel")["discount_pct"].mean().reset_index(name="Maximum_Discount").query("Maximum_Discount>5.0")

   channel  Maximum_Discount
0   Online          7.976501
1  Partner          7.224939
2    Store          6.715426

In [1230]:
sales_data_orders["order_date"] = pd.to_datetime(
    sales_data_orders["order_date"], errors="coerce"
)

In [1231]:
sales_data_orders["order_date"].min()

Timestamp('2025-01-01 00:00:00')

In [1232]:
sales_data_orders["order_date"].max()

Timestamp('2025-12-20 00:00:00')

In [1233]:
sales_data_customers.head(1)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27

In [1234]:
sales_data_customers["signup_date"]=pd.to_datetime(sales_data_customers["signup_date"], errors="coerce")

In [1235]:
sales_data_customers["signup_date"].min()

Timestamp('2023-01-10 00:00:00')

In [1236]:
sales_data_customers["signup_date"].max()

Timestamp('2025-06-19 00:00:00')

In [1237]:
sales_data_returns.head(1)

  return_id order_id return_date         reason  refund_amount
0     R0001   O01050  2025-05-20  Late Delivery        1917.72

In [1238]:
sales_data_returns["return_date"].min()

Timestamp('2025-01-13 00:00:00')

In [1239]:
sales_data_returns["return_date"].min()

Timestamp('2025-01-13 00:00:00')

In [1240]:
sales_data_orders.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59

In [1241]:
sales_data_orders["order_date"].dt.year

0       2025
1       2025
2       2025
3       2025
4       2025
        ...
1203    2025
1204    2025
1205    2025
1206    2025
1207    2025
Name: order_date, Length: 1208, dtype: int32

In [1242]:
sales_data_orders["order_date"].dt.month

0        2
1        2
2       11
3       10
4        2
        ..
1203     7
1204    10
1205     3
1206     2
1207     4
Name: order_date, Length: 1208, dtype: int32

In [1243]:
sales_data_orders["order_date"].dt.month_name()

0       February
1       February
2       November
3        October
4       February
          ...
1203        July
1204     October
1205       March
1206    February
1207       April
Name: order_date, Length: 1208, dtype: str

In [1244]:
sales_data_orders["order_date"].dt.day_of_week

0       4
1       3
2       3
3       2
4       3
       ..
1203    1
1204    5
1205    5
1206    3
1207    5
Name: order_date, Length: 1208, dtype: int32

In [1245]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.month_name())['order_id'].count()

order_date
April         86
August       105
December      84
February     110
January      104
July         114
June         108
March        104
May           93
November     105
October      106
September     89
Name: order_id, dtype: int64

In [1246]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.month_name())['revenue'].sum()

order_date
April        3736987.64
August       4781216.19
December     3046748.79
February     4920270.69
January      5102711.46
July         4634551.76
June         4403524.13
March        4678443.18
May          4077698.57
November     4390124.64
October      4894184.33
September    3410309.80
Name: revenue, dtype: float64

In [1247]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.month_name())['order_id'].count()

order_date
April         86
August       105
December      84
February     110
January      104
July         114
June         108
March        104
May           93
November     105
October      106
September     89
Name: order_id, dtype: int64

In [1248]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.day_name())

In [1249]:
sales_data_orders.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59

In [1250]:
sales_data_customers.head(1)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27

In [1251]:
sales_data_orders["customer_id"] = (
    sales_data_orders["customer_id"].astype("string").str.strip()
)

sales_data_customers["customer_id"] = (
    sales_data_customers["customer_id"].astype("string").str.strip()
)

result = sales_data_orders.merge(
    sales_data_customers[["customer_id", "customer_name"]],
    on="customer_id",
    how="left"
)

result.head(2)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,customer_name
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Customer 106
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Customer 20

In [1252]:
result.groupby(["customer_id","customer_name"])["order_id"].count().reset_index(name="Total_Orders").query("Total_Orders>5")

    customer_id   customer_name  Total_Orders
0         C0001      Customer 1            11
1         C0002      Customer 2             9
2         C0003      Customer 3             8
3         C0004    Customer 4              10
4         C0005      Customer 5             7
..          ...             ...           ...
114       C0115    Customer 115            15
116       C0117    Customer 117             8
117       C0118    Customer 118            12
118       C0119    Customer 119             7
119       C0120    Customer 120             7

[113 rows x 3 columns]

In [1253]:
sales_data_orders['order_date']=pd.to_datetime(sales_data_orders['order_date'])
sales_data_orders['day_of_week']=sales_data_orders['order_date'].dt.day_name()

In [1254]:
print(sales_data_orders['day_of_week'])

0          Friday
1        Thursday
2        Thursday
3       Wednesday
4        Thursday
          ...
1203      Tuesday
1204     Saturday
1205     Saturday
1206     Thursday
1207     Saturday
Name: day_of_week, Length: 1208, dtype: str

In [1255]:
sales_data_orders.head(3)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday

In [1256]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.month_name())['revenue'].sum()

order_date
April        3736987.64
August       4781216.19
December     3046748.79
February     4920270.69
January      5102711.46
July         4634551.76
June         4403524.13
March        4678443.18
May          4077698.57
November     4390124.64
October      4894184.33
September    3410309.80
Name: revenue, dtype: float64

In [1257]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.month_name())['quantity'].count()

order_date
April         86
August       105
December      84
February     110
January      104
July         114
June         108
March        104
May           93
November     105
October      106
September     89
Name: quantity, dtype: int64

In [1258]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.month_name())['revenue'].mean()

order_date
April        43453.344651
August       45535.392286
December     36270.818929
February     44729.733545
January      49064.533269
July         40653.962807
June         40773.371574
March        44985.030577
May          43846.221183
November     41810.710857
October      46171.550283
September    38318.087640
Name: revenue, dtype: float64

In [1259]:
sales_data_orders.groupby(
    sales_data_orders['order_date'].dt.month_name()
).agg(
    average_revenue=('revenue', 'mean'),
    order_ids=('order_id', list)
)

            average_revenue                                          order_ids
order_date
April          43453.344651  [O00026, O00033, O00055, O00074, O00076, O0009...
August         45535.392286  [O00028, O00037, O00047, O00048, O00058, O0006...
December       36270.818929  [O00007, O00031, O00041, O00045, O00053, O0006...
February       44729.733545  [O00001, O00002, O00005, O00020, O00064, O0007...
January        49064.533269  [O00023, O00043, O00052, O00067, O00100, O0012...
July           40653.962807  [O00034, O00035, O00044, O00046, O00051, O0005...
June           40773.371574  [O00014, O00018, O00032, O00039, O00050, O0006...
March          44985.030577  [O00006, O00011, O00012, O00016, O00025, O0002...
May            43846.221183  [O00008, O00027, O00038, O00054, O00073, O0007...
November       41810.710857  [O00003, O00009, O00010, O00042, O00056, O0008...
October        46171.550283  [O00004, O00013, O00015, O00017, O00036, O0004...
September      38318.087640  [O00019, O00021, O00022, O00024, O00030, O0004...

In [1260]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.month_name())['revenue'].sum().idxmax()

'January'

In [1261]:
monthly_revenue=sales_data_orders.groupby(sales_data_orders['order_date'].dt.month_name())['revenue'].sum()
print("Month: ", monthly_revenue.idxmax())
print("Revenue: ", monthly_revenue.max())

Month:  January
Revenue:  5102711.46

In [1262]:
sales_data_orders[
    (sales_data_orders['order_date'].dt.month == 1)&
    (sales_data_orders['order_date'].dt.year == 2025)
]['order_id'].count()

np.int64(104)

In [1263]:
sales_data_orders[
    (sales_data_orders['order_date'].dt.month == 1)&
    (sales_data_orders['order_date'].dt.year == 2025)
]['order_id'].nunique()

104

In [1264]:
sales_data_orders[
    (sales_data_orders['order_date'].dt.month == 1)&
    (sales_data_orders['order_date'].dt.year == 2025)
]['order_id']

22      O00023
42      O00043
51      O00052
66      O00067
99      O00100
         ...
1074    O01075
1106    O01107
1154    O01155
1165    O01166
1171    O01172
Name: order_id, Length: 104, dtype: str

In [1265]:
sales_data_orders[
    (sales_data_orders['order_date'].dt.month == 1)&
    (sales_data_orders['order_date'].dt.year == 2025)
]['order_id'].tolist()

['O00023',
 'O00043',
 'O00052',
 'O00067',
 'O00100',
 'O00124',
 'O00125',
 'O00132',
 'O00138',
 'O00143',
 'O00151',
 'O00155',
 'O00170',
 'O00201',
 'O00213',
 'O00214',
 'O00220',
 'O00239',
 'O00242',
 'O00252',
 'O00257',
 'O00281',
 'O00301',
 'O00311',
 'O00331',
 'O00354',
 'O00357',
 'O00361',
 'O00382',
 'O00387',
 'O00400',
 'O00418',
 'O00428',
 'O00430',
 'O00432',
 'O00434',
 'O00443',
 'O00445',
 'O00458',
 'O00477',
 'O00478',
 'O00491',
 'O00494',
 'O00511',
 'O00523',
 'O00528',
 'O00547',
 'O00565',
 'O00570',
 'O00571',
 'O00578',
 'O00582',
 'O00584',
 'O00597',
 'O00599',
 'O00602',
 'O00603',
 'O00607',
 'O00634',
 'O00636',
 'O00645',
 'O00646',
 'O00674',
 'O00682',
 'O00700',
 'O00702',
 'O00709',
 'O00722',
 'O00728',
 'O00767',
 'O00780',
 'O00791',
 'O00800',
 'O00815',
 'O00820',
 'O00831',
 'O00854',
 'O00866',
 'O00876',
 'O00883',
 'O00887',
 'O00891',
 'O00900',
 'O00903',
 'O00905',
 'O00907',
 'O00921',
 'O00929',
 'O00962',
 'O01004',
 'O01008',
 'O01011',
 'O01024',
 'O01033',
 'O01041',
 'O01055',
 'O01060',
 'O01063',
 'O01072',
 'O01075',
 'O01107',
 'O01155',
 'O01166',
 'O01172']

In [1266]:
sales_data_orders[sales_data_orders['order_date'].between('2025-01-01','2025-02-28')]

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday
19,O00020,2025-02-15,C0105,P036,1,8205.28,5.0,Store,COD,7795.02,Saturday
22,O00023,2025-01-27,C0097,P032,6,21914.95,5.0,Online,COD,124915.22,Monday
...,...,...,...,...,...,...,...,...,...,...,...
1189,O01190,2025-02-17,C0103,P015,5,9349.00,15.0,Partner,Wallet,39733.25,Monday
1190,O01191,2025-02-04,C0013,P038,3,18337.90,0.0,Partner,Wallet,55013.70,Tuesday
1191,O01192,2025-02-09,C0061,P028,2,9633.24,0.0,Partner,COD,19266.48,Sunday
1198,O01199,2025-02-02,C0109,P028,4,9633.24,0.0,Partner,Card,38532.96,Sunday
1206,O00818,2025-02-06,C0047,P015,5,9349.00,15.0,Online,Card,39733.25,Thursday

In [1267]:
sales_data_orders[sales_data_orders['order_date'].dt.day_of_week>=5]

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
5,O00006,2025-03-30,C9999,P006,2,14793.25,0.0,Partner,UPI,29586.50,Sunday
7,O00008,2025-05-25,C0038,P003,2,10634.76,0.0,Partner,NetBanking,21269.52,Sunday
12,O00013,2025-10-04,C0090,P026,3,18931.19,10.0,Store,NetBanking,51114.21,Saturday
13,O00014,2025-06-15,C0011,P039,1,16544.81,5.0,Partner,COD,15717.57,Sunday
19,O00020,2025-02-15,C0105,P036,1,8205.28,5.0,Store,COD,7795.02,Saturday
...,...,...,...,...,...,...,...,...,...,...,...
1197,O01198,2025-05-04,C0026,P024,4,14676.96,0.0,Online,COD,58707.84,Sunday
1198,O01199,2025-02-02,C0109,P028,4,9633.24,0.0,Partner,Card,38532.96,Sunday
1204,O01084,2025-10-25,C0084,P031,6,7443.48,20.0,Partner,Card,35728.70,Saturday
1205,O00284,2025-03-15,C0077,P021,2,1794.79,0.0,Partner,Wallet,3589.58,Saturday
1207,O00315,2025-04-26,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95,Saturday

In [1268]:
sales_data_orders[sales_data_orders['order_date'].dt.day_of_week<5]

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday
...,...,...,...,...,...,...,...,...,...,...,...
1200,O00637,2025-12-05,C0077,P004,6,12708.08,10.0,Store,NetBanking,68623.63,Friday
1201,O00684,2025-09-24,C0084,P021,1,1794.79,15.0,Partner,COD,1525.57,Wednesday
1202,O01034,2025-10-02,C0028,P034,4,12765.42,15.0,Online,Wallet,43402.43,Thursday
1203,O00191,2025-07-08,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32,Tuesday
1206,O00818,2025-02-06,C0047,P015,5,9349.00,15.0,Online,Card,39733.25,Thursday

In [1269]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.day_name())['order_id'].count()

order_date
Friday       177
Monday       164
Saturday     170
Sunday       150
Thursday     202
Tuesday      156
Wednesday    189
Name: order_id, dtype: int64

In [1270]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.day_name())['revenue'].sum()

order_date
Friday       7299928.95
Monday       7453084.60
Saturday     6841377.65
Sunday       6284535.15
Thursday     9108814.03
Tuesday      6772816.76
Wednesday    8316214.04
Name: revenue, dtype: float64

In [1271]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.day_name())['revenue'].mean()

order_date
Friday       41242.536441
Monday       45445.637805
Saturday     40243.397941
Sunday       41896.901000
Thursday     45093.138762
Tuesday      43415.492051
Wednesday    44001.132487
Name: revenue, dtype: float64

In [1272]:
sales_data_orders.head()

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday

In [1273]:
sales_data_customers.head(2)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27
1,C0002,Customer 2,cust2@example.com,Wholesale,East,Patna,2023-05-04

In [1274]:
sales_data_orders.merge(sales_data_customers[['customer_id','customer_name','region']],
                        on='customer_id',
                        how='left')[['order_id','customer_name','region']]

     order_id   customer_name region
0      O00001    Customer 106   East
1      O00002     Customer 20  North
2      O00003     Customer 72   West
3      O00004     Customer 49  North
4      O00005     Customer 73   East
...       ...             ...    ...
1203   O00191    Customer 4    South
1204   O01084     Customer 84  North
1205   O00284     Customer 77   West
1206   O00818     Customer 47   West
1207   O00315     Customer 52   East

[1208 rows x 3 columns]

In [1275]:
sales_data_orders.merge(sales_data_customers[['customer_id','customer_name','region','segment']],
                        on='customer_id',
                        how='left')[['order_id','customer_name','region','segment']]

     order_id   customer_name region    segment
0      O00001    Customer 106   East  Corporate
1      O00002     Customer 20  North  Corporate
2      O00003     Customer 72   West     Retail
3      O00004     Customer 49  North  Corporate
4      O00005     Customer 73   East  Wholesale
...       ...             ...    ...        ...
1203   O00191    Customer 4    South  Corporate
1204   O01084     Customer 84  North  Wholesale
1205   O00284     Customer 77   West  Wholesale
1206   O00818     Customer 47   West     Retail
1207   O00315     Customer 52   East  Corporate

[1208 rows x 4 columns]

In [1276]:
sales_data_orders.merge(sales_data_customers[['customer_id','customer_name']],
                        on='customer_id',
                        how='left')[['order_id','customer_name']]

     order_id   customer_name
0      O00001    Customer 106
1      O00002     Customer 20
2      O00003     Customer 72
3      O00004     Customer 49
4      O00005     Customer 73
...       ...             ...
1203   O00191    Customer 4
1204   O01084     Customer 84
1205   O00284     Customer 77
1206   O00818     Customer 47
1207   O00315     Customer 52

[1208 rows x 2 columns]

In [1277]:
sales_data_orders.merge(sales_data_customers[['customer_id','customer_name','region']],
                        on='customer_id',
                        how='left')[['order_id','customer_name','region']]

     order_id   customer_name region
0      O00001    Customer 106   East
1      O00002     Customer 20  North
2      O00003     Customer 72   West
3      O00004     Customer 49  North
4      O00005     Customer 73   East
...       ...             ...    ...
1203   O00191    Customer 4    South
1204   O01084     Customer 84  North
1205   O00284     Customer 77   West
1206   O00818     Customer 47   West
1207   O00315     Customer 52   East

[1208 rows x 3 columns]

In [1278]:
sales_data_orders.merge(sales_data_customers[['customer_id','segment']],
                        on='customer_id',
                        how='left').groupby('segment')['revenue'].sum()

segment
Corporate    17963776.86
Retail       16137801.92
Wholesale    17654523.60
retail         291082.30
Name: revenue, dtype: float64

In [1279]:
sales_data_orders.merge(sales_data_customers[['customer_id','region']],
                        on='customer_id',
                        how='left').groupby('region')['revenue'].sum()

region
East      11491037.87
North     16901076.83
South     11007923.53
West      12191619.32
north       455527.13
Name: revenue, dtype: float64

In [1280]:
sales_data_orders.merge(sales_data_customers[['customer_id','city']],
                        on='customer_id',
                        how='left').groupby('city')['revenue'].sum().nlargest(10)

city
Chandigarh    5516915.17
Jaipur        5041871.02
Pune          4341588.66
Delhi         3864142.10
Patna         3850425.45
Hyderabad     3393976.70
Surat         3199553.55
Kochi         3059933.25
Ahmedabad     3059089.82
Kolkata       2846852.23
Name: revenue, dtype: float64

In [1281]:
sales_data_orders.merge(sales_data_customers[['customer_id','region']],
                        on='customer_id',
                        how='left').groupby('region')['order_id'].count()

region
East      269
North     393
South     246
West      289
north      10
Name: order_id, dtype: int64

In [1282]:
sales_data_customers.head(2)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27
1,C0002,Customer 2,cust2@example.com,Wholesale,East,Patna,2023-05-04

In [1283]:
sales_data_orders.head(2)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday

In [1284]:
sales_data_orders.merge(sales_data_customers[['customer_id','segment']],
                        on='customer_id',
                        how='left').groupby('segment')['revenue'].mean()

segment
Corporate    43707.486277
Retail       46240.120115
Wholesale    40123.917273
retail       41583.185714
Name: revenue, dtype: float64

In [1285]:
sales_data_orders.groupby('customer_id', as_index=False)['revenue'].sum().nlargest(10,'revenue')

   customer_id    revenue
63       C0064  905871.92
84       C0085  794674.06
51       C0052  790722.03
71       C0072  766393.26
48       C0049  739040.54
17       C0018  735339.80
58       C0059  724631.91
95       C0096  714861.20
38       C0039  690114.71
16       C0017  682781.05

In [1286]:
sales_data_orders.groupby('customer_id')['revenue'].sum()

customer_id
C0001    386349.59
C0002    355165.40
C0003    369234.07
C0004    579063.90
C0005    324812.66
           ...
C0117    372179.08
C0118    409502.17
C0119    234261.06
C0120    518616.86
C9999     29586.50
Name: revenue, Length: 121, dtype: float64

In [1287]:
sales_data_orders.merge(
    sales_data_customers[['customer_id', 'region']],
    on='customer_id',
    how='left'
).groupby('region').size()

region
East      269
North     393
South     246
West      289
north      10
dtype: int64

In [1288]:
sales_data_customers[~sales_data_customers['customer_id'].isin(sales_data_orders['customer_id'])]

Empty DataFrame
Columns: [customer_id, customer_name, email, segment, region, city, signup_date]
Index: []

In [1289]:
sales_data_customers[sales_data_customers['customer_id'].isin(sales_data_orders['customer_id'])]

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27
1,C0002,Customer 2,cust2@example.com,Wholesale,East,Patna,2023-05-04
2,C0003,Customer 3,NaN,Retail,South,Chennai,2024-08-25
3,C0004,Customer 4,NaN,Corporate,South,Chennai,2024-10-08
4,C0005,Customer 5,NaN,Retail,North,Chandigarh,2025-05-30
...,...,...,...,...,...,...,...
115,C0116,Customer 116,cust116@example.com,Corporate,East,Bhubaneswar,2024-06-30
116,C0117,Customer 117,NaN,Retail,South,Hyderabad,2024-07-20
117,C0118,Customer 118,cust118@example.com,Wholesale,East,Bhubaneswar,2023-04-16
118,C0119,Customer 119,cust119@example.com,Wholesale,North,Jaipur,2023-12-15
119,C0120,Customer 120,cust120@example.com,Wholesale,South,Bengaluru,2023-04-27

In [1290]:
sales_data_orders.merge(
    sales_data_customers[['customer_id', 'segment']],
    on='customer_id',
    how='left'
).groupby('segment').size()

segment
Corporate    411
Retail       349
Wholesale    440
retail         7
dtype: int64

In [1291]:
sales_data_orders.groupby('customer_id',as_index=False)['order_id'].count().rename(columns={'order_id':'Total_Orders'})

    customer_id  Total_Orders
0         C0001            11
1         C0002             9
2         C0003             8
3         C0004            10
4         C0005             7
..          ...           ...
116       C0117             8
117       C0118            12
118       C0119             7
119       C0120             7
120       C9999             1

[121 rows x 2 columns]

In [1292]:
sales_data_orders.merge(sales_data_customers[['customer_id','customer_name']],
                        on='customer_id',
                        how='left').groupby(['customer_id','customer_name'])['order_id'].count()

customer_id  customer_name
C0001        Customer 1        11
C0002        Customer 2         9
C0003        Customer 3         8
C0004          Customer 4      10
C0005        Customer 5         7
                               ..
C0116        Customer 116       4
C0117        Customer 117       8
C0118        Customer 118      12
C0119        Customer 119       7
C0120        Customer 120       7
Name: order_id, Length: 120, dtype: int64

In [1293]:
sales_data_products.head(2)

  product_id  product_name category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001  Grocery     2916.58     2252.96      True
1       P002  APP-Item-002  Apparel     3617.52     2100.87      True

In [1294]:
sales_data_orders.head()

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday

In [1295]:
sales_data_orders.merge(sales_data_products[['product_id','category']],
                        on='product_id',
                        how='left').groupby('category')['quantity'].count()

category
Apparel        272
Beauty         106
Electronics    166
Grocery        272
Home           198
Sports         193
Name: quantity, dtype: int64

In [1296]:
sales_data_orders.merge(sales_data_products[['product_id','category']],
                        on='product_id',
                        how='left').groupby('category')['revenue'].sum()

category
Apparel        12393058.36
Beauty          2675835.52
Electronics     8340728.95
Grocery        12621222.80
Home            6576104.04
Sports          9350137.81
Name: revenue, dtype: float64

In [1297]:
sales_data_orders.merge(sales_data_products[['product_id','product_name','cost_price']],
                        on='product_id',
                        how='left')[['order_id','product_name','cost_price']]

     order_id  product_name  cost_price
0      O00001  GRO-Item-005    11629.50
1      O00002  ELE-Item-010    12997.40
2      O00003  GRO-Item-027     3111.26
3      O00004  SPO-Item-029    11921.40
4      O00005  HOM-Item-040     9708.00
...       ...           ...         ...
1203   O00191  GRO-Item-024    12025.52
1204   O01084  ELE-Item-031     4447.09
1205   O00284  HOM-Item-021     1478.80
1206   O00818  APP-Item-015     5729.55
1207   O00315  GRO-Item-030    17162.00

[1208 rows x 3 columns]

In [1298]:
sales_data_orders.merge(sales_data_products[['product_id','category','product_name']],
                        on='product_id',
                        how='left')[['order_id','product_name','category']]

     order_id  product_name     category
0      O00001  GRO-Item-005      Grocery
1      O00002  ELE-Item-010  Electronics
2      O00003  GRO-Item-027      Grocery
3      O00004  SPO-Item-029       Sports
4      O00005  HOM-Item-040         Home
...       ...           ...          ...
1203   O00191  GRO-Item-024      Grocery
1204   O01084  ELE-Item-031  Electronics
1205   O00284  HOM-Item-021         Home
1206   O00818  APP-Item-015      Apparel
1207   O00315  GRO-Item-030      Grocery

[1208 rows x 3 columns]

In [1299]:
sales_data_orders.merge(sales_data_products[['product_id','product_name']],
                          on='product_id',
                          how='left')[['order_id','product_name']]

     order_id  product_name
0      O00001  GRO-Item-005
1      O00002  ELE-Item-010
2      O00003  GRO-Item-027
3      O00004  SPO-Item-029
4      O00005  HOM-Item-040
...       ...           ...
1203   O00191  GRO-Item-024
1204   O01084  ELE-Item-031
1205   O00284  HOM-Item-021
1206   O00818  APP-Item-015
1207   O00315  GRO-Item-030

[1208 rows x 2 columns]

In [1300]:
sales_data_orders.merge(sales_data_products[['product_id','product_name']],
                          on='product_id',
                          how='left')[['order_id','product_id','product_name']]

     order_id product_id  product_name
0      O00001       P005  GRO-Item-005
1      O00002       P010  ELE-Item-010
2      O00003       P027  GRO-Item-027
3      O00004       P029  SPO-Item-029
4      O00005       P040  HOM-Item-040
...       ...        ...           ...
1203   O00191       P024  GRO-Item-024
1204   O01084       P031  ELE-Item-031
1205   O00284       P021  HOM-Item-021
1206   O00818       P015  APP-Item-015
1207   O00315       P030  GRO-Item-030

[1208 rows x 3 columns]

In [1301]:
#sales_data_orders['cogs']=(sales_data_orders['quantity']*sales_data_orders['cost_price'])
#sales_data_orders['cogs'] = (
#    sales_data_orders['quantity'] * sales_data_orders['cost_price']
#)
sales_data_orders.head(2)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday

In [1302]:
sales_data_cog=sales_data_orders.merge(sales_data_products[['product_id','cost_price']],
                        on='product_id',
                        how='left')

In [1303]:
sales_data_cog

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week,cost_price
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday,11629.50
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday,12997.40
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday,3111.26
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday,11921.40
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday,9708.00
...,...,...,...,...,...,...,...,...,...,...,...,...
1203,O00191,2025-07-08,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32,Tuesday,12025.52
1204,O01084,2025-10-25,C0084,P031,6,7443.48,20.0,Partner,Card,35728.70,Saturday,4447.09
1205,O00284,2025-03-15,C0077,P021,2,1794.79,0.0,Partner,Wallet,3589.58,Saturday,1478.80
1206,O00818,2025-02-06,C0047,P015,5,9349.00,15.0,Online,Card,39733.25,Thursday,5729.55
1207,O00315,2025-04-26,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95,Saturday,17162.00

In [1304]:
sales_data_cog['cogs']=(sales_data_cog['quantity'] * sales_data_cog['cost_price'])
sales_data_cog.groupby('product_id')['cogs'].sum()

product_id
P001     157707.20
P002     222692.22
P003     641971.44
P004     680698.56
P005    1442058.00
P006     961738.64
P007    1072587.94
P008    1277748.60
P009     258749.82
P010    1585682.80
P011    1152134.88
P012     227888.64
P013    1549755.48
P014     548901.15
P015     515659.50
P016    1534585.36
P017    1346036.97
P018    1174837.12
P019     723949.19
P020    1774830.65
P021     190765.20
P022     945285.34
P023     411684.28
P024    1130398.88
P025     684859.68
P026    1713899.04
P027     410686.32
P028     547861.68
P029    1716681.60
P030    2162412.00
P031     613698.42
P032    1571475.18
P033    1814735.58
P034     770491.26
P035    1136383.87
P036     478889.25
P037     466912.92
P038    1734435.71
P039    1324729.92
P040    1281456.00
P999          0.00
Name: cogs, dtype: float64

In [1305]:
sales_data_cog.head(2)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week,cost_price,cogs
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday,11629.5,46518.0
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday,12997.4,64987.0

In [1306]:
sales_data_cog['profit']=sales_data_cog['unit_price']-sales_data_cog['cost_price']

In [1307]:
sales_data_cog

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week,cost_price,cogs,profit
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday,11629.50,46518.00,4670.13
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday,12997.40,64987.00,5286.43
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday,3111.26,15556.30,1014.29
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday,11921.40,47685.60,9618.98
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday,9708.00,9708.00,3554.69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1203,O00191,2025-07-08,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32,Tuesday,12025.52,60127.60,2651.44
1204,O01084,2025-10-25,C0084,P031,6,7443.48,20.0,Partner,Card,35728.70,Saturday,4447.09,26682.54,2996.39
1205,O00284,2025-03-15,C0077,P021,2,1794.79,0.0,Partner,Wallet,3589.58,Saturday,1478.80,2957.60,315.99
1206,O00818,2025-02-06,C0047,P015,5,9349.00,15.0,Online,Card,39733.25,Thursday,5729.55,28647.75,3619.45
1207,O00315,2025-04-26,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95,Saturday,17162.00,85810.00,4974.99

In [1308]:
sales_data_cog.groupby('order_id')['profit'].sum()

order_id
O00001    4670.13
O00002    5286.43
O00003    1014.29
O00004    9618.98
O00005    3554.69
           ...
O01196    1830.01
O01197    3554.69
O01198    2651.44
O01199    1456.20
O01200    1014.29
Name: profit, Length: 1200, dtype: float64

In [1309]:
sales_data_products.head(2)

  product_id  product_name category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001  Grocery     2916.58     2252.96      True
1       P002  APP-Item-002  Apparel     3617.52     2100.87      True

In [1310]:
sales_data_cog.merge(sales_data_products[['product_id','category']],
                     on='product_id',
                     how='left').groupby('category')['profit'].sum()

category
Apparel        1163150.93
Beauty          173103.11
Electronics     621656.71
Grocery        1085076.19
Home            510202.04
Sports         1103693.83
Name: profit, dtype: float64

In [1311]:
sales_data_cog['profit_margin']=(sales_data_cog['profit']/sales_data_cog['unit_price'])*100

In [1312]:
sales_data_cog

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week,cost_price,cogs,profit,profit_margin
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday,11629.50,46518.00,4670.13,28.651755
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday,12997.40,64987.00,5286.43,28.913143
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday,3111.26,15556.30,1014.29,24.585570
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday,11921.40,47685.60,9618.98,44.655572
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday,9708.00,9708.00,3554.69,26.802180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1203,O00191,2025-07-08,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32,Tuesday,12025.52,60127.60,2651.44,18.065321
1204,O01084,2025-10-25,C0084,P031,6,7443.48,20.0,Partner,Card,35728.70,Saturday,4447.09,26682.54,2996.39,40.255230
1205,O00284,2025-03-15,C0077,P021,2,1794.79,0.0,Partner,Wallet,3589.58,Saturday,1478.80,2957.60,315.99,17.605959
1206,O00818,2025-02-06,C0047,P015,5,9349.00,15.0,Online,Card,39733.25,Thursday,5729.55,28647.75,3619.45,38.714836
1207,O00315,2025-04-26,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95,Saturday,17162.00,85810.00,4974.99,22.473652

In [1313]:
sales_data_cog.merge(sales_data_products[['product_id','category']],
                     on='product_id',
                     how='left').groupby('category')['profit_margin'].mean()

category
Apparel        32.424746
Beauty         20.579674
Electronics    26.002398
Grocery        27.006089
Home           23.597803
Sports         39.334476
Name: profit_margin, dtype: float64

In [1314]:
sales_data_products.head(1)

  product_id  product_name category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001  Grocery     2916.58     2252.96      True

In [1315]:
sales_data_orders.merge(sales_data_products[['product_id']],
                        on='product_id',
                        how='left').groupby('product_id')['revenue'].sum().nlargest(10)

product_id
P029    2935953.79
P030    2563463.42
P032    2273676.11
P033    2136775.68
P020    2045864.53
P017    2036057.76
P038    2028171.73
P010    2016706.46
P026    1988721.50
P005    1896461.94
Name: revenue, dtype: float64

In [1316]:
sales_data_cog.groupby('product_id')['profit'].sum().nlargest(10)

product_id
P029    403997.16
P017    263714.76
P032    260162.56
P008    200506.56
P010    195597.91
P007    188735.75
P005    168124.68
P030    164174.67
P004    162906.63
P034    159445.76
Name: profit, dtype: float64

In [1317]:
sales_data_orders.merge(
    sales_data_products[['product_id','product_name','in_stock']],
                        on='product_id',
                        how='inner').query('in_stock == False')[['product_id','product_name','in_stock']].drop_duplicates()

    product_id  product_name  in_stock
1         P010  ELE-Item-010     False
29        P020  APP-Item-020     False
32        P025  HOM-Item-025     False
46        P017  SPO-Item-017     False
67        P024  GRO-Item-024     False
130       P022  APP-Item-022     False

In [1318]:
sales_data_orders.merge(
    sales_data_products[['product_id','product_name','in_stock']],
                        on='product_id',
                        how='inner')

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week,product_name,in_stock
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday,GRO-Item-005,True
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday,ELE-Item-010,False
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday,GRO-Item-027,True
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday,SPO-Item-029,True
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday,HOM-Item-040,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1202,O00191,2025-07-08,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32,Tuesday,GRO-Item-024,False
1203,O01084,2025-10-25,C0084,P031,6,7443.48,20.0,Partner,Card,35728.70,Saturday,ELE-Item-031,True
1204,O00284,2025-03-15,C0077,P021,2,1794.79,0.0,Partner,Wallet,3589.58,Saturday,HOM-Item-021,True
1205,O00818,2025-02-06,C0047,P015,5,9349.00,15.0,Online,Card,39733.25,Thursday,APP-Item-015,True
1206,O00315,2025-04-26,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95,Saturday,GRO-Item-030,True

In [1319]:
sales_data_orders.merge(
    sales_data_products[['product_id','product_name','in_stock']],
                        on='product_id',
                        how='inner').isna()

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week,product_name,in_stock
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1202,False,False,False,False,False,False,False,False,False,False,False,False,False
1203,False,False,False,False,False,False,False,False,False,False,False,False,False
1204,False,False,False,False,False,False,False,False,False,False,False,False,False
1205,False,False,False,False,False,False,False,False,False,False,False,False,False
1206,False,False,False,False,False,False,False,False,False,False,False,False,False

In [1320]:
sales_data_products.merge(
    sales_data_orders[['product_id']].drop_duplicates(),
    on='product_id',
    how='left',
    indicator=True
).query('in_stock == True and _merge == "left_only"')[
    ['product_id', 'product_name', 'category', 'in_stock']
]

Empty DataFrame
Columns: [product_id, product_name, category, in_stock]
Index: []

In [1321]:
sales_data_orders.groupby('product_id')['customer_id'].nunique()

product_id
P001    16
P002    26
P003    26
P004    24
P005    32
P006    22
P007    29
P008    21
P009    29
P010    31
P011    27
P012    22
P013    23
P014    24
P015    25
P016    21
P017    34
P018    20
P019    28
P020    26
P021    30
P022    23
P023    26
P024    26
P025    36
P026    28
P027    32
P028    19
P029    35
P030    28
P031    29
P032    30
P033    28
P034    28
P035    23
P036    26
P037    34
P038    34
P039    24
P040    29
P999     1
Name: customer_id, dtype: int64

In [1322]:
sales_data_orders.groupby('product_id')['order_id'].count()

product_id
P001    16
P002    28
P003    30
P004    29
P005    36
P006    25
P007    31
P008    24
P009    33
P010    37
P011    31
P012    23
P013    24
P014    27
P015    26
P016    25
P017    36
P018    20
P019    33
P020    29
P021    38
P022    23
P023    27
P024    29
P025    41
P026    29
P027    36
P028    21
P029    42
P030    33
P031    33
P032    32
P033    31
P034    32
P035    29
P036    31
P037    36
P038    36
P039    26
P040    39
P999     1
Name: order_id, dtype: int64

In [1323]:
sales_data_orders.merge(sales_data_products[['product_id','product_name']],
                        on='product_id',
                        how='left').groupby(['product_id','product_name'],as_index=False)['revenue'].sum().query('revenue>500000')

   product_id  product_name     revenue
2        P003  SPO-Item-003  1066134.68
3        P004  APP-Item-004  1124665.08
4        P005  GRO-Item-005  1896461.94
5        P006  BEA-Item-006  1101357.45
6        P007  APP-Item-007  1493519.17
7        P008  APP-Item-008  1823979.60
9        P010  ELE-Item-010  2016706.46
10       P011  ELE-Item-011  1362551.65
12       P013  HOM-Item-013  1828981.69
13       P014  BEA-Item-014   697294.82
14       P015  APP-Item-015   787653.25
15       P016  GRO-Item-016  1885782.55
16       P017  SPO-Item-017  2036057.76
17       P018  HOM-Item-018  1476957.70
18       P019  GRO-Item-019   855318.42
19       P020  APP-Item-020  2045864.53
21       P022  APP-Item-022  1319121.42
22       P023  APP-Item-023   609943.68
23       P024  GRO-Item-024  1284234.01
24       P025  HOM-Item-025   740895.87
25       P026  ELE-Item-026  1988721.50
26       P027  GRO-Item-027   506205.01
27       P028  BEA-Item-028   577031.08
28       P029  SPO-Item-029  2935953.79
29       P030  GRO-Item-030  2563463.42
30       P031  ELE-Item-031   944577.61
31       P032  GRO-Item-032  2273676.11
32       P033  SPO-Item-033  2136775.68
33       P034  GRO-Item-034  1165482.85
34       P035  APP-Item-035  1362133.80
35       P036  SPO-Item-036   811502.18
36       P037  HOM-Item-037   701544.81
37       P038  ELE-Item-038  2028171.73
38       P039  APP-Item-039  1471660.88
39       P040  HOM-Item-040  1612079.98

In [1324]:
sales_data_cog.merge(sales_data_products[['product_id','category']],
                     on='product_id',
                     how='left').groupby('category', as_index=False)['profit'].sum().query('profit<0')

Empty DataFrame
Columns: [category, profit]
Index: []

In [1325]:
sales_data=sales_data_orders.merge(sales_data_customers[['customer_id','customer_name','region','segment']],
                        on='customer_id',
                        how='left').merge(sales_data_products[['product_id','product_name','category']],
                                          on='product_id',
                                            how='left')[['order_id','customer_name','region','segment','product_name','category','revenue']]

In [1326]:
sales_data

C:\Users\Tranzita\AppData\Roaming\Python\Python314\site-packages\IPython\core\displayhook.py:291: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  warn('Output cache limit (currently {sz} entries) hit.\n'

,order_id,customer_name,region,segment,product_name,category,revenue
0,O00001,Customer 106,East,Corporate,GRO-Item-005,Grocery,61938.59
1,O00002,Customer 20,North,Corporate,ELE-Item-010,Electronics,91419.15
2,O00003,Customer 72,West,Retail,GRO-Item-027,Grocery,18564.98
3,O00004,Customer 49,North,Corporate,SPO-Item-029,Sports,86161.52
4,O00005,Customer 73,East,Wholesale,HOM-Item-040,Home,11936.42
...,...,...,...,...,...,...,...
1203,O00191,Customer 4,South,Corporate,GRO-Item-024,Grocery,66046.32
1204,O01084,Customer 84,North,Wholesale,ELE-Item-031,Electronics,35728.70
1205,O00284,Customer 77,West,Wholesale,HOM-Item-021,Home,3589.58
1206,O00818,Customer 47,West,Retail,APP-Item-015,Apparel,39733.25
1207,O00315,Customer 52,East,Corporate,GRO-Item-030,Grocery,110684.95

In [1327]:
sales_data.groupby(['region','category'])['revenue'].sum()

region  category
East    Apparel        2009282.63
        Beauty          622067.93
        Electronics    1933331.23
        Grocery        3196392.68
        Home           1803945.19
        Sports         1806334.51
North   Apparel        4233528.29
        Beauty          875372.44
        Electronics    2400341.81
        Grocery        3999963.21
        Home           1546469.77
        Sports         3845401.31
South   Apparel        2944423.22
        Beauty          621780.28
        Electronics    1714732.80
        Grocery        2208121.40
        Home           1490455.52
        Sports         2028410.31
West    Apparel        3193524.65
        Beauty          527028.37
        Electronics    2192295.71
        Grocery        2922316.10
        Home           1704731.61
        Sports         1651722.88
north   Apparel          12299.57
        Electronics     100027.40
        Grocery         294429.41
        Home             30501.95
        Sports           18268.80
Name: revenue, dtype: float64

In [1328]:
sales_data_cog

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week,cost_price,cogs,profit,profit_margin
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday,11629.50,46518.00,4670.13,28.651755
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday,12997.40,64987.00,5286.43,28.913143
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday,3111.26,15556.30,1014.29,24.585570
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday,11921.40,47685.60,9618.98,44.655572
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday,9708.00,9708.00,3554.69,26.802180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1203,O00191,2025-07-08,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32,Tuesday,12025.52,60127.60,2651.44,18.065321
1204,O01084,2025-10-25,C0084,P031,6,7443.48,20.0,Partner,Card,35728.70,Saturday,4447.09,26682.54,2996.39,40.255230
1205,O00284,2025-03-15,C0077,P021,2,1794.79,0.0,Partner,Wallet,3589.58,Saturday,1478.80,2957.60,315.99,17.605959
1206,O00818,2025-02-06,C0047,P015,5,9349.00,15.0,Online,Card,39733.25,Thursday,5729.55,28647.75,3619.45,38.714836
1207,O00315,2025-04-26,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95,Saturday,17162.00,85810.00,4974.99,22.473652

In [1329]:
sales_data_orders.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday

In [1330]:
sales_data_customers.head(1)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27

In [1331]:
sales_data_products.head(1)

  product_id  product_name category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001  Grocery     2916.58     2252.96      True

In [1332]:
sales_data_avg_order = sales_data_orders.merge(
    sales_data_customers[['customer_id', 'region']],
    on='customer_id',
    how='left'
)

channel_revenue = sales_data_avg_order.groupby(
    ['region', 'channel'],
    as_index=False
)['revenue'].sum()

highest_channel = (
    channel_revenue
    .sort_values('revenue', ascending=False)
    .groupby('region')
    .head(1)
    .reset_index(drop=True)
)

highest_channel

   region  channel     revenue
0   North    Store  6003964.31
1    West   Online  5128464.82
2    East    Store  4139425.56
3   South  Partner  3865976.70
4  north    Online   204228.51

In [1333]:
sales_data_avg_order=sales_data_orders.merge(sales_data_customers[['customer_id','region']],
                                             on='customer_id',
                                                how='left')
sales_data_avg_order.groupby(['region','channel'],as_index=False)['revenue'].mean()

    region  channel       revenue
0     East   Online  45749.842073
1     East  Partner  40001.391778
2     East    Store  42674.490309
3    North   Online  43117.939750
4    North  Partner  41470.722826
5    North    Store  44473.809704
6    South   Online  46060.040390
7    South  Partner  43437.940449
8    South    Store  44941.546500
9     West   Online  45384.644425
10    West  Partner  39065.130202
11    West    Store  41502.683247
12  north    Online  68076.170000
13  north   Partner  32219.544000
14  north     Store  45100.450000

In [1334]:
sales_data_revenue_product=sales_data_orders.merge(sales_data_customers[['customer_id','region','customer_name']],
                        on='customer_id',
                        how='left').merge(sales_data_products[['product_id','category','product_name']],
                                          on='product_id',
                                            how='left')

In [1335]:
sales_data_revenue_product.groupby(['region','product_name'], as_index=False)['revenue'].sum().groupby('region').head(1)

     region  product_name    revenue
0      East  APP-Item-002   58422.94
40    North  APP-Item-002  106535.96
80    South  APP-Item-002  106355.09
120    West  APP-Item-002   70903.39
160  north   APP-Item-002   12299.57

In [1336]:
sales_data_revenue_product.groupby(['region','customer_name'], as_index=False)['revenue'].sum().groupby('region').head(1)

     region   customer_name    revenue
0      East    Customer 101  337152.24
31    North    Customer 107  529516.50
66    South    Customer 4    579063.90
93     West     Customer 10  571518.25
119  north      Customer 16  455527.13

In [1337]:
sales_data_orders.merge(sales_data_customers[['customer_id','customer_name','segment']],
                        on='customer_id',
                        how='left').merge(sales_data_products[['product_id','product_name','category']],
                                          on='product_id',
                                            how='left')

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week,customer_name,segment,product_name,category
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday,Customer 106,Corporate,GRO-Item-005,Grocery
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday,Customer 20,Corporate,ELE-Item-010,Electronics
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday,Customer 72,Retail,GRO-Item-027,Grocery
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday,Customer 49,Corporate,SPO-Item-029,Sports
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday,Customer 73,Wholesale,HOM-Item-040,Home
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1203,O00191,2025-07-08,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32,Tuesday,Customer 4,Corporate,GRO-Item-024,Grocery
1204,O01084,2025-10-25,C0084,P031,6,7443.48,20.0,Partner,Card,35728.70,Saturday,Customer 84,Wholesale,ELE-Item-031,Electronics
1205,O00284,2025-03-15,C0077,P021,2,1794.79,0.0,Partner,Wallet,3589.58,Saturday,Customer 77,Wholesale,HOM-Item-021,Home
1206,O00818,2025-02-06,C0047,P015,5,9349.00,15.0,Online,Card,39733.25,Thursday,Customer 47,Retail,APP-Item-015,Apparel
1207,O00315,2025-04-26,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95,Saturday,Customer 52,Corporate,GRO-Item-030,Grocery

In [1338]:
sales_data_orders.merge(sales_data_customers[['customer_id','region']],
                        on='customer_id',
                        how='left').merge(sales_data_products[['product_id','category']],
                                          on='product_id',
                                            how='left').groupby(['region','category'], as_index=False)['revenue'].sum().nlargest(5, 'revenue')

   region category     revenue
6   North  Apparel  4233528.29
9   North  Grocery  3999963.21
11  North   Sports  3845401.31
3    East  Grocery  3196392.68
18   West  Apparel  3193524.65

In [1339]:
sales_data_quantity=sales_data_orders.merge(
    sales_data_customers[['customer_id','customer_name','segment']],
                        on='customer_id',
                        how='left').merge(
                            sales_data_products[['product_id','product_name','category']],
                                          on='product_id',
                                            how='left')[['order_id','customer_name','segment','product_name','category','quantity']]

In [1340]:
sales_data_quantity

     order_id   customer_name    segment  product_name     category  quantity
0      O00001    Customer 106  Corporate  GRO-Item-005      Grocery         4
1      O00002     Customer 20  Corporate  ELE-Item-010  Electronics         5
2      O00003     Customer 72     Retail  GRO-Item-027      Grocery         5
3      O00004     Customer 49  Corporate  SPO-Item-029       Sports         4
4      O00005     Customer 73  Wholesale  HOM-Item-040         Home         1
...       ...             ...        ...           ...          ...       ...
1203   O00191    Customer 4    Corporate  GRO-Item-024      Grocery         5
1204   O01084     Customer 84  Wholesale  ELE-Item-031  Electronics         6
1205   O00284     Customer 77  Wholesale  HOM-Item-021         Home         2
1206   O00818     Customer 47     Retail  APP-Item-015      Apparel         5
1207   O00315     Customer 52  Corporate  GRO-Item-030      Grocery         5

[1208 rows x 6 columns]

In [1341]:
sales_data_quantity.groupby(['segment','category'])['quantity'].sum()

segment    category
Corporate  Apparel        292
           Beauty         168
           Electronics    177
           Grocery        350
           Home           216
           Sports         229
Retail     Apparel        336
           Beauty          79
           Electronics    188
           Grocery        264
           Home           191
           Sports         212
Wholesale  Apparel        325
           Beauty         131
           Electronics    225
           Grocery        341
           Home           263
           Sports         207
retail     Apparel         11
           Electronics      5
           Grocery          5
           Sports          11
Name: quantity, dtype: int64

In [1342]:
sales_data_cog

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week,cost_price,cogs,profit,profit_margin
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday,11629.50,46518.00,4670.13,28.651755
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday,12997.40,64987.00,5286.43,28.913143
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday,3111.26,15556.30,1014.29,24.585570
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday,11921.40,47685.60,9618.98,44.655572
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday,9708.00,9708.00,3554.69,26.802180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1203,O00191,2025-07-08,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32,Tuesday,12025.52,60127.60,2651.44,18.065321
1204,O01084,2025-10-25,C0084,P031,6,7443.48,20.0,Partner,Card,35728.70,Saturday,4447.09,26682.54,2996.39,40.255230
1205,O00284,2025-03-15,C0077,P021,2,1794.79,0.0,Partner,Wallet,3589.58,Saturday,1478.80,2957.60,315.99,17.605959
1206,O00818,2025-02-06,C0047,P015,5,9349.00,15.0,Online,Card,39733.25,Thursday,5729.55,28647.75,3619.45,38.714836
1207,O00315,2025-04-26,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95,Saturday,17162.00,85810.00,4974.99,22.473652

In [1343]:
sales_data_cog.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week,cost_price,cogs,profit,profit_margin
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday,11629.5,46518.0,4670.13,28.651755

In [1344]:
sales_data_products.head(1)

  product_id  product_name category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001  Grocery     2916.58     2252.96      True

In [1345]:
sales_data_customers.head(1)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27

In [1346]:
sales_data_profit=sales_data_cog.merge(sales_data_products[['product_id','category']],
                      on='product_id',
                      how='left').merge(sales_data_customers[['customer_id','region']],
                                        on='customer_id',
                                        how='left')
sales_data_profit

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week,cost_price,cogs,profit,profit_margin,category,region
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday,11629.50,46518.00,4670.13,28.651755,Grocery,East
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday,12997.40,64987.00,5286.43,28.913143,Electronics,North
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday,3111.26,15556.30,1014.29,24.585570,Grocery,West
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday,11921.40,47685.60,9618.98,44.655572,Sports,North
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday,9708.00,9708.00,3554.69,26.802180,Home,East
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1203,O00191,2025-07-08,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32,Tuesday,12025.52,60127.60,2651.44,18.065321,Grocery,South
1204,O01084,2025-10-25,C0084,P031,6,7443.48,20.0,Partner,Card,35728.70,Saturday,4447.09,26682.54,2996.39,40.255230,Electronics,North
1205,O00284,2025-03-15,C0077,P021,2,1794.79,0.0,Partner,Wallet,3589.58,Saturday,1478.80,2957.60,315.99,17.605959,Home,West
1206,O00818,2025-02-06,C0047,P015,5,9349.00,15.0,Online,Card,39733.25,Thursday,5729.55,28647.75,3619.45,38.714836,Apparel,West
1207,O00315,2025-04-26,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95,Saturday,17162.00,85810.00,4974.99,22.473652,Grocery,East

In [1347]:
sales_data_profit.groupby(['region','category'])['profit'].sum()

region  category
East    Apparel        232983.93
        Beauty          38552.45
        Electronics    134537.52
        Grocery        282585.69
        Home           121605.44
        Sports         204650.61
North   Apparel        401396.63
        Beauty          55680.65
        Electronics    195840.19
        Grocery        352580.46
        Home           136174.95
        Sports         422841.71
South   Apparel        231284.31
        Beauty          41117.35
        Electronics    130853.93
        Grocery        179656.51
        Home           107403.62
        Sports         247116.80
West    Apparel        295969.41
        Beauty          34687.93
        Electronics    151510.12
        Grocery        244510.04
        Home           142713.68
        Sports         221759.30
north   Apparel          1516.65
        Electronics      8914.95
        Grocery         25743.49
        Home             2304.35
        Sports           7325.41
Name: profit, dtype: float64

In [1348]:
sales_data_returns['return_id'].shape[0]

90

In [1349]:
sales_data_returns['return_id'].nunique()

90

In [1350]:
sales_data_returns['refund_amount'].sum()

np.float64(2742524.7699999996)

In [1351]:
sales_data_returns['refund_amount'].mean()

np.float64(30472.497444444438)

In [1352]:
sales_data_returns

   return_id order_id return_date            reason  refund_amount
0      R0001   O01050  2025-05-20     Late Delivery        1917.72
1      R0002   O00477  2025-02-11           Damaged       14780.26
2      R0003   O00062  2025-07-31     Late Delivery       14078.53
3      R0004   O00911  2025-03-03  Not as described       28091.19
4      R0005   O00069  2025-10-13  Not as described       33479.32
..       ...      ...         ...               ...            ...
85     R0086   O00577  2025-05-18  Not as described       13929.93
86     R0087   O00843  2025-07-24           Damaged       44266.66
87     R0088   O00923  2025-10-01           Damaged       28322.28
88     R0089   O00657  2025-03-18        Wrong Item       67644.59
89     R0090   O00084  2025-08-30           Damaged       18703.00

[90 rows x 5 columns]

In [1353]:
sales_data_returns.groupby(['reason'],as_index=False)['refund_amount'].sum()

             reason  refund_amount
0           Damaged      591433.16
1     Late Delivery      524675.43
2  Not as described      678083.68
3             Other      293763.68
4        Wrong Item      654568.82

In [1354]:
sales_data_orders.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday

In [1355]:
sales_data_returns.head(1)

  return_id order_id return_date         reason  refund_amount
0     R0001   O01050  2025-05-20  Late Delivery        1917.72

In [1356]:
sales_data_returns.merge(sales_data_orders[['order_id','revenue']], 
                         on='order_id',
                         how='left')[['return_id','order_id','revenue','refund_amount']]

   return_id order_id   revenue  refund_amount
0      R0001   O01050   3713.00        1917.72
1      R0002   O00477  21914.95       14780.26
2      R0003   O00062  24615.84       14078.53
3      R0004   O00911  55013.70       28091.19
4      R0005   O00069  74852.50       33479.32
..       ...      ...       ...            ...
86     R0086   O00577  26471.70       13929.93
87     R0087   O00843  64811.21       44266.66
88     R0088   O00923  48898.89       28322.28
89     R0089   O00657  69341.05       67644.59
90     R0090   O00084  59495.78       18703.00

[91 rows x 4 columns]

In [1357]:
sales_data_returns.merge(sales_data_orders[['order_id','revenue','order_date']], 
                         on='order_id',
                         how='left')[['return_id','order_id','order_date']]

   return_id order_id order_date
0      R0001   O01050 2025-05-01
1      R0002   O00477 2025-01-29
2      R0003   O00062 2025-07-22
3      R0004   O00911 2025-02-17
4      R0005   O00069 2025-10-04
..       ...      ...        ...
86     R0086   O00577 2025-05-15
87     R0087   O00843 2025-07-21
88     R0088   O00923 2025-09-17
89     R0089   O00657 2025-03-11
90     R0090   O00084 2025-08-16

[91 rows x 3 columns]

In [1358]:
sales_data_returns.merge(sales_data_orders[['order_id']],
                        on='order_id',
                        how='left')[['order_id','return_id']]

   order_id return_id
0    O01050     R0001
1    O00477     R0002
2    O00062     R0003
3    O00911     R0004
4    O00069     R0005
..      ...       ...
86   O00577     R0086
87   O00843     R0087
88   O00923     R0088
89   O00657     R0089
90   O00084     R0090

[91 rows x 2 columns]

In [1359]:
sales_data_orders[~sales_data_orders['order_id'].isin(sales_data_returns['order_id'])]

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday
...,...,...,...,...,...,...,...,...,...,...,...
1203,O00191,2025-07-08,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32,Tuesday
1204,O01084,2025-10-25,C0084,P031,6,7443.48,20.0,Partner,Card,35728.70,Saturday
1205,O00284,2025-03-15,C0077,P021,2,1794.79,0.0,Partner,Wallet,3589.58,Saturday
1206,O00818,2025-02-06,C0047,P015,5,9349.00,15.0,Online,Card,39733.25,Thursday
1207,O00315,2025-04-26,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95,Saturday

In [1360]:
sales_data_returns.merge(sales_data_orders[['order_id','revenue']],
                         on='order_id',
                         how='left').groupby('order_id')['revenue'].first()

order_id
O00016    123698.30
O00048    109612.80
O00062     24615.84
O00068     23936.74
O00069     74852.50
            ...
O01137     39385.34
O01146     15748.88
O01180     28899.72
O01187    136972.80
O01198     58707.84
Name: revenue, Length: 90, dtype: float64

In [1361]:
sales_data_returns.merge(sales_data_orders[['order_id','revenue']],
                         on='order_id',
                         how='left').groupby('order_id')['revenue'].mean()

order_id
O00016    123698.30
O00048    109612.80
O00062     24615.84
O00068     23936.74
O00069     74852.50
            ...
O01137     39385.34
O01146     15748.88
O01180     28899.72
O01187    136972.80
O01198     58707.84
Name: revenue, Length: 90, dtype: float64

In [1362]:
returned_orders=sales_data_returns['order_id'].unique()
sales_data_orders[sales_data_orders['order_id'].isin(returned_orders)]['revenue'].mean()

np.float64(47029.93494505495)

In [1363]:
returned_orders=sales_data_returns['order_id'].unique()
sales_data_orders[~sales_data_orders['order_id'].isin(returned_orders)]['revenue'].mean()

np.float64(42790.55246195166)

In [1364]:
(sales_data_returns['order_id'].nunique()/sales_data_orders['order_id'].nunique())*100

7.5

In [1365]:
sales_data_orders.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday

In [1366]:
sales_data_returns.head(1)

  return_id order_id return_date         reason  refund_amount
0     R0001   O01050  2025-05-20  Late Delivery        1917.72

In [1367]:
sales_data_orders['order_id'].nunique()

1200

In [1368]:
sales_data_returns['order_id'].nunique()

90

In [1369]:
sales_data_return_orders=sales_data_returns.merge(sales_data_orders[['order_id','channel']],
                         on='order_id',
                        how='left')
sales_data_return_orders

   return_id order_id return_date            reason  refund_amount  channel
0      R0001   O01050  2025-05-20     Late Delivery        1917.72   Online
1      R0002   O00477  2025-02-11           Damaged       14780.26   Online
2      R0003   O00062  2025-07-31     Late Delivery       14078.53   Online
3      R0004   O00911  2025-03-03  Not as described       28091.19    Store
4      R0005   O00069  2025-10-13  Not as described       33479.32    Store
..       ...      ...         ...               ...            ...      ...
86     R0086   O00577  2025-05-18  Not as described       13929.93  Partner
87     R0087   O00843  2025-07-24           Damaged       44266.66    Store
88     R0088   O00923  2025-10-01           Damaged       28322.28  Partner
89     R0089   O00657  2025-03-18        Wrong Item       67644.59  Partner
90     R0090   O00084  2025-08-30           Damaged       18703.00   Online

[91 rows x 6 columns]

In [1370]:
sales_data_return_orders['return_count'] = (
    sales_data_return_orders.groupby('channel')['return_id']
    .transform('count')
)

In [1371]:
sales_data_return_orders.columns

Index(['return_id', 'order_id', 'return_date', 'reason', 'refund_amount',
       'channel', 'return_count'],
      dtype='str')

In [1372]:
sales_data_return_orders = sales_data_return_orders[['channel', 'return_count']].drop_duplicates()
sales_data_return_orders

   channel  return_count
0   Online            25
3    Store            35
6  Partner            31

In [1373]:
sales_data_orders['total_count'] = sales_data_orders.groupby(['channel'])['channel'].transform('count')

In [1374]:
sales_data_orders

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week,total_count
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday,422
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday,395
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday,395
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday,391
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday,395
...,...,...,...,...,...,...,...,...,...,...,...,...
1203,O00191,2025-07-08,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32,Tuesday,391
1204,O01084,2025-10-25,C0084,P031,6,7443.48,20.0,Partner,Card,35728.70,Saturday,422
1205,O00284,2025-03-15,C0077,P021,2,1794.79,0.0,Partner,Wallet,3589.58,Saturday,422
1206,O00818,2025-02-06,C0047,P015,5,9349.00,15.0,Online,Card,39733.25,Thursday,395
1207,O00315,2025-04-26,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95,Saturday,391

In [1375]:
#sales_data_return_orders.merge(sales_data_orders.groupBy(['channel']).agg(),
#                               on='channel',
 #                              how="outer"
#)

In [1376]:
sales_channel=sales_data_orders[['channel', 'total_count']].drop_duplicates()
sales_channel

   channel  total_count
0  Partner          422
1   Online          395
3    Store          391

In [1377]:
sales_return_data=sales_data_return_orders.merge(sales_channel)
sales_return_data

   channel  return_count  total_count
0   Online            25          395
1    Store            35          391
2  Partner            31          422

In [1378]:
sales_return_data['Return_Rate']=(sales_return_data['return_count']/sales_return_data['total_count'])*100
sales_return_data

   channel  return_count  total_count  Return_Rate
0   Online            25          395     6.329114
1    Store            35          391     8.951407
2  Partner            31          422     7.345972

In [1399]:
sales_return_data.nlargest(1,'Return_Rate')

  channel  return_count  total_count  Return_Rate
1   Store            35          391     8.951407

In [1379]:
sales_data_products.head(1)

  product_id  product_name category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001  Grocery     2916.58     2252.96      True

In [1380]:
sales_data_orders.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week,total_count
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday,422

In [1381]:
sales_data_returns.head(1)

  return_id order_id return_date         reason  refund_amount
0     R0001   O01050  2025-05-20  Late Delivery        1917.72

In [1390]:
sales_data_customers.head(1)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27

In [1382]:
sales_data_category=sales_data_orders.merge(sales_data_products[['product_id','category']],
                                            on='product_id',
                                            how='left').merge(sales_data_returns[['order_id','return_id']],
                                                              on='order_id',
                                                              how='left')
sales_data_category

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week,total_count,category,return_id
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday,422,Grocery,NaN
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday,395,Electronics,NaN
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday,395,Grocery,NaN
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday,391,Sports,NaN
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday,395,Home,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1203,O00191,2025-07-08,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32,Tuesday,391,Grocery,NaN
1204,O01084,2025-10-25,C0084,P031,6,7443.48,20.0,Partner,Card,35728.70,Saturday,422,Electronics,NaN
1205,O00284,2025-03-15,C0077,P021,2,1794.79,0.0,Partner,Wallet,3589.58,Saturday,422,Home,NaN
1206,O00818,2025-02-06,C0047,P015,5,9349.00,15.0,Online,Card,39733.25,Thursday,395,Apparel,NaN
1207,O00315,2025-04-26,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95,Saturday,391,Grocery,NaN

In [1388]:
sales_data_return_rate=sales_data_category.groupby('category').agg(
    returned_orders=('return_id','count'),
    total_orders=('order_id','nunique')
)
sales_data_return_rate

             returned_orders  total_orders
category
Apparel                   15           270
Beauty                     9           106
Electronics               13           165
Grocery                   24           269
Home                      14           196
Sports                    16           193

In [1389]:
sales_data_return_rate['return_rate']=((sales_data_return_rate['returned_orders']/sales_data_return_rate['total_orders'])*100)
sales_data_return_rate

             returned_orders  total_orders  return_rate
category
Apparel                   15           270     5.555556
Beauty                     9           106     8.490566
Electronics               13           165     7.878788
Grocery                   24           269     8.921933
Home                      14           196     7.142857
Sports                    16           193     8.290155

In [1393]:
sales_data_return_region=sales_data_orders.merge(sales_data_customers[['customer_id','region']],
                                                 on='customer_id',
                                                 how='left').merge(sales_data_returns[['order_id','return_id']],
                                                              on='order_id',
                                                              how='left')
sales_data_return_region

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week,total_count,region,return_id
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday,422,East,NaN
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday,395,North,NaN
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday,395,West,NaN
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday,391,North,NaN
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday,395,East,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1203,O00191,2025-07-08,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32,Tuesday,391,South,NaN
1204,O01084,2025-10-25,C0084,P031,6,7443.48,20.0,Partner,Card,35728.70,Saturday,422,North,NaN
1205,O00284,2025-03-15,C0077,P021,2,1794.79,0.0,Partner,Wallet,3589.58,Saturday,422,West,NaN
1206,O00818,2025-02-06,C0047,P015,5,9349.00,15.0,Online,Card,39733.25,Thursday,395,West,NaN
1207,O00315,2025-04-26,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95,Saturday,391,East,NaN

In [1396]:
sales_data_return_region_rate=sales_data_return_region.groupby('region').agg(
    returned_orders=('return_id','count'),
        total_orders=('order_id','nunique')
)
sales_data_return_region_rate

        returned_orders  total_orders
region
East                 28           268
North                25           391
South                21           245
West                 17           285
north                 0            10

In [1398]:
sales_data_return_region_rate['Return_Rate']=((sales_data_return_region_rate['returned_orders']/
                                               sales_data_return_region_rate['total_orders'])*100)
sales_data_return_region_rate

        returned_orders  total_orders  Return_Rate
region
East                 28           268    10.447761
North                25           391     6.393862
South                21           245     8.571429
West                 17           285     5.964912
north                 0            10     0.000000