In [1]:
import pandas as pd

In [2]:
sales_data_orders=pd.read_excel(r"D:\Python Test\sales_data.xlsx", sheet_name="Orders")
sales_data_customers=pd.read_excel(r"D:\Python Test\sales_data.xlsx", sheet_name="Customers")
sales_data_products=pd.read_excel(r"D:\Python Test\sales_data.xlsx", sheet_name="Products")
sales_data_returns=pd.read_excel(r"D:\Python Test\sales_data.xlsx", sheet_name="Returns")

In [3]:
sales_data_orders.head(2)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15

In [4]:
sales_data_orders.groupby("channel").aggregate({"order_id":"count"})

         order_id
channel
Online        395
Partner       422
Store         391

In [5]:
sales_data_orders['revenue'] = sales_data_orders['revenue'].astype(str).str.replace("₹", "", regex=False).astype(float)

In [6]:
sales_data_orders.groupby("channel").aggregate({"revenue":"sum"})

             revenue
channel
Online   17804956.26
Partner  17247193.82
Store    17024621.10

In [7]:
sales_data_orders.groupby("channel").aggregate({"revenue":"mean"})

              revenue
channel
Online   45075.838633
Partner  40870.127536
Store    43541.230435

In [8]:
sales_data_orders.groupby("channel").aggregate({"quantity":"count"})

         quantity
channel
Online        395
Partner       422
Store         391

In [9]:
sales_data_orders.groupby("payment_method").aggregate({"order_id":"count"})

                order_id
payment_method
COD                  238
Card                 241
NetBanking           253
UPI                  217
Wallet               239

In [10]:
sales_data_orders.groupby("payment_method").aggregate({"order_id":"count"}).rename(columns={"order_id":"Orders Placed"})

                Orders Placed
payment_method
COD                       238
Card                      241
NetBanking                253
UPI                       217
Wallet                    239

In [11]:
sales_data_orders.groupby("payment_method").aggregate({"revenue":"sum"}).rename(columns={"revenue":"Revenue Collected"})

                Revenue Collected
payment_method
COD                   10764083.04
Card                  10122294.82
NetBanking            10922704.99
UPI                    9363177.40
Wallet                10159386.84

In [12]:
sales_data_orders.groupby("payment_method").aggregate({"revenue":"mean"}).rename(columns={"revenue":"Average Revenue"})

                Average Revenue
payment_method
COD                45227.239664
Card               42001.223320
NetBanking         43172.746996
UPI                43148.282949
Wallet             42507.894728

In [13]:
sales_data_customers.head(2)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27
1,C0002,Customer 2,cust2@example.com,Wholesale,East,Patna,2023-05-04

In [14]:
sales_data_customers.groupby("segment").aggregate({"customer_id":"count"})

           customer_id
segment
Corporate           40
Retail              34
Wholesale           45
retail               1

In [15]:
sales_data_customers.groupby("segment").aggregate({"region":"count"})

           region
segment
Corporate      40
Retail         34
Wholesale      45
retail          1

In [16]:
sales_data_customers.groupby("city").aggregate({"customer_id":"count"}).rename(columns={"customer_id":"Total Customers"})

             Total Customers
city
Ahmedabad                  6
Bengaluru                  5
Bhubaneswar                8
Chandigarh                12
Chennai                    6
Delhi                      8
Guwahati                   6
Hyderabad                  9
Jaipur                     9
Kochi                      6
Kolkata                    7
Lucknow                    6
MUMBAI                     1
Mumbai                     4
Patna                     10
Pune                      10
Surat                      7

In [17]:
sales_data_products.head(2)

  product_id  product_name category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001  Grocery     2916.58     2252.96      True
1       P002  APP-Item-002  Apparel     3617.52     2100.87      True

In [18]:
sales_data_products.groupby("category").aggregate({"product_id":"count"})

             product_id
category
Apparel              10
Beauty                4
Electronics           5
Grocery               9
Home                  6
Sports                6

In [19]:
sales_data_products.groupby("category").aggregate({"unit_price":"mean"})

               unit_price
category
Apparel      14095.019000
Beauty        8509.382500
Electronics  15372.922000
Grocery      14052.264444
Home         12688.400000
Sports       14401.065000

In [20]:
sales_data_returns.head(2)

  return_id order_id return_date         reason  refund_amount
0     R0001   O01050  2025-05-20  Late Delivery        1917.72
1     R0002   O00477  2025-02-11        Damaged       14780.26

In [21]:
sales_data_returns.groupby("reason").aggregate({"return_id":"count"})

                  return_id
reason
Damaged                  20
Late Delivery            18
Not as described         20
Other                    12
Wrong Item               20

In [22]:
sales_data_returns.groupby("reason").aggregate({"refund_amount":"sum"})

                  refund_amount
reason
Damaged               591433.16
Late Delivery         524675.43
Not as described      678083.68
Other                 293763.68
Wrong Item            654568.82

In [23]:
sales_data_returns.groupby("reason").aggregate({"refund_amount":"mean"})

                  refund_amount
reason
Damaged            29571.658000
Late Delivery      29148.635000
Not as described   33904.184000
Other              24480.306667
Wrong Item         32728.441000

In [24]:
sales_data_orders.head(5)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15
2,O00003,2025-11-13 00:00:00,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98
3,O00004,2025-10-29 00:00:00,C0049,P029,4,21540.38,0.0,Store,COD,86161.52
4,O00005,2025-02-20 00:00:00,C0073,P040,1,13262.69,10.0,Online,Card,11936.42

In [25]:
sales_data_orders.groupby("channel").aggregate(
    {"order_id":"count",
    "revenue":['sum','mean'],
    #"revenue":"mean",
    "quantity":"count"})

        order_id      revenue               quantity
           count          sum          mean    count
channel
Online       395  17804956.26  45075.838633      395
Partner      422  17247193.82  40870.127536      422
Store        391  17024621.10  43541.230435      391

In [26]:
sales_data_orders.groupby("channel").aggregate({"revenue":"sum"})

             revenue
channel
Online   17804956.26
Partner  17247193.82
Store    17024621.10

In [27]:
sales_data_orders.groupby("payment_method").aggregate(
    {
    "order_id":"count",
    "revenue":['sum','mean']
    }
)

               order_id      revenue
                  count          sum          mean
payment_method
COD                 238  10764083.04  45227.239664
Card                241  10122294.82  42001.223320
NetBanking          253  10922704.99  43172.746996
UPI                 217   9363177.40  43148.282949
Wallet              239  10159386.84  42507.894728

In [28]:
sales_data_products.head(2)

  product_id  product_name category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001  Grocery     2916.58     2252.96      True
1       P002  APP-Item-002  Apparel     3617.52     2100.87      True

In [29]:
sales_data_products.groupby("category").aggregate(
    {
    "product_id":"count",
    "unit_price":"mean",
    "cost_price":"mean"
    }
)

             product_id    unit_price    cost_price
category
Apparel              10  14095.019000   9780.892000
Beauty                4   8509.382500   6796.690000
Electronics           5  15372.922000  11680.094000
Grocery               9  14052.264444  10177.105556
Home                  6  12688.400000   9660.716667
Sports                6  14401.065000   9116.828333

In [30]:
sales_data_customers.head(2)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27
1,C0002,Customer 2,cust2@example.com,Wholesale,East,Patna,2023-05-04

In [31]:
sales_data_customers.groupby("region").aggregate({
    "customer_id":"count",
    "city":"count"
})

        customer_id  city
region
East             31    31
North            35    35
South            27    27
West             26    26
north             1     1

In [32]:
sales_data_returns.head(2)

  return_id order_id return_date         reason  refund_amount
0     R0001   O01050  2025-05-20  Late Delivery        1917.72
1     R0002   O00477  2025-02-11        Damaged       14780.26

In [33]:
sales_data_returns.groupby("reason").aggregate({
    "return_id":['count'],
    "refund_amount":['sum','mean']
})

                 return_id refund_amount
                     count           sum          mean
reason
Damaged                 20     591433.16  29571.658000
Late Delivery           18     524675.43  29148.635000
Not as described        20     678083.68  33904.184000
Other                   12     293763.68  24480.306667
Wrong Item              20     654568.82  32728.441000

In [34]:
sales_data_orders.head(2)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15

In [35]:
sales_data_orders.groupby("channel").aggregate({
    "revenue":['min','max','mean','sum']
})

         revenue
             min        max          mean          sum
channel
Online   1705.05  147796.50  45075.838633  17804956.26
Partner  1525.57  143620.44  40870.127536  17247193.82
Store    1705.05  148437.96  43541.230435  17024621.10

In [36]:
sales_data_orders.groupby("channel").aggregate({"revenue":"sum"}).sort_values(by="revenue", ascending=False)

             revenue
channel
Online   17804956.26
Partner  17247193.82
Store    17024621.10

In [37]:
sales_data_orders.groupby("channel")["revenue"].sum().nlargest(1)

channel
Online    17804956.26
Name: revenue, dtype: float64

In [38]:
sales_data_orders.groupby("channel").aggregate({"quantity":"mean"}).idxmax()

quantity    Online
dtype: str

In [39]:
sales_data_orders.groupby("channel")["revenue"].mean().nlargest(1)

channel
Online    45075.838633
Name: revenue, dtype: float64

In [40]:
sales_data_orders.groupby("payment_method")["revenue"].sum().nlargest(1)

payment_method
NetBanking    10922704.99
Name: revenue, dtype: float64

In [41]:
sales_data_products.head(2)

  product_id  product_name category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001  Grocery     2916.58     2252.96      True
1       P002  APP-Item-002  Apparel     3617.52     2100.87      True

In [42]:
sales_data_products.groupby("category")["unit_price"].mean().nlargest(1)

category
Electronics    15372.922
Name: unit_price, dtype: float64

In [43]:
sales_data_customers.head(2)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27
1,C0002,Customer 2,cust2@example.com,Wholesale,East,Patna,2023-05-04

In [44]:
sales_data_customers.groupby("region")["customer_id"].count().nlargest(1)

region
North    35
Name: customer_id, dtype: int64

In [45]:
sales_data_customers.groupby("city")["customer_id"].nunique().reset_index(name="customer_count").query("customer_count>10")

         city  customer_count
3  Chandigarh              12

In [46]:
sales_data_orders.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59

In [47]:
sales_data_orders.groupby("channel")["order_id"].nunique().reset_index(name="count_orders").query("count_orders>200")

   channel  count_orders
0   Online           393
1  Partner           419
2    Store           388

In [48]:
sales_data_orders.groupby("payment_method")['revenue'].sum().reset_index(name="Total_Revenue").query("Total_Revenue>10000000")

  payment_method  Total_Revenue
0            COD    10764083.04
1           Card    10122294.82
2     NetBanking    10922704.99
4         Wallet    10159386.84

In [49]:
sales_data_products.head(2)

  product_id  product_name category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001  Grocery     2916.58     2252.96      True
1       P002  APP-Item-002  Apparel     3617.52     2100.87      True

In [50]:
sales_data_products.groupby("category")["unit_price"].mean().reset_index(name="unit_price").query("unit_price>10000")

      category    unit_price
0      Apparel  14095.019000
2  Electronics  15372.922000
3      Grocery  14052.264444
4         Home  12688.400000
5       Sports  14401.065000

In [51]:
sales_data_returns.head(2)

  return_id order_id return_date         reason  refund_amount
0     R0001   O01050  2025-05-20  Late Delivery        1917.72
1     R0002   O00477  2025-02-11        Damaged       14780.26

In [52]:
sales_data_returns.groupby("reason")["refund_amount"].sum().reset_index(name="refund_amount").query("refund_amount>100000")

             reason  refund_amount
0           Damaged      591433.16
1     Late Delivery      524675.43
2  Not as described      678083.68
3             Other      293763.68
4        Wrong Item      654568.82

In [53]:
sales_data_orders.head(2)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15

In [54]:
sales_data_orders.groupby("product_id")["quantity"].sum().reset_index(name="Total_Quantity").nlargest(5,"Total_Quantity")

   product_id  Total_Quantity
24       P025             144
28       P029             144
30       P031             138
26       P027             132
39       P040             132

In [55]:
sales_data_orders.groupby("product_id")["revenue"].sum().reset_index(name="Total_Revenue").nlargest(5,"Total_Revenue")

   product_id  Total_Revenue
28       P029     2935953.79
29       P030     2563463.42
31       P032     2273676.11
32       P033     2136775.68
19       P020     2045864.53

In [56]:
sales_data_customers.head(1)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27

In [57]:
sales_data_orders.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59

In [58]:
sales_data_orders.columns[sales_data_orders.columns.duplicated()]

Index([], dtype='str')

In [59]:
sales_data_customers.columns[sales_data_customers.columns.duplicated()]

Index([], dtype='str')

In [60]:
top_customers = (
    sales_data_orders.groupby("customer_id")["order_id"]
    .count()
    .reset_index(name="Total_Orders")
    .nlargest(5, "Total_Orders")
)

top_customers = top_customers.merge(
    sales_data_customers.loc[:, ["customer_id", "customer_name"]]
    .loc[:, lambda df: ~df.columns.duplicated()],
    on="customer_id",
    how="left"
)

top_customers[["customer_id", "customer_name", "Total_Orders"]]

  customer_id customer_name  Total_Orders
0       C0077   Customer 77            19
1       C0061   Customer 61            16
2       C0068   Customer 68            16
3       C0072   Customer 72            16
4       C0074   Customer 74            16

In [61]:
sales_data_orders.groupby("customer_id").size().reset_index(name="Total_Orders").nlargest(5, "Total_Orders")

   customer_id  Total_Orders
76       C0077            19
60       C0061            16
67       C0068            16
71       C0072            16
73       C0074            16

In [62]:
sales_data_orders.groupby("customer_id")["revenue"].sum().reset_index(name="Total_Revenue").nlargest(5,"Total_Revenue")

   customer_id  Total_Revenue
63       C0064      905871.92
84       C0085      794674.06
51       C0052      790722.03
71       C0072      766393.26
48       C0049      739040.54

In [63]:
sales_data_orders.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59

In [64]:
sales_data_orders.groupby("product_id")["quantity"].sum().reset_index(name="Total_Quantity").query("Total_Quantity>100")

   product_id  Total_Quantity
1        P002             106
2        P003             108
4        P005             124
8        P009             126
9        P010             122
10       P011             104
13       P014             105
16       P017             123
18       P019             113
19       P020             109
20       P021             129
24       P025             144
25       P026             112
26       P027             132
28       P029             144
29       P030             126
30       P031             138
31       P032             114
34       P035             107
35       P036             105
36       P037             123
37       P038             119
39       P040             132

In [65]:
sales_data_orders.groupby("customer_id")["order_id"].count().reset_index(name="Total_Orders").nlargest(10,"Total_Orders")

   customer_id  Total_Orders
76       C0077            19
60       C0061            16
67       C0068            16
71       C0072            16
73       C0074            16
83       C0084            16
48       C0049            15
52       C0053            15
63       C0064            15
88       C0089            15

In [66]:
sales_data_orders.groupby("customer_id")["revenue"].sum().reset_index(name="Total_Revenue").query("Total_Revenue>500000")

    customer_id  Total_Revenue
3         C0004      579063.90
9         C0010      571518.25
10        C0011      586090.00
12        C0013      584925.98
16        C0017      682781.05
17        C0018      735339.80
19        C0020      516128.46
27        C0028      634440.84
30        C0031      504330.68
34        C0035      610691.29
35        C0036      545878.17
38        C0039      690114.71
41        C0042      576647.48
43        C0044      646869.25
45        C0046      500991.44
48        C0049      739040.54
51        C0052      790722.03
52        C0053      667668.36
53        C0054      627468.23
57        C0058      609779.72
58        C0059      724631.91
60        C0061      590860.97
61        C0062      539031.32
63        C0064      905871.92
65        C0066      529843.08
67        C0068      674831.18
71        C0072      766393.26
73        C0074      523827.40
76        C0077      641513.92
82        C0083      622460.20
84        C0085      794674.06
88        C0089      629800.85
92        C0093      551644.91
95        C0096      714861.20
96        C0097      532522.88
103       C0104      528949.73
106       C0107      529516.50
119       C0120      518616.86

In [67]:
sales_data_orders.groupby("product_id")["customer_id"].nunique().reset_index(name="Total_Customers").query("Total_Customers>20")

   product_id  Total_Customers
1        P002               26
2        P003               26
3        P004               24
4        P005               32
5        P006               22
6        P007               29
7        P008               21
8        P009               29
9        P010               31
10       P011               27
11       P012               22
12       P013               23
13       P014               24
14       P015               25
15       P016               21
16       P017               34
18       P019               28
19       P020               26
20       P021               30
21       P022               23
22       P023               26
23       P024               26
24       P025               36
25       P026               28
26       P027               32
28       P029               35
29       P030               28
30       P031               29
31       P032               30
32       P033               28
33       P034               28
34       P035               23
35       P036               26
36       P037               34
37       P038               34
38       P039               24
39       P040               29

In [68]:
sales_data_orders.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59

In [69]:
sales_data_orders.groupby("channel")["discount_pct"].mean().reset_index(name="Maximum_Discount").query("Maximum_Discount>5.0")

   channel  Maximum_Discount
0   Online          7.976501
1  Partner          7.224939
2    Store          6.715426

In [70]:
sales_data_orders["order_date"] = pd.to_datetime(
    sales_data_orders["order_date"], errors="coerce"
)

In [71]:
sales_data_orders["order_date"].min()

Timestamp('2025-01-01 00:00:00')

In [72]:
sales_data_orders["order_date"].max()

Timestamp('2025-12-20 00:00:00')

In [73]:
sales_data_customers.head(1)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27

In [74]:
sales_data_customers["signup_date"]=pd.to_datetime(sales_data_customers["signup_date"], errors="coerce")

In [75]:
sales_data_customers["signup_date"].min()

Timestamp('2023-01-10 00:00:00')

In [76]:
sales_data_customers["signup_date"].max()

Timestamp('2025-06-19 00:00:00')

In [77]:
sales_data_returns.head(1)

  return_id order_id return_date         reason  refund_amount
0     R0001   O01050  2025-05-20  Late Delivery        1917.72

In [78]:
sales_data_returns["return_date"].min()

Timestamp('2025-01-13 00:00:00')

In [79]:
sales_data_returns["return_date"].min()

Timestamp('2025-01-13 00:00:00')

In [80]:
sales_data_orders.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59

In [81]:
sales_data_orders["order_date"].dt.year

0       2025
1       2025
2       2025
3       2025
4       2025
        ...
1203    2025
1204    2025
1205    2025
1206    2025
1207    2025
Name: order_date, Length: 1208, dtype: int32

In [82]:
sales_data_orders["order_date"].dt.month

0        2
1        2
2       11
3       10
4        2
        ..
1203     7
1204    10
1205     3
1206     2
1207     4
Name: order_date, Length: 1208, dtype: int32

In [83]:
sales_data_orders["order_date"].dt.month_name()

0       February
1       February
2       November
3        October
4       February
          ...
1203        July
1204     October
1205       March
1206    February
1207       April
Name: order_date, Length: 1208, dtype: str

In [84]:
sales_data_orders["order_date"].dt.day_of_week

0       4
1       3
2       3
3       2
4       3
       ..
1203    1
1204    5
1205    5
1206    3
1207    5
Name: order_date, Length: 1208, dtype: int32

In [85]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.month_name())['order_id'].count()

order_date
April         86
August       105
December      84
February     110
January      104
July         114
June         108
March        104
May           93
November     105
October      106
September     89
Name: order_id, dtype: int64

In [86]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.month_name())['revenue'].sum()

order_date
April        3736987.64
August       4781216.19
December     3046748.79
February     4920270.69
January      5102711.46
July         4634551.76
June         4403524.13
March        4678443.18
May          4077698.57
November     4390124.64
October      4894184.33
September    3410309.80
Name: revenue, dtype: float64

In [87]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.month_name())['order_id'].count()

order_date
April         86
August       105
December      84
February     110
January      104
July         114
June         108
March        104
May           93
November     105
October      106
September     89
Name: order_id, dtype: int64

In [88]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.day_name())

In [89]:
sales_data_orders.head(1)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59

In [90]:
sales_data_customers.head(1)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27

In [91]:
sales_data_orders["customer_id"] = (
    sales_data_orders["customer_id"].astype("string").str.strip()
)

sales_data_customers["customer_id"] = (
    sales_data_customers["customer_id"].astype("string").str.strip()
)

result = sales_data_orders.merge(
    sales_data_customers[["customer_id", "customer_name"]],
    on="customer_id",
    how="left"
)

result.head(2)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,customer_name
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Customer 106
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Customer 20

In [92]:
result.groupby(["customer_id","customer_name"])["order_id"].count().reset_index(name="Total_Orders").query("Total_Orders>5")

    customer_id   customer_name  Total_Orders
0         C0001      Customer 1            11
1         C0002      Customer 2             9
2         C0003      Customer 3             8
3         C0004    Customer 4              10
4         C0005      Customer 5             7
..          ...             ...           ...
114       C0115    Customer 115            15
116       C0117    Customer 117             8
117       C0118    Customer 118            12
118       C0119    Customer 119             7
119       C0120    Customer 120             7

[113 rows x 3 columns]

In [93]:
sales_data_orders['order_date']=pd.to_datetime(sales_data_orders['order_date'])
sales_data_orders['day_of_week']=sales_data_orders['order_date'].dt.day_name()

In [94]:
print(sales_data_orders['day_of_week'])

0          Friday
1        Thursday
2        Thursday
3       Wednesday
4        Thursday
          ...
1203      Tuesday
1204     Saturday
1205     Saturday
1206     Thursday
1207     Saturday
Name: day_of_week, Length: 1208, dtype: str

In [95]:
sales_data_orders.head(3)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday

In [96]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.month_name())['revenue'].sum()

order_date
April        3736987.64
August       4781216.19
December     3046748.79
February     4920270.69
January      5102711.46
July         4634551.76
June         4403524.13
March        4678443.18
May          4077698.57
November     4390124.64
October      4894184.33
September    3410309.80
Name: revenue, dtype: float64

In [97]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.month_name())['quantity'].count()

order_date
April         86
August       105
December      84
February     110
January      104
July         114
June         108
March        104
May           93
November     105
October      106
September     89
Name: quantity, dtype: int64

In [98]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.month_name())['revenue'].mean()

order_date
April        43453.344651
August       45535.392286
December     36270.818929
February     44729.733545
January      49064.533269
July         40653.962807
June         40773.371574
March        44985.030577
May          43846.221183
November     41810.710857
October      46171.550283
September    38318.087640
Name: revenue, dtype: float64

In [99]:
sales_data_orders.groupby(
    sales_data_orders['order_date'].dt.month_name()
).agg(
    average_revenue=('revenue', 'mean'),
    order_ids=('order_id', list)
)

            average_revenue                                          order_ids
order_date
April          43453.344651  [O00026, O00033, O00055, O00074, O00076, O0009...
August         45535.392286  [O00028, O00037, O00047, O00048, O00058, O0006...
December       36270.818929  [O00007, O00031, O00041, O00045, O00053, O0006...
February       44729.733545  [O00001, O00002, O00005, O00020, O00064, O0007...
January        49064.533269  [O00023, O00043, O00052, O00067, O00100, O0012...
July           40653.962807  [O00034, O00035, O00044, O00046, O00051, O0005...
June           40773.371574  [O00014, O00018, O00032, O00039, O00050, O0006...
March          44985.030577  [O00006, O00011, O00012, O00016, O00025, O0002...
May            43846.221183  [O00008, O00027, O00038, O00054, O00073, O0007...
November       41810.710857  [O00003, O00009, O00010, O00042, O00056, O0008...
October        46171.550283  [O00004, O00013, O00015, O00017, O00036, O0004...
September      38318.087640  [O00019, O00021, O00022, O00024, O00030, O0004...

In [100]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.month_name())['revenue'].sum().idxmax()

'January'

In [101]:
monthly_revenue=sales_data_orders.groupby(sales_data_orders['order_date'].dt.month_name())['revenue'].sum()
print("Month: ", monthly_revenue.idxmax())
print("Revenue: ", monthly_revenue.max())

Month:  January
Revenue:  5102711.46

In [102]:
sales_data_orders[
    (sales_data_orders['order_date'].dt.month == 1)&
    (sales_data_orders['order_date'].dt.year == 2025)
]['order_id'].count()

np.int64(104)

In [103]:
sales_data_orders[
    (sales_data_orders['order_date'].dt.month == 1)&
    (sales_data_orders['order_date'].dt.year == 2025)
]['order_id'].nunique()

104

In [104]:
sales_data_orders[
    (sales_data_orders['order_date'].dt.month == 1)&
    (sales_data_orders['order_date'].dt.year == 2025)
]['order_id']

22      O00023
42      O00043
51      O00052
66      O00067
99      O00100
         ...
1074    O01075
1106    O01107
1154    O01155
1165    O01166
1171    O01172
Name: order_id, Length: 104, dtype: str

In [105]:
sales_data_orders[
    (sales_data_orders['order_date'].dt.month == 1)&
    (sales_data_orders['order_date'].dt.year == 2025)
]['order_id'].tolist()

['O00023',
 'O00043',
 'O00052',
 'O00067',
 'O00100',
 'O00124',
 'O00125',
 'O00132',
 'O00138',
 'O00143',
 'O00151',
 'O00155',
 'O00170',
 'O00201',
 'O00213',
 'O00214',
 'O00220',
 'O00239',
 'O00242',
 'O00252',
 'O00257',
 'O00281',
 'O00301',
 'O00311',
 'O00331',
 'O00354',
 'O00357',
 'O00361',
 'O00382',
 'O00387',
 'O00400',
 'O00418',
 'O00428',
 'O00430',
 'O00432',
 'O00434',
 'O00443',
 'O00445',
 'O00458',
 'O00477',
 'O00478',
 'O00491',
 'O00494',
 'O00511',
 'O00523',
 'O00528',
 'O00547',
 'O00565',
 'O00570',
 'O00571',
 'O00578',
 'O00582',
 'O00584',
 'O00597',
 'O00599',
 'O00602',
 'O00603',
 'O00607',
 'O00634',
 'O00636',
 'O00645',
 'O00646',
 'O00674',
 'O00682',
 'O00700',
 'O00702',
 'O00709',
 'O00722',
 'O00728',
 'O00767',
 'O00780',
 'O00791',
 'O00800',
 'O00815',
 'O00820',
 'O00831',
 'O00854',
 'O00866',
 'O00876',
 'O00883',
 'O00887',
 'O00891',
 'O00900',
 'O00903',
 'O00905',
 'O00907',
 'O00921',
 'O00929',
 'O00962',
 'O01004',
 'O01008',
 'O01011',
 'O01024',
 'O01033',
 'O01041',
 'O01055',
 'O01060',
 'O01063',
 'O01072',
 'O01075',
 'O01107',
 'O01155',
 'O01166',
 'O01172']

In [107]:
sales_data_orders[sales_data_orders['order_date'].between('2025-01-01','2025-02-28')]

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday
19,O00020,2025-02-15,C0105,P036,1,8205.28,5.0,Store,COD,7795.02,Saturday
22,O00023,2025-01-27,C0097,P032,6,21914.95,5.0,Online,COD,124915.22,Monday
...,...,...,...,...,...,...,...,...,...,...,...
1189,O01190,2025-02-17,C0103,P015,5,9349.00,15.0,Partner,Wallet,39733.25,Monday
1190,O01191,2025-02-04,C0013,P038,3,18337.90,0.0,Partner,Wallet,55013.70,Tuesday
1191,O01192,2025-02-09,C0061,P028,2,9633.24,0.0,Partner,COD,19266.48,Sunday
1198,O01199,2025-02-02,C0109,P028,4,9633.24,0.0,Partner,Card,38532.96,Sunday
1206,O00818,2025-02-06,C0047,P015,5,9349.00,15.0,Online,Card,39733.25,Thursday

In [108]:
sales_data_orders[sales_data_orders['order_date'].dt.day_of_week>=5]

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
5,O00006,2025-03-30,C9999,P006,2,14793.25,0.0,Partner,UPI,29586.50,Sunday
7,O00008,2025-05-25,C0038,P003,2,10634.76,0.0,Partner,NetBanking,21269.52,Sunday
12,O00013,2025-10-04,C0090,P026,3,18931.19,10.0,Store,NetBanking,51114.21,Saturday
13,O00014,2025-06-15,C0011,P039,1,16544.81,5.0,Partner,COD,15717.57,Sunday
19,O00020,2025-02-15,C0105,P036,1,8205.28,5.0,Store,COD,7795.02,Saturday
...,...,...,...,...,...,...,...,...,...,...,...
1197,O01198,2025-05-04,C0026,P024,4,14676.96,0.0,Online,COD,58707.84,Sunday
1198,O01199,2025-02-02,C0109,P028,4,9633.24,0.0,Partner,Card,38532.96,Sunday
1204,O01084,2025-10-25,C0084,P031,6,7443.48,20.0,Partner,Card,35728.70,Saturday
1205,O00284,2025-03-15,C0077,P021,2,1794.79,0.0,Partner,Wallet,3589.58,Saturday
1207,O00315,2025-04-26,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95,Saturday

In [109]:
sales_data_orders[sales_data_orders['order_date'].dt.day_of_week<5]

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday
...,...,...,...,...,...,...,...,...,...,...,...
1200,O00637,2025-12-05,C0077,P004,6,12708.08,10.0,Store,NetBanking,68623.63,Friday
1201,O00684,2025-09-24,C0084,P021,1,1794.79,15.0,Partner,COD,1525.57,Wednesday
1202,O01034,2025-10-02,C0028,P034,4,12765.42,15.0,Online,Wallet,43402.43,Thursday
1203,O00191,2025-07-08,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32,Tuesday
1206,O00818,2025-02-06,C0047,P015,5,9349.00,15.0,Online,Card,39733.25,Thursday

In [110]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.day_name())['order_id'].count()

order_date
Friday       177
Monday       164
Saturday     170
Sunday       150
Thursday     202
Tuesday      156
Wednesday    189
Name: order_id, dtype: int64

In [111]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.day_name())['revenue'].sum()

order_date
Friday       7299928.95
Monday       7453084.60
Saturday     6841377.65
Sunday       6284535.15
Thursday     9108814.03
Tuesday      6772816.76
Wednesday    8316214.04
Name: revenue, dtype: float64

In [112]:
sales_data_orders.groupby(sales_data_orders['order_date'].dt.day_name())['revenue'].mean()

order_date
Friday       41242.536441
Monday       45445.637805
Saturday     40243.397941
Sunday       41896.901000
Thursday     45093.138762
Tuesday      43415.492051
Wednesday    44001.132487
Name: revenue, dtype: float64

In [115]:
sales_data_orders.head()

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,day_of_week
0,O00001,2025-02-07,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Friday
1,O00002,2025-02-13,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Thursday
2,O00003,2025-11-13,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Thursday
3,O00004,2025-10-29,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Wednesday
4,O00005,2025-02-20,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Thursday

In [114]:
sales_data_customers.head(2)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27
1,C0002,Customer 2,cust2@example.com,Wholesale,East,Patna,2023-05-04

In [117]:
sales_data_orders.merge(sales_data_customers[['customer_id','customer_name','region']],
                        on='customer_id',
                        how='left')[['order_id','customer_name','region']]

     order_id   customer_name region
0      O00001    Customer 106   East
1      O00002     Customer 20  North
2      O00003     Customer 72   West
3      O00004     Customer 49  North
4      O00005     Customer 73   East
...       ...             ...    ...
1203   O00191    Customer 4    South
1204   O01084     Customer 84  North
1205   O00284     Customer 77   West
1206   O00818     Customer 47   West
1207   O00315     Customer 52   East

[1208 rows x 3 columns]

In [120]:
sales_data_orders.merge(sales_data_customers[['customer_id','segment']],
                        on='customer_id',
                        how='left').groupby('segment')['revenue'].sum()

segment
Corporate    17963776.86
Retail       16137801.92
Wholesale    17654523.60
retail         291082.30
Name: revenue, dtype: float64

In [118]:
sales_data_orders.merge(sales_data_customers[['customer_id','customer_name','region','segment']],
                        on='customer_id',
                        how='left')[['order_id','customer_name','region','segment']]

     order_id   customer_name region    segment
0      O00001    Customer 106   East  Corporate
1      O00002     Customer 20  North  Corporate
2      O00003     Customer 72   West     Retail
3      O00004     Customer 49  North  Corporate
4      O00005     Customer 73   East  Wholesale
...       ...             ...    ...        ...
1203   O00191    Customer 4    South  Corporate
1204   O01084     Customer 84  North  Wholesale
1205   O00284     Customer 77   West  Wholesale
1206   O00818     Customer 47   West     Retail
1207   O00315     Customer 52   East  Corporate

[1208 rows x 4 columns]

In [113]:
sales_data_orders.merge(sales_data_customers[['customer_id','customer_name']],
                        on='customer_id',
                        how='left')[['order_id','customer_name']]

     order_id   customer_name
0      O00001    Customer 106
1      O00002     Customer 20
2      O00003     Customer 72
3      O00004     Customer 49
4      O00005     Customer 73
...       ...             ...
1203   O00191    Customer 4
1204   O01084     Customer 84
1205   O00284     Customer 77
1206   O00818     Customer 47
1207   O00315     Customer 52

[1208 rows x 2 columns]

In [116]:
sales_data_orders.merge(sales_data_customers[['customer_id','customer_name','region']],
                        on='customer_id',
                        how='left')[['order_id','customer_name','region']]

     order_id   customer_name region
0      O00001    Customer 106   East
1      O00002     Customer 20  North
2      O00003     Customer 72   West
3      O00004     Customer 49  North
4      O00005     Customer 73   East
...       ...             ...    ...
1203   O00191    Customer 4    South
1204   O01084     Customer 84  North
1205   O00284     Customer 77   West
1206   O00818     Customer 47   West
1207   O00315     Customer 52   East

[1208 rows x 3 columns]