In [1]:
import pandas as pd

In [2]:
categories=pd.read_csv(r"D:\Python Test\categories.csv")
customers=pd.read_csv(r"D:\Python Test\customers.csv")
employees=pd.read_csv(r"D:\Python Test\employees.csv")
order_items=pd.read_csv(r"D:\Python Test\order_items.csv")
orders=pd.read_csv(r"D:\Python Test\orders.csv")
payments=pd.read_csv(r"D:\Python Test\payments.csv")
products=pd.read_csv(r"D:\Python Test\products.csv")
promotions=pd.read_csv(r"D:\Python Test\promotions.csv")
returns=pd.read_csv(r"D:\Python Test\returns.csv")
shipments=pd.read_csv(r"D:\Python Test\shipments.csv")
stores=pd.read_csv(r"D:\Python Test\stores.csv")
suppliers=pd.read_csv(r"D:\Python Test\suppliers.csv")

In [8]:
stores.head(1)

   store_id  city
0         1  Pune

In [9]:
employees.head(1)

   employee_id  store_id  salary
0            1        46   33345

In [5]:
products_suppliers=products.merge(suppliers, 
                                  on="supplier_id",
                                  how="left")
print(products_suppliers)

      product_id  category_id  supplier_id  price country
0              1            9          135   3987   China
1              2           18          194   4412   China
2              3           23          118   3548     USA
3              4           19          139   1971   China
4              5           10          115   4495   China
...          ...          ...          ...    ...     ...
9995        9996           15          197   2558     USA
9996        9997           20          156   2516     USA
9997        9998            9           44   1668   China
9998        9999           18           93   3895     USA
9999       10000            1           18   4711     USA

[10000 rows x 5 columns]

In [4]:
suppliers

     supplier_id country
0              1   India
1              2   India
2              3   India
3              4     USA
4              5   China
..           ...     ...
195          196   India
196          197     USA
197          198   China
198          199     USA
199          200   India

[200 rows x 2 columns]

In [3]:
product_category=products.merge(
    categories,
    on="category_id",
    how="left"
)
print(product_category)

      product_id  category_id  supplier_id  price category_name
0              1            9          135   3987         Cat_9
1              2           18          194   4412        Cat_18
2              3           23          118   3548        Cat_23
3              4           19          139   1971        Cat_19
4              5           10          115   4495        Cat_10
...          ...          ...          ...    ...           ...
9995        9996           15          197   2558        Cat_15
9996        9997           20          156   2516        Cat_20
9997        9998            9           44   1668         Cat_9
9998        9999           18           93   3895        Cat_18
9999       10000            1           18   4711         Cat_1

[10000 rows x 5 columns]

In [84]:
order_customer=orders.merge(customers, on="customer_id", how="left")
print(order_customer)

        order_id  customer_id  store_id  order_date  promotion_id       city  \
0              1        45308        33  2021-08-26            24       Pune
1              2        10070        81  2022-03-19             3  Bangalore
2              3        43308        17  2021-01-21            25      Delhi
3              4        47997        85  2021-01-16            48       Pune
4              5        36546        81  2022-09-14            33      Delhi
...          ...          ...       ...         ...           ...        ...
299995    299996         5151        68  2021-07-21            50     Mumbai
299996    299997         1806        95  2021-03-25            50       Pune
299997    299998        10040        84  2022-09-17            18  Bangalore
299998    299999        48944        72  2022-03-24            26       Pune
299999    300000        29100         8  2023-01-13             2  Bangalore

       signup_date
0       2019-06-24
1       2019-10-18
2       2022-05-26
3       2022-11-03
4       2023-06-06
...            ...
299995  2023-08-25
299996  2022-09-15
299997  2023-11-25
299998  2020-10-29
299999  2019-01-01

[300000 rows x 7 columns]

In [81]:
merged_df=employees.merge(orders, on="store_id")
employee_orders=merged_df.groupby("employee_id")["order_id"].count().reset_index(name="order_count")
result=employee_orders[employee_orders["order_count"]>500]
print(result)

     employee_id  order_count
0              1         3005
1              2         2999
2              3         3062
3              4         3000
4              5         3084
..           ...          ...
995          996         3127
996          997         3028
997          998         3106
998          999         2911
999         1000         3066

[1000 rows x 2 columns]

In [78]:
employees.head(1)

   employee_id  store_id  salary
0            1        46   33345

In [79]:
stores.head(1)

   store_id  city
0         1  Pune

In [80]:
orders.head(1)

   order_id  customer_id  store_id  order_date  promotion_id
0         1        45308        33  2021-08-26            24

In [77]:
city_customers=(customers.groupby("city")
                .size().reset_index(name="customer_count"))
result=city_customers[city_customers["customer_count"]>100]
print(result)

        city  customer_count
0  Bangalore           12434
1      Delhi           12389
2     Mumbai           12656
3       Pune           12521

In [76]:
customers.head(1)

   customer_id    city signup_date
0            1  Mumbai  2021-02-16

In [75]:
order_items["sales"]=order_items["qty"]*order_items["price"]
product_sales=(order_items.groupby("product_id")["sales"]
               .sum()
               .reset_index(name="total_sales"))
result=product_sales[product_sales["total_sales"]>100000]
print(result)

      product_id  total_sales
0              1       440464
1              2       420731
2              3       413083
3              4       346770
4              5       364497
...          ...          ...
9995        9996       366573
9996        9997       407294
9997        9998       423663
9998        9999       355598
9999       10000       373514

[10000 rows x 2 columns]

In [70]:
order_items.head(1)

   order_item_id  order_id  product_id  qty  price  Product_sales
0              1    145042         472    3    176            528

In [71]:
products.head(1)

   product_id  category_id  supplier_id  price
0           1            9          135   3987

In [69]:
store_orders=(orders.groupby("store_id")
            .size()
              .reset_index(name="order_count"))
result=store_orders[store_orders["order_count"]>1000]
print(result)

    store_id  order_count
0          1         2961
1          2         2997
2          3         3027
3          4         3106
4          5         2973
..       ...          ...
95        96         2971
96        97         3008
97        98         2986
98        99         3014
99       100         3035

[100 rows x 2 columns]

In [68]:
stores.head(1)

   store_id  city
0         1  Pune

In [64]:
orders.head(1)

   order_id  customer_id  store_id  order_date  promotion_id
0         1        45308        33  2021-08-26            24

In [ ]:
customers.head(1)

   customer_id    city signup_date
0            1  Mumbai  2021-02-16

In [67]:
cat_products=(orders.groupby("customer_id")
            .size()
              .reset_index(name="order_count"))
result=cat_products[cat_products["order_count"]>5]
print(result)

       customer_id  order_count
1                2            6
2                3            6
7                8           10
10              11            9
11              12            7
...            ...          ...
49876        49991            9
49881        49996            6
49882        49997            7
49883        49998            6
49885        50000            9

[27657 rows x 2 columns]

In [55]:
products.head(1)

   product_id  category_id  supplier_id  price
0           1            9          135   3987

In [56]:
categories.head(1)

   category_id category_name
0            1         Cat_1

In [51]:
merged_df=employees.merge(orders, on="store_id")
employee_orders=(merged_df.groupby("employee_id")["order_id"]
                 .count().reset_index(name="order_count"))
result=employee_orders[employee_orders["order_count"]>500]
print(result)

     employee_id  order_count
0              1         3005
1              2         2999
2              3         3062
3              4         3000
4              5         3084
..           ...          ...
995          996         3127
996          997         3028
997          998         3106
998          999         2911
999         1000         3066

[1000 rows x 2 columns]

In [52]:
employee_orders

     employee_id  order_count
0              1         3005
1              2         2999
2              3         3062
3              4         3000
4              5         3084
..           ...          ...
995          996         3127
996          997         3028
997          998         3106
998          999         2911
999         1000         3066

[1000 rows x 2 columns]

In [46]:
print(orders.columns)
print(employees.columns)

Index(['order_id', 'customer_id', 'store_id', 'order_date', 'promotion_id'], dtype='str')
Index(['employee_id', 'store_id', 'salary'], dtype='str')

In [40]:
stores

    store_id       city
0          1       Pune
1          2       Pune
2          3      Delhi
3          4     Mumbai
4          5     Mumbai
..       ...        ...
95        96       Pune
96        97     Mumbai
97        98     Mumbai
98        99  Bangalore
99       100      Delhi

[100 rows x 2 columns]

In [41]:
orders

        order_id  customer_id  store_id  order_date  promotion_id
0              1        45308        33  2021-08-26            24
1              2        10070        81  2022-03-19             3
2              3        43308        17  2021-01-21            25
3              4        47997        85  2021-01-16            48
4              5        36546        81  2022-09-14            33
...          ...          ...       ...         ...           ...
299995    299996         5151        68  2021-07-21            50
299996    299997         1806        95  2021-03-25            50
299997    299998        10040        84  2022-09-17            18
299998    299999        48944        72  2022-03-24            26
299999    300000        29100         8  2023-01-13             2

[300000 rows x 5 columns]

In [39]:
employees

     employee_id  store_id  salary
0              1        46   33345
1              2        29   23325
2              3        54   22348
3              4        22   77360
4              5        75   69422
..           ...       ...     ...
995          996         9   24914
996          997        82   79117
997          998         4   33964
998          999        21   38532
999         1000        49   47050

[1000 rows x 3 columns]

In [38]:
city_customers=(customers.groupby("city")
                .size()
                .reset_index(name="customer_count"))
result=city_customers[city_customers["customer_count"]>10]
print(result)

        city  customer_count
0  Bangalore           12434
1      Delhi           12389
2     Mumbai           12656
3       Pune           12521

In [37]:
customers

       customer_id       city signup_date
0                1     Mumbai  2021-02-16
1                2  Bangalore  2019-06-22
2                3       Pune  2022-01-25
3                4     Mumbai  2023-06-14
4                5      Delhi  2023-06-24
...            ...        ...         ...
49995        49996  Bangalore  2020-11-24
49996        49997     Mumbai  2021-11-13
49997        49998  Bangalore  2023-02-18
49998        49999  Bangalore  2020-07-05
49999        50000  Bangalore  2019-06-05

[50000 rows x 3 columns]

In [34]:
products

      product_id  category_id  supplier_id  price
0              1            9          135   3987
1              2           18          194   4412
2              3           23          118   3548
3              4           19          139   1971
4              5           10          115   4495
...          ...          ...          ...    ...
9995        9996           15          197   2558
9996        9997           20          156   2516
9997        9998            9           44   1668
9998        9999           18           93   3895
9999       10000            1           18   4711

[10000 rows x 4 columns]

In [33]:
store_orders=(orders.groupby("store_id")
              .size()
              .reset_index(name="order_count"))
result=store_orders[store_orders["order_count"]>1000]
print(result)

    store_id  order_count
0          1         2961
1          2         2997
2          3         3027
3          4         3106
4          5         2973
..       ...          ...
95        96         2971
96        97         3008
97        98         2986
98        99         3014
99       100         3035

[100 rows x 2 columns]

In [32]:
orders

        order_id  customer_id  store_id  order_date  promotion_id
0              1        45308        33  2021-08-26            24
1              2        10070        81  2022-03-19             3
2              3        43308        17  2021-01-21            25
3              4        47997        85  2021-01-16            48
4              5        36546        81  2022-09-14            33
...          ...          ...       ...         ...           ...
299995    299996         5151        68  2021-07-21            50
299996    299997         1806        95  2021-03-25            50
299997    299998        10040        84  2022-09-17            18
299998    299999        48944        72  2022-03-24            26
299999    300000        29100         8  2023-01-13             2

[300000 rows x 5 columns]

In [31]:
stores

    store_id       city
0          1       Pune
1          2       Pune
2          3      Delhi
3          4     Mumbai
4          5     Mumbai
..       ...        ...
95        96       Pune
96        97     Mumbai
97        98     Mumbai
98        99  Bangalore
99       100      Delhi

[100 rows x 2 columns]

In [30]:
customer_orders=(
    orders.groupby("customer_id")
    .size()
    .reset_index(name="order_count"))
result=customer_orders[customer_orders["order_count"]>5]
print(result)

       customer_id  order_count
1                2            6
2                3            6
7                8           10
10              11            9
11              12            7
...            ...          ...
49876        49991            9
49881        49996            6
49882        49997            7
49883        49998            6
49885        50000            9

[27657 rows x 2 columns]

In [24]:
orders

        order_id  customer_id  store_id  order_date  promotion_id
0              1        45308        33  2021-08-26            24
1              2        10070        81  2022-03-19             3
2              3        43308        17  2021-01-21            25
3              4        47997        85  2021-01-16            48
4              5        36546        81  2022-09-14            33
...          ...          ...       ...         ...           ...
299995    299996         5151        68  2021-07-21            50
299996    299997         1806        95  2021-03-25            50
299997    299998        10040        84  2022-09-17            18
299998    299999        48944        72  2022-03-24            26
299999    300000        29100         8  2023-01-13             2

[300000 rows x 5 columns]

In [23]:
customers

       customer_id       city signup_date
0                1     Mumbai  2021-02-16
1                2  Bangalore  2019-06-22
2                3       Pune  2022-01-25
3                4     Mumbai  2023-06-14
4                5      Delhi  2023-06-24
...            ...        ...         ...
49995        49996  Bangalore  2020-11-24
49996        49997     Mumbai  2021-11-13
49997        49998  Bangalore  2023-02-18
49998        49999  Bangalore  2020-07-05
49999        50000  Bangalore  2019-06-05

[50000 rows x 3 columns]

In [22]:
category_counts=(products.groupby("category_id").
                 size().
                 reset_index(name="product_count"))
result=category_counts[category_counts["product_count"]>10]
print(result)

    category_id  product_count
0             1            312
1             2            298
2             3            351
3             4            327
4             5            358
5             6            340
6             7            316
7             8            351
8             9            350
9            10            340
10           11            338
11           12            350
12           13            347
13           14            312
14           15            338
15           16            345
16           17            344
17           18            323
18           19            328
19           20            329
20           21            346
21           22            331
22           23            305
23           24            313
24           25            328
25           26            351
26           27            331
27           28            350
28           29            320
29           30            328

In [21]:
products

      product_id  category_id  supplier_id  price
0              1            9          135   3987
1              2           18          194   4412
2              3           23          118   3548
3              4           19          139   1971
4              5           10          115   4495
...          ...          ...          ...    ...
9995        9996           15          197   2558
9996        9997           20          156   2516
9997        9998            9           44   1668
9998        9999           18           93   3895
9999       10000            1           18   4711

[10000 rows x 4 columns]

In [20]:
categories

    category_id category_name
0             1         Cat_1
1             2         Cat_2
2             3         Cat_3
3             4         Cat_4
4             5         Cat_5
5             6         Cat_6
6             7         Cat_7
7             8         Cat_8
8             9         Cat_9
9            10        Cat_10
10           11        Cat_11
11           12        Cat_12
12           13        Cat_13
13           14        Cat_14
14           15        Cat_15
15           16        Cat_16
16           17        Cat_17
17           18        Cat_18
18           19        Cat_19
19           20        Cat_20
20           21        Cat_21
21           22        Cat_22
22           23        Cat_23
23           24        Cat_24
24           25        Cat_25
25           26        Cat_26
26           27        Cat_27
27           28        Cat_28
28           29        Cat_29
29           30        Cat_30

In [16]:
categories

    category_id category_name
0             1         Cat_1
1             2         Cat_2
2             3         Cat_3
3             4         Cat_4
4             5         Cat_5
5             6         Cat_6
6             7         Cat_7
7             8         Cat_8
8             9         Cat_9
9            10        Cat_10
10           11        Cat_11
11           12        Cat_12
12           13        Cat_13
13           14        Cat_14
14           15        Cat_15
15           16        Cat_16
16           17        Cat_17
17           18        Cat_18
18           19        Cat_19
19           20        Cat_20
20           21        Cat_21
21           22        Cat_22
22           23        Cat_23
23           24        Cat_24
24           25        Cat_25
25           26        Cat_26
26           27        Cat_27
27           28        Cat_28
28           29        Cat_29
29           30        Cat_30

In [10]:
products

      product_id  category_id  supplier_id  price
0              1            9          135   3987
1              2           18          194   4412
2              3           23          118   3548
3              4           19          139   1971
4              5           10          115   4495
...          ...          ...          ...    ...
9995        9996           15          197   2558
9996        9997           20          156   2516
9997        9998            9           44   1668
9998        9999           18           93   3895
9999       10000            1           18   4711

[10000 rows x 4 columns]

In [19]:
order_items["Category_Sales"]=order_items["qty"]*order_items["price"]
#category_sales=order_items.groupby("category_id")["Category_Sales"].sum().reset_index()
merged_df=order_items.merge(
    products[["product_id","category_id"]],
    on="product_id")
category_sales=merged_df.groupby("category_id")["Category_Sales"].sum().reset_index()
print(category_sales)

    category_id  Category_Sales
0             1       118898915
1             2       112033211
2             3       135379339
3             4       126683191
4             5       136704132
5             6       129309749
6             7       120955964
7             8       132816590
8             9       132465085
9            10       130541445
10           11       129692788
11           12       133897588
12           13       132409449
13           14       119279003
14           15       128354546
15           16       129764814
16           17       132292751
17           18       122830679
18           19       125439819
19           20       126434094
20           21       135329061
21           22       126567395
22           23       117133042
23           24       121605160
24           25       127557740
25           26       134697069
26           27       125610068
27           28       133603891
28           29       122143415
29           30       127316143

In [18]:
products

      product_id  category_id  supplier_id  price
0              1            9          135   3987
1              2           18          194   4412
2              3           23          118   3548
3              4           19          139   1971
4              5           10          115   4495
...          ...          ...          ...    ...
9995        9996           15          197   2558
9996        9997           20          156   2516
9997        9998            9           44   1668
9998        9999           18           93   3895
9999       10000            1           18   4711

[10000 rows x 4 columns]

In [36]:
order_items["Product_sales"]=order_items["qty"]*order_items["price"]
product_sales=order_items.groupby("product_id")["Product_sales"].sum().reset_index()
product_sales=product_sales.merge(products, on="product_id")
products_sales=product_sales[product_sales["Product_sales"]>100000]
print(products_sales)

      product_id  Product_sales  category_id  supplier_id  price
0              1         440464            9          135   3987
1              2         420731           18          194   4412
2              3         413083           23          118   3548
3              4         346770           19          139   1971
4              5         364497           10          115   4495
...          ...            ...          ...          ...    ...
9995        9996         366573           15          197   2558
9996        9997         407294           20          156   2516
9997        9998         423663            9           44   1668
9998        9999         355598           18           93   3895
9999       10000         373514            1           18   4711

[10000 rows x 5 columns]

In [15]:
order_items["Product_Sales"]=order_items["qty"]*order_items["price"]
product_sales=order_items.groupby("product_id")["Product_Sales"].sum().reset_index()
product_sales=product_sales.merge(products,on="product_id")
print(product_sales)

      product_id  Product_Sales  category_id  supplier_id  price
0              1         440464            9          135   3987
1              2         420731           18          194   4412
2              3         413083           23          118   3548
3              4         346770           19          139   1971
4              5         364497           10          115   4495
...          ...            ...          ...          ...    ...
9995        9996         366573           15          197   2558
9996        9997         407294           20          156   2516
9997        9998         423663            9           44   1668
9998        9999         355598           18           93   3895
9999       10000         373514            1           18   4711

[10000 rows x 5 columns]

In [8]:
order_items["sales"]=order_items["qty"]*order_items["price"]
mereged_df=order_items.merge(
    orders[["order_id","store_id"]],
    on="order_id")
store_sales=mereged_df.groupby("store_id")["sales"].sum().reset_index()
store_sales=store_sales.merge(stores,on="store_id")

In [9]:
store_sales

    store_id     sales       city
0          1  37430666       Pune
1          2  39398223       Pune
2          3  38560059      Delhi
3          4  39929457     Mumbai
4          5  37150218     Mumbai
..       ...       ...        ...
95        96  37464060       Pune
96        97  38950128     Mumbai
97        98  37854618     Mumbai
98        99  38963804  Bangalore
99       100  38253683      Delhi

[100 rows x 3 columns]

In [5]:
order_items

        order_item_id  order_id  product_id  qty  price
0                   1    145042         472    3    176
1                   2    110932        1666    2   1034
2                   3    269799        8616    4   2290
3                   4    298741        9909    3   1555
4                   5    105218        1179    3    936
...               ...       ...         ...  ...    ...
599995         599996    199013        1358    3   4638
599996         599997     61973        3240    2   2875
599997         599998     56980        5447    3    565
599998         599999    119571        9216    3   3867
599999         600000    298854        4441    3   3074

[600000 rows x 5 columns]

In [4]:
stores

    store_id       city
0          1       Pune
1          2       Pune
2          3      Delhi
3          4     Mumbai
4          5     Mumbai
..       ...        ...
95        96       Pune
96        97     Mumbai
97        98     Mumbai
98        99  Bangalore
99       100      Delhi

[100 rows x 2 columns]

In [3]:
orders

        order_id  customer_id  store_id  order_date  promotion_id
0              1        45308        33  2021-08-26            24
1              2        10070        81  2022-03-19             3
2              3        43308        17  2021-01-21            25
3              4        47997        85  2021-01-16            48
4              5        36546        81  2022-09-14            33
...          ...          ...       ...         ...           ...
299995    299996         5151        68  2021-07-21            50
299996    299997         1806        95  2021-03-25            50
299997    299998        10040        84  2022-09-17            18
299998    299999        48944        72  2022-03-24            26
299999    300000        29100         8  2023-01-13             2

[300000 rows x 5 columns]

In [20]:
order_items

        order_item_id  order_id  product_id  qty  price
0                   1    145042         472    3    176
1                   2    110932        1666    2   1034
2                   3    269799        8616    4   2290
3                   4    298741        9909    3   1555
4                   5    105218        1179    3    936
...               ...       ...         ...  ...    ...
599995         599996    199013        1358    3   4638
599996         599997     61973        3240    2   2875
599997         599998     56980        5447    3    565
599998         599999    119571        9216    3   3867
599999         600000    298854        4441    3   3074

[600000 rows x 5 columns]

In [19]:
categories

    category_id category_name
0             1         Cat_1
1             2         Cat_2
2             3         Cat_3
3             4         Cat_4
4             5         Cat_5
5             6         Cat_6
6             7         Cat_7
7             8         Cat_8
8             9         Cat_9
9            10        Cat_10
10           11        Cat_11
11           12        Cat_12
12           13        Cat_13
13           14        Cat_14
14           15        Cat_15
15           16        Cat_16
16           17        Cat_17
17           18        Cat_18
18           19        Cat_19
19           20        Cat_20
20           21        Cat_21
21           22        Cat_22
22           23        Cat_23
23           24        Cat_24
24           25        Cat_25
25           26        Cat_26
26           27        Cat_27
27           28        Cat_28
28           29        Cat_29
29           30        Cat_30

In [16]:
order_items

        order_item_id  order_id  product_id  qty  price
0                   1    145042         472    3    176
1                   2    110932        1666    2   1034
2                   3    269799        8616    4   2290
3                   4    298741        9909    3   1555
4                   5    105218        1179    3    936
...               ...       ...         ...  ...    ...
599995         599996    199013        1358    3   4638
599996         599997     61973        3240    2   2875
599997         599998     56980        5447    3    565
599998         599999    119571        9216    3   3867
599999         600000    298854        4441    3   3074

[600000 rows x 5 columns]

In [15]:
payments

        payment_id  order_id  amount
0                1         1    1462
1                2         2    2272
2                3         3    1342
3                4         4    1906
4                5         5    7185
...            ...       ...     ...
299995      299996    299996   16433
299996      299997    299997   12560
299997      299998    299998    8735
299998      299999    299999   12792
299999      300000    300000   15349

[300000 rows x 3 columns]

In [14]:
stores

    store_id       city
0          1       Pune
1          2       Pune
2          3      Delhi
3          4     Mumbai
4          5     Mumbai
..       ...        ...
95        96       Pune
96        97     Mumbai
97        98     Mumbai
98        99  Bangalore
99       100      Delhi

[100 rows x 2 columns]

In [10]:
employees

     employee_id  store_id  salary
0              1        46   33345
1              2        29   23325
2              3        54   22348
3              4        22   77360
4              5        75   69422
..           ...       ...     ...
995          996         9   24914
996          997        82   79117
997          998         4   33964
998          999        21   38532
999         1000        49   47050

[1000 rows x 3 columns]

In [13]:
employees_per_store=employees.groupby('store_id').size().reset_index(name='employee_count')
print(employees_per_store)

    store_id  employee_count
0          1              10
1          2              11
2          3              10
3          4              14
4          5               8
..       ...             ...
95        96               4
96        97              10
97        98               5
98        99               7
99       100              10

[100 rows x 2 columns]

In [8]:
orders_per_store=orders.groupby('store_id').size().reset_index(name='order_count')
print(orders_per_store)

    store_id  order_count
0          1         2961
1          2         2997
2          3         3027
3          4         3106
4          5         2973
..       ...          ...
95        96         2971
96        97         3008
97        98         2986
98        99         3014
99       100         3035

[100 rows x 2 columns]

In [9]:
orders_per_customer=orders.groupby('customer_id').size().reset_index(name='customer_count')
print(orders_per_customer)

       customer_id  customer_count
0                1               5
1                2               6
2                3               6
3                4               2
4                5               4
...            ...             ...
49881        49996               6
49882        49997               7
49883        49998               6
49884        49999               2
49885        50000               9

[49886 rows x 2 columns]

In [7]:
orders

        order_id  customer_id  store_id  order_date  promotion_id
0              1        45308        33  2021-08-26            24
1              2        10070        81  2022-03-19             3
2              3        43308        17  2021-01-21            25
3              4        47997        85  2021-01-16            48
4              5        36546        81  2022-09-14            33
...          ...          ...       ...         ...           ...
299995    299996         5151        68  2021-07-21            50
299996    299997         1806        95  2021-03-25            50
299997    299998        10040        84  2022-09-17            18
299998    299999        48944        72  2022-03-24            26
299999    300000        29100         8  2023-01-13             2

[300000 rows x 5 columns]

In [6]:
shipments

        shipment_id  order_id     status
0                 1         1  delivered
1                 2         2    shipped
2                 3         3       late
3                 4         4       late
4                 5         5       late
...             ...       ...        ...
299995       299996    299996  delivered
299996       299997    299997  delivered
299997       299998    299998    shipped
299998       299999    299999       late
299999       300000    300000       late

[300000 rows x 3 columns]

In [5]:
stores

    store_id       city
0          1       Pune
1          2       Pune
2          3      Delhi
3          4     Mumbai
4          5     Mumbai
..       ...        ...
95        96       Pune
96        97     Mumbai
97        98     Mumbai
98        99  Bangalore
99       100      Delhi

[100 rows x 2 columns]

In [4]:
orders.shape

(300000, 5)

In [85]:
orders.dtypes

order_id                 int64
customer_id              int64
store_id                 int64
order_date      datetime64[us]
promotion_id             int64
dtype: object

In [89]:
customers

       customer_id       city signup_date
0                1     Mumbai  2021-02-16
1                2  Bangalore  2019-06-22
2                3       Pune  2022-01-25
3                4     Mumbai  2023-06-14
4                5      Delhi  2023-06-24
...            ...        ...         ...
49995        49996  Bangalore  2020-11-24
49996        49997     Mumbai  2021-11-13
49997        49998  Bangalore  2023-02-18
49998        49999  Bangalore  2020-07-05
49999        50000  Bangalore  2019-06-05

[50000 rows x 3 columns]

In [92]:
products

      product_id  category_id  supplier_id  price
0              1            9          135   3987
1              2           18          194   4412
2              3           23          118   3548
3              4           19          139   1971
4              5           10          115   4495
...          ...          ...          ...    ...
9995        9996           15          197   2558
9996        9997           20          156   2516
9997        9998            9           44   1668
9998        9999           18           93   3895
9999       10000            1           18   4711

[10000 rows x 4 columns]

In [95]:
product_count = products.groupby("category_id")["product_id"].count()

print(product_count)

category_id
1     312
2     298
3     351
4     327
5     358
6     340
7     316
8     351
9     350
10    340
11    338
12    350
13    347
14    312
15    338
16    345
17    344
18    323
19    328
20    329
21    346
22    331
23    305
24    313
25    328
26    351
27    331
28    350
29    320
30    328
Name: product_id, dtype: int64

In [94]:
products["category_product"]=products["category_id"]
product_c=products["category_product"].value_counts().sort_index()
print(product_c)

category_product
1     312
2     298
3     351
4     327
5     358
6     340
7     316
8     351
9     350
10    340
11    338
12    350
13    347
14    312
15    338
16    345
17    344
18    323
19    328
20    329
21    346
22    331
23    305
24    313
25    328
26    351
27    331
28    350
29    320
30    328
Name: count, dtype: int64

In [91]:
customers["city_count"]=customers["city"]
customers_city=customers["city_count"].value_counts().sort_index()
print(customers_city)

city_count
Bangalore    12434
Delhi        12389
Mumbai       12656
Pune         12521
Name: count, dtype: int64

In [87]:
orders["month"]=orders["order_date"].dt.month
monthly_orders=orders["month"].value_counts().sort_index()

print(monthly_orders)

month
1     25666
2     23155
3     25517
4     24610
5     25442
6     24556
7     25539
8     25158
9     24651
10    25550
11    24707
12    25449
Name: count, dtype: int64

In [83]:
orders

        order_id  customer_id  store_id order_date  promotion_id
0              1        45308        33 2021-08-26            24
1              2        10070        81 2022-03-19             3
2              3        43308        17 2021-01-21            25
3              4        47997        85 2021-01-16            48
4              5        36546        81 2022-09-14            33
...          ...          ...       ...        ...           ...
299995    299996         5151        68 2021-07-21            50
299996    299997         1806        95 2021-03-25            50
299997    299998        10040        84 2022-09-17            18
299998    299999        48944        72 2022-03-24            26
299999    300000        29100         8 2023-01-13             2

[300000 rows x 5 columns]

In [82]:
stores.count()

store_id    100
city        100
dtype: int64

In [80]:
employees.count()

employee_id    1000
store_id       1000
salary         1000
dtype: int64

In [77]:
products["price"].mean()

np.float64(2537.5481)

In [78]:
products["price"].max()

np.int64(4999)

In [79]:
products["price"].min()

np.int64(100)

In [76]:
products["price"].describe()

count    10000.000000
mean      2537.548100
std       1411.008186
min        100.000000
25%       1311.000000
50%       2540.500000
75%       3753.250000
max       4999.000000
Name: price, dtype: float64

In [75]:
products.head()

   product_id  category_id  supplier_id  price
0           1            9          135   3987
1           2           18          194   4412
2           3           23          118   3548
3           4           19          139   1971
4           5           10          115   4495

In [74]:
orders.count()

order_id        300000
customer_id     300000
store_id        300000
order_date      300000
promotion_id    300000
dtype: int64

In [73]:
products.count()

product_id     10000
category_id    10000
supplier_id    10000
price          10000
dtype: int64

In [72]:
customers.count()

customer_id    50000
city           50000
signup_date    50000
dtype: int64

In [70]:
orders.sort_values("order_date").head(1)

        order_id  customer_id  store_id order_date  promotion_id
168479    168480        46506        49 2020-01-01            22

In [71]:
orders.sort_values("order_date").tail(1)

        order_id  customer_id  store_id order_date  promotion_id
126539    126540        23564        27 2024-01-01            47

In [69]:
orders.head()

   order_id  customer_id  store_id order_date  promotion_id
0         1        45308        33 2021-08-26            24
1         2        10070        81 2022-03-19             3
2         3        43308        17 2021-01-21            25
3         4        47997        85 2021-01-16            48
4         5        36546        81 2022-09-14            33

In [64]:
products.head(5)

   product_id  category_id  supplier_id  price
0           1            9          135   3987
1           2           18          194   4412
2           3           23          118   3548
3           4           19          139   1971
4           5           10          115   4495

In [63]:
order_items.head(5)

   order_item_id  order_id  product_id  qty  price
0              1    145042         472    3    176
1              2    110932        1666    2   1034
2              3    269799        8616    4   2290
3              4    298741        9909    3   1555
4              5    105218        1179    3    936

In [66]:
result_product=pd.merge(
    products,
    order_items,
    on="product_id",
    how="inner"
)
result_product.head(5)

,product_id,category_id,supplier_id,price_x,order_item_id,order_id,qty,price_y
0,1,9,135,3987,7410,97060,4,4501
1,1,9,135,3987,11547,243522,3,1087
2,1,9,135,3987,15674,215791,2,2486
3,1,9,135,3987,23309,173878,3,2144
4,1,9,135,3987,32026,198895,4,3757

In [67]:
products.head(5)

   product_id  category_id  supplier_id  price
0           1            9          135   3987
1           2           18          194   4412
2           3           23          118   3548
3           4           19          139   1971
4           5           10          115   4495

In [68]:
order_items.head(5)

   order_item_id  order_id  product_id  qty  price
0              1    145042         472    3    176
1              2    110932        1666    2   1034
2              3    269799        8616    4   2290
3              4    298741        9909    3   1555
4              5    105218        1179    3    936

In [61]:
df_payment=pd.DataFrame(payments)
sorted_df=df_payment.sort_values(by='amount', ascending=False)
sorted_df.head(10)

        payment_id  order_id  amount
233491      233492    233492   19999
205782      205783    205783   19999
55025        55026     55026   19999
272761      272762    272762   19999
238900      238901    238901   19999
289777      289778    289778   19999
145777      145778    145778   19999
219922      219923    219923   19999
90343        90344     90344   19999
260104      260105    260105   19999

In [62]:
df_payment=pd.DataFrame(payments)
sorted_df=df_payment.sort_values(by='amount', ascending=True)
sorted_df.head(10)

        payment_id  order_id  amount
293160      293161    293161     100
181401      181402    181402     100
9077          9078      9078     100
117800      117801    117801     100
142287      142288    142288     100
35725        35726     35726     100
157140      157141    157141     100
129395      129396    129396     100
268398      268399    268399     100
222449      222450    222450     100

In [49]:
customers.head(5)

   customer_id       city signup_date
0            1     Mumbai  2021-02-16
1            2  Bangalore  2019-06-22
2            3       Pune  2022-01-25
3            4     Mumbai  2023-06-14
4            5      Delhi  2023-06-24

In [46]:
employees.head(5)

   employee_id  store_id  salary
0            1        46   33345
1            2        29   23325
2            3        54   22348
3            4        22   77360
4            5        75   69422

In [45]:
df_payment=pd.DataFrame(payments)
sorted_df=df_payment.sort_values(by='amount', ascending=False)
print(sorted_df)

        payment_id  order_id  amount
233491      233492    233492   19999
205782      205783    205783   19999
55025        55026     55026   19999
272761      272762    272762   19999
238900      238901    238901   19999
...            ...       ...     ...
181401      181402    181402     100
117800      117801    117801     100
170733      170734    170734     100
129395      129396    129396     100
91562        91563     91563     100

[300000 rows x 3 columns]

In [44]:
payments.head(5)

   payment_id  order_id  amount
0           1         1    1462
1           2         2    2272
2           3         3    1342
3           4         4    1906
4           5         5    7185

In [41]:
payments.dtypes

payment_id    int64
order_id      int64
amount        int64
dtype: object

In [39]:
df_categories=pd.DataFrame(categories)
unique_category=df_categories['category_name'].unique()
print(unique_category)

<StringArray>
[ 'Cat_1',  'Cat_2',  'Cat_3',  'Cat_4',  'Cat_5',  'Cat_6',  'Cat_7',
  'Cat_8',  'Cat_9', 'Cat_10', 'Cat_11', 'Cat_12', 'Cat_13', 'Cat_14',
 'Cat_15', 'Cat_16', 'Cat_17', 'Cat_18', 'Cat_19', 'Cat_20', 'Cat_21',
 'Cat_22', 'Cat_23', 'Cat_24', 'Cat_25', 'Cat_26', 'Cat_27', 'Cat_28',
 'Cat_29', 'Cat_30']
Length: 30, dtype: str

In [38]:
categories.info

<bound method DataFrame.info of     category_id category_name
0             1         Cat_1
1             2         Cat_2
2             3         Cat_3
3             4         Cat_4
4             5         Cat_5
5             6         Cat_6
6             7         Cat_7
7             8         Cat_8
8             9         Cat_9
9            10        Cat_10
10           11        Cat_11
11           12        Cat_12
12           13        Cat_13
13           14        Cat_14
14           15        Cat_15
15           16        Cat_16
16           17        Cat_17
17           18        Cat_18
18           19        Cat_19
19           20        Cat_20
20           21        Cat_21
21           22        Cat_22
22           23        Cat_23
23           24        Cat_24
24           25        Cat_25
25           26        Cat_26
26           27        Cat_27
27           28        Cat_28
28           29        Cat_29
29           30        Cat_30>

In [37]:
df_stores=pd.DataFrame(stores)
unique_city=df_stores['city'].unique()
print(unique_city)

<StringArray>
['Pune', 'Delhi', 'Mumbai', 'Bangalore']
Length: 4, dtype: str

In [30]:
stores.city

0          Pune
1          Pune
2         Delhi
3        Mumbai
4        Mumbai
        ...
95         Pune
96       Mumbai
97       Mumbai
98    Bangalore
99        Delhi
Name: city, Length: 100, dtype: str

In [31]:
stores.info

<bound method DataFrame.info of     store_id       city
0          1       Pune
1          2       Pune
2          3      Delhi
3          4     Mumbai
4          5     Mumbai
..       ...        ...
95        96       Pune
96        97     Mumbai
97        98     Mumbai
98        99  Bangalore
99       100      Delhi

[100 rows x 2 columns]>

In [32]:
df_stores=pd.DataFrame(stores)
df_city=df_stores[df_stores['city']=='Pune']
print(df_city)

    store_id  city
0          1  Pune
1          2  Pune
11        12  Pune
14        15  Pune
15        16  Pune
22        23  Pune
23        24  Pune
25        26  Pune
29        30  Pune
32        33  Pune
38        39  Pune
40        41  Pune
42        43  Pune
46        47  Pune
48        49  Pune
49        50  Pune
52        53  Pune
60        61  Pune
64        65  Pune
66        67  Pune
71        72  Pune
73        74  Pune
77        78  Pune
90        91  Pune
91        92  Pune
93        94  Pune
95        96  Pune

In [33]:
df_stores=pd.DataFrame(stores)
df_city=df_stores[df_stores['city']=='Mumbai']
print(df_city)

    store_id    city
3          4  Mumbai
4          5  Mumbai
5          6  Mumbai
13        14  Mumbai
18        19  Mumbai
19        20  Mumbai
21        22  Mumbai
27        28  Mumbai
31        32  Mumbai
33        34  Mumbai
36        37  Mumbai
37        38  Mumbai
41        42  Mumbai
47        48  Mumbai
51        52  Mumbai
53        54  Mumbai
54        55  Mumbai
56        57  Mumbai
65        66  Mumbai
67        68  Mumbai
74        75  Mumbai
81        82  Mumbai
83        84  Mumbai
84        85  Mumbai
85        86  Mumbai
86        87  Mumbai
88        89  Mumbai
89        90  Mumbai
94        95  Mumbai
96        97  Mumbai
97        98  Mumbai

In [21]:
df_shipments=pd.DataFrame(shipments)
df_status=df_shipments[df_shipments['status']=='delivered']
print(df_status)

        shipment_id  order_id     status
0                 1         1  delivered
7                 8         8  delivered
9                10        10  delivered
15               16        16  delivered
16               17        17  delivered
...             ...       ...        ...
299974       299975    299975  delivered
299976       299977    299977  delivered
299982       299983    299983  delivered
299995       299996    299996  delivered
299996       299997    299997  delivered

[99862 rows x 3 columns]

In [23]:
result=pd.merge(
    shipments,
    orders,
    on="order_id",
    how="inner"
)
print(result)

        shipment_id  order_id     status  customer_id  store_id order_date  \
0                 1         1  delivered        45308        33 2021-08-26
1                 2         2    shipped        10070        81 2022-03-19
2                 3         3       late        43308        17 2021-01-21
3                 4         4       late        47997        85 2021-01-16
4                 5         5       late        36546        81 2022-09-14
...             ...       ...        ...          ...       ...        ...
299995       299996    299996  delivered         5151        68 2021-07-21
299996       299997    299997  delivered         1806        95 2021-03-25
299997       299998    299998    shipped        10040        84 2022-09-17
299998       299999    299999       late        48944        72 2022-03-24
299999       300000    300000       late        29100         8 2023-01-13

        promotion_id
0                 24
1                  3
2                 25
3                 48
4                 33
...              ...
299995            50
299996            50
299997            18
299998            26
299999             2

[300000 rows x 7 columns]

In [29]:
df_result=pd.merge(
    shipments,
    payments,
    on="order_id",
    how="inner"
)
df_result=df_result[shipments['status']=='delivered']
print(df_result)

        shipment_id  order_id     status  payment_id  amount
0                 1         1  delivered           1    1462
7                 8         8  delivered           8   10407
9                10        10  delivered          10    5666
15               16        16  delivered          16    6483
16               17        17  delivered          17    8486
...             ...       ...        ...         ...     ...
299974       299975    299975  delivered      299975    1490
299976       299977    299977  delivered      299977   16441
299982       299983    299983  delivered      299983   18899
299995       299996    299996  delivered      299996   16433
299996       299997    299997  delivered      299997   12560

[99862 rows x 5 columns]

In [19]:
shipments.info

<bound method DataFrame.info of         shipment_id  order_id     status
0                 1         1  delivered
1                 2         2    shipped
2                 3         3       late
3                 4         4       late
4                 5         5       late
...             ...       ...        ...
299995       299996    299996  delivered
299996       299997    299997  delivered
299997       299998    299998    shipped
299998       299999    299999       late
299999       300000    300000       late

[300000 rows x 3 columns]>

In [26]:
orders.info

<bound method DataFrame.info of         order_id  customer_id  store_id order_date  promotion_id
0              1        45308        33 2021-08-26            24
1              2        10070        81 2022-03-19             3
2              3        43308        17 2021-01-21            25
3              4        47997        85 2021-01-16            48
4              5        36546        81 2022-09-14            33
...          ...          ...       ...        ...           ...
299995    299996         5151        68 2021-07-21            50
299996    299997         1806        95 2021-03-25            50
299997    299998        10040        84 2022-09-17            18
299998    299999        48944        72 2022-03-24            26
299999    300000        29100         8 2023-01-13             2

[300000 rows x 5 columns]>

In [18]:
returns.info

<bound method DataFrame.info of        return_id  order_item_id  refund
0              1         496351    2282
1              2         522631    4637
2              3         481424    2421
3              4         207559    1805
4              5         265929    4907
...          ...            ...     ...
29995      29996         220719    2304
29996      29997         427518    3739
29997      29998         482831     205
29998      29999          32985     671
29999      30000         113304    2778

[30000 rows x 3 columns]>

In [17]:
products.info

<bound method DataFrame.info of       product_id  category_id  supplier_id  price
0              1            9          135   3987
1              2           18          194   4412
2              3           23          118   3548
3              4           19          139   1971
4              5           10          115   4495
...          ...          ...          ...    ...
9995        9996           15          197   2558
9996        9997           20          156   2516
9997        9998            9           44   1668
9998        9999           18           93   3895
9999       10000            1           18   4711

[10000 rows x 4 columns]>

In [16]:
payments.info

<bound method DataFrame.info of         payment_id  order_id  amount
0                1         1    1462
1                2         2    2272
2                3         3    1342
3                4         4    1906
4                5         5    7185
...            ...       ...     ...
299995      299996    299996   16433
299996      299997    299997   12560
299997      299998    299998    8735
299998      299999    299999   12792
299999      300000    300000   15349

[300000 rows x 3 columns]>

In [15]:
order_items.info

<bound method DataFrame.info of         order_item_id  order_id  product_id  qty  price
0                   1    145042         472    3    176
1                   2    110932        1666    2   1034
2                   3    269799        8616    4   2290
3                   4    298741        9909    3   1555
4                   5    105218        1179    3    936
...               ...       ...         ...  ...    ...
599995         599996    199013        1358    3   4638
599996         599997     61973        3240    2   2875
599997         599998     56980        5447    3    565
599998         599999    119571        9216    3   3867
599999         600000    298854        4441    3   3074

[600000 rows x 5 columns]>

In [57]:
print(categories)

    category_id category_name
0             1         Cat_1
1             2         Cat_2
2             3         Cat_3
3             4         Cat_4
4             5         Cat_5
5             6         Cat_6
6             7         Cat_7
7             8         Cat_8
8             9         Cat_9
9            10        Cat_10
10           11        Cat_11
11           12        Cat_12
12           13        Cat_13
13           14        Cat_14
14           15        Cat_15
15           16        Cat_16
16           17        Cat_17
17           18        Cat_18
18           19        Cat_19
19           20        Cat_20
20           21        Cat_21
21           22        Cat_22
22           23        Cat_23
23           24        Cat_24
24           25        Cat_25
25           26        Cat_26
26           27        Cat_27
27           28        Cat_28
28           29        Cat_29
29           30        Cat_30

In [16]:
print(customers)

       customer_id       city signup_date
0                1     Mumbai  2021-02-16
1                2  Bangalore  2019-06-22
2                3       Pune  2022-01-25
3                4     Mumbai  2023-06-14
4                5      Delhi  2023-06-24
...            ...        ...         ...
49995        49996  Bangalore  2020-11-24
49996        49997     Mumbai  2021-11-13
49997        49998  Bangalore  2023-02-18
49998        49999  Bangalore  2020-07-05
49999        50000  Bangalore  2019-06-05

[50000 rows x 3 columns]

In [56]:
employees.columns

Index(['employee_id', 'store_id', 'salary'], dtype='str')

In [17]:
print(products.head(10))

   product_id  category_id  supplier_id  price
0           1            9          135   3987
1           2           18          194   4412
2           3           23          118   3548
3           4           19          139   1971
4           5           10          115   4495
5           6           17           53   2634
6           7            8          160   3028
7           8           30           21   3686
8           9           29           74   1844
9          10           29           77    316

In [27]:
df_customers=pd.DataFrame(customers)
df_city=df_customers[df_customers['city']=='Mumbai']
print(df_city)

       customer_id    city signup_date
0                1  Mumbai  2021-02-16
3                4  Mumbai  2023-06-14
8                9  Mumbai  2019-09-06
19              20  Mumbai  2021-07-07
20              21  Mumbai  2022-11-09
...            ...     ...         ...
49985        49986  Mumbai  2020-03-21
49988        49989  Mumbai  2019-12-08
49989        49990  Mumbai  2022-09-30
49994        49995  Mumbai  2022-11-26
49996        49997  Mumbai  2021-11-13

[12656 rows x 3 columns]

In [35]:
df_customers.columns.to_list()

['customer_id', 'city', 'signup_date']

In [33]:
print(dir(df_customers.columns.to_list))

['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__func__', '__ge__', '__get__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__self__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']

In [41]:
print(dir(products))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__firstlineno__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__static_attributes__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append_internal', '_arith_method', '_arith_method_with_reindex', '_attrs', '_box_col_values', '_can_fast_transpose', '_check_copy_deprecation', '_check_inplace_and_allows_duplicate_labels', '_check_label_or_level_ambiguity', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_combine_frame', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_from_mgr', '_constructor_sliced', '_constructor_sliced_from_mgr', '_dir_additions', '_dir_deletions', '_dispatch_frame_op', '_drop_axis', '_drop_labels_or_levels', '_ensure_valid_index', '_find_valid_index', '_flags', '_flex_arith_method', '_flex_cmp_method', '_from_arrays', '_from_mgr', '_get_agg_axis', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_column_array', '_get_index_resolvers', '_get_item', '_get_label_or_level_values', '_get_numeric_data', '_get_value', '_get_values_for_csv', '_getitem_bool_array', '_getitem_multilevel', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_info_repr', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_homogeneous_type', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_iset_item', '_iset_item_mgr', '_iset_not_inplace', '_iter_column_arrays', '_ixs', '_logical_func', '_logical_method', '_maybe_align_series_as_frame', '_metadata', '_mgr', '_min_count_stat_function', '_module_source', '_needs_reindex_multi', '_pad_or_backfill', '_reduce', '_reduce_axis1', '_reindex_axes', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_columnwise', '_repr_data_resource_', '_repr_fits_horizontal_', '_repr_fits_vertical_', '_repr_html_', '_repr_latex_', '_reset_cache', '_sanitize_column', '_select_dtypes_indices', '_series', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_item', '_set_item_frame_value', '_set_item_mgr', '_set_value', '_setitem_array', '_setitem_frame', '_setitem_slice', '_shift_with_freq', '_should_reindex_frame_op', '_slice', '_stat_function', '_stat_function_ddof', '_to_dict_of_blocks', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'attrs', 'axes', 'between_time', 'bfill', 'boxplot', 'category_id', 'clip', 'columns', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first_valid_index', 'flags', 'floordiv', 'from_arrow', 'from_dict', 'from_records', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'insert', 'interpolate', 'isetitem', 'isin', 'isna', 'isnull', 'items', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last_valid_index', 'le', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'price', 'prod', 'product', 'product_id', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'supplier_id', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_hdf', 'to_html', 'to_iceberg', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']

In [47]:
df_products=pd.DataFrame(products)
df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product_id   10000 non-null  int64
 1   category_id  10000 non-null  int64
 2   supplier_id  10000 non-null  int64
 3   price        10000 non-null  int64
dtypes: int64(4)
memory usage: 312.6 KB

In [ ]:
df_products=pd.DataFrame(products)
df_price=df_products[df_products['price']>1000]
print(df_price)

      product_id  category_id  supplier_id  price
0              1            9          135   3987
1              2           18          194   4412
2              3           23          118   3548
3              4           19          139   1971
4              5           10          115   4495
...          ...          ...          ...    ...
9995        9996           15          197   2558
9996        9997           20          156   2516
9997        9998            9           44   1668
9998        9999           18           93   3895
9999       10000            1           18   4711

[8147 rows x 4 columns]

In [51]:
df_products=pd.DataFrame(products)
df_price=df_products[df_products['price'].between(500,2000)]
print(df_price)

      product_id  category_id  supplier_id  price
3              4           19          139   1971
8              9           29           74   1844
10            11            9           61    564
12            13           30           17   1910
16            17           15          124   1578
...          ...          ...          ...    ...
9991        9992            6           29   1002
9992        9993            1          109    616
9993        9994            5          136    580
9994        9995            9          126   1175
9997        9998            9           44   1668

[3105 rows x 4 columns]

In [22]:
result=pd.merge(
    products,
    categories,
    on="category_id",
    how="inner"
)
result=result[result["category_name"]=="Cat_10"]
print(result)

      product_id  category_id  supplier_id  price category_name
4              5           10          115   4495        Cat_10
13            14           10          187   2403        Cat_10
15            16           10          122   3332        Cat_10
21            22           10          140   2753        Cat_10
61            62           10          134   1950        Cat_10
...          ...          ...          ...    ...           ...
9865        9866           10          107   3770        Cat_10
9904        9905           10          165   2379        Cat_10
9962        9963           10           37   1150        Cat_10
9975        9976           10            8   4446        Cat_10
9990        9991           10           54    334        Cat_10

[340 rows x 5 columns]

In [4]:
result=result[result["category_name"]=="Cat_10"]

In [5]:
print(result)

      product_id  category_id  supplier_id  price category_name
4              5           10          115   4495        Cat_10
13            14           10          187   2403        Cat_10
15            16           10          122   3332        Cat_10
21            22           10          140   2753        Cat_10
61            62           10          134   1950        Cat_10
...          ...          ...          ...    ...           ...
9865        9866           10          107   3770        Cat_10
9904        9905           10          165   2379        Cat_10
9962        9963           10           37   1150        Cat_10
9975        9976           10            8   4446        Cat_10
9990        9991           10           54    334        Cat_10

[340 rows x 5 columns]

In [7]:
orders.columns

Index(['order_id', 'customer_id', 'store_id', 'order_date', 'promotion_id'], dtype='str')

In [9]:
print(orders)

        order_id  customer_id  store_id  order_date  promotion_id
0              1        45308        33  2021-08-26            24
1              2        10070        81  2022-03-19             3
2              3        43308        17  2021-01-21            25
3              4        47997        85  2021-01-16            48
4              5        36546        81  2022-09-14            33
...          ...          ...       ...         ...           ...
299995    299996         5151        68  2021-07-21            50
299996    299997         1806        95  2021-03-25            50
299997    299998        10040        84  2022-09-17            18
299998    299999        48944        72  2022-03-24            26
299999    300000        29100         8  2023-01-13             2

[300000 rows x 5 columns]

In [10]:
orders.head()

   order_id  customer_id  store_id  order_date  promotion_id
0         1        45308        33  2021-08-26            24
1         2        10070        81  2022-03-19             3
2         3        43308        17  2021-01-21            25
3         4        47997        85  2021-01-16            48
4         5        36546        81  2022-09-14            33

In [11]:
orders.dtypes

order_id        int64
customer_id     int64
store_id        int64
order_date        str
promotion_id    int64
dtype: object

In [12]:
orders["order_date"]=pd.to_datetime(orders["order_date"])

In [13]:
date=pd.to_datetime("2023-01-01")
orders_after=orders[orders["order_date"]>date]
print(orders_after)

        order_id  customer_id  store_id order_date  promotion_id
5              6         9479        84 2023-02-03             2
11            12         7224        85 2023-01-05             2
12            13        46135        93 2023-06-14            35
15            16        24181        19 2023-05-31            18
18            19        21963        18 2023-05-02            41
...          ...          ...       ...        ...           ...
299975    299976        23233        56 2023-07-31            12
299980    299981        14740        67 2023-07-28            29
299987    299988        40599        68 2023-06-13            46
299990    299991        33057        42 2023-12-12             1
299999    300000        29100         8 2023-01-13             2

[75006 rows x 5 columns]

In [14]:
orders.info

<bound method DataFrame.info of         order_id  customer_id  store_id order_date  promotion_id
0              1        45308        33 2021-08-26            24
1              2        10070        81 2022-03-19             3
2              3        43308        17 2021-01-21            25
3              4        47997        85 2021-01-16            48
4              5        36546        81 2022-09-14            33
...          ...          ...       ...        ...           ...
299995    299996         5151        68 2021-07-21            50
299996    299997         1806        95 2021-03-25            50
299997    299998        10040        84 2022-09-17            18
299998    299999        48944        72 2022-03-24            26
299999    300000        29100         8 2023-01-13             2

[300000 rows x 5 columns]>