In [1]:
import pandas as pd

In [2]:
sales_data_orders=pd.read_excel(r"D:\Project\sales_data.xlsx", sheet_name="Orders")
sales_data_customers=pd.read_excel(r"D:\Project\sales_data.xlsx", sheet_name="Customers")
sales_data_products=pd.read_excel(r"D:\Project\sales_data.xlsx", sheet_name="Products")
sales_data_returns=pd.read_excel(r"D:\Project\sales_data.xlsx", sheet_name="Returns")

In [3]:
sales_data_orders.head(5)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15
2,O00003,2025-11-13 00:00:00,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98
3,O00004,2025-10-29 00:00:00,C0049,P029,4,21540.38,0.0,Store,COD,86161.52
4,O00005,2025-02-20 00:00:00,C0073,P040,1,13262.69,10.0,Online,Card,11936.42

In [4]:
sales_data_customers.tail(10)

,customer_id,customer_name,email,segment,region,city,signup_date
110,C0111,Customer 111,cust111@example.com,Corporate,East,Patna,2023-12-05
111,C0112,Customer 112,cust112@example.com,Wholesale,East,Patna,2023-08-25
112,C0113,Customer 113,cust113@example.com,Corporate,North,Chandigarh,2024-07-02
113,C0114,Customer 114,cust114@example.com,Wholesale,South,Chennai,2023-10-11
114,C0115,Customer 115,cust115@example.com,Wholesale,East,Kolkata,2023-08-21
115,C0116,Customer 116,cust116@example.com,Corporate,East,Bhubaneswar,2024-06-30
116,C0117,Customer 117,NaN,Retail,South,Hyderabad,2024-07-20
117,C0118,Customer 118,cust118@example.com,Wholesale,East,Bhubaneswar,2023-04-16
118,C0119,Customer 119,cust119@example.com,Wholesale,North,Jaipur,2023-12-15
119,C0120,Customer 120,cust120@example.com,Wholesale,South,Bengaluru,2023-04-27

In [5]:
sales_data_products.head(10)

  product_id  product_name     category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001      Grocery     2916.58     2252.96      True
1       P002  APP-Item-002      Apparel     3617.52     2100.87      True
2       P003  SPO-Item-003       Sports    10634.76     5944.18      True
3       P004  APP-Item-004      Apparel    12708.08     7090.61      True
4       P005  GRO-Item-005      Grocery    16299.63    11629.50      True
5       P006  BEA-Item-006       Beauty    14793.25    11728.52      True
6       P007  APP-Item-007      Apparel    17498.76    11410.51      True
7       P008  APP-Item-008      Apparel    23936.74    15582.30      True
8       P009  BEA-Item-009       Beauty     2553.40     2053.57      True
9       P010  ELE-Item-010  Electronics    18283.83    12997.40     False

In [6]:
sales_data_returns.head(5)

  return_id order_id return_date            reason  refund_amount
0     R0001   O01050  2025-05-20     Late Delivery        1917.72
1     R0002   O00477  2025-02-11           Damaged       14780.26
2     R0003   O00062  2025-07-31     Late Delivery       14078.53
3     R0004   O00911  2025-03-03  Not as described       28091.19
4     R0005   O00069  2025-10-13  Not as described       33479.32

In [7]:
sales_data=r"D:\Project\sales_data.xlsx"
sheet_names=["Orders","Customers","Products","Returns"]

sheets_dict=pd.read_excel(sales_data, sheet_name=sheet_names)
for sheet_name, df in sheets_dict.items():
    rows, columns = df.shape
    print(f"Sheet: {sheet_name} - Rows: {rows}, Columns: {columns}")

Sheet: Orders - Rows: 1208, Columns: 10
Sheet: Customers - Rows: 120, Columns: 7
Sheet: Products - Rows: 40, Columns: 6
Sheet: Returns - Rows: 90, Columns: 5

In [8]:
sales_data=r"D:\Project\sales_data.xlsx"
sheet_names=["Orders","Customers","Products","Returns"]

sheets_dict=pd.read_excel(sales_data, sheet_name=sheet_names)
for sheet_name, df in sheets_dict.items():
    columns = df.columns
    print(f"Sheet: {sheet_name} - Columns: {columns}")

Sheet: Orders - Columns: Index(['order_id', 'order_date', 'customer_id', 'product_id', 'quantity',
       'unit_price', 'discount_pct', 'channel', 'payment_method', 'revenue'],
      dtype='str')
Sheet: Customers - Columns: Index(['customer_id', 'customer_name', 'email', 'segment', 'region', 'city',
       'signup_date'],
      dtype='str')
Sheet: Products - Columns: Index(['product_id', 'product_name', 'category', 'unit_price', 'cost_price',
       'in_stock'],
      dtype='str')
Sheet: Returns - Columns: Index(['return_id', 'order_id', 'return_date', 'reason', 'refund_amount'], dtype='str')

In [9]:
sales_data_orders.head(2)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15

In [12]:
sales_data_orders.groupby("payment_method").aggregate({"revenue":"mean"})

                     revenue
payment_method
COD             45227.239664
Card            42001.223320
NetBanking      43172.746996
UPI             43148.282949
Wallet          42507.894728

In [ ]:
sales_data_orders.groupby("payment_method").aggregate({"revenue":"sum"})

                    revenue
payment_method
COD             10764083.04
Card            10122294.82
NetBanking      10922704.99
UPI              9363177.40
Wallet          10159386.84

In [ ]:
sales_data_orders.groupby("payment_method").aggregate({"order_id":"count"})

                order_id
payment_method
COD                  238
Card                 241
NetBanking           253
UPI                  217
Wallet               239

In [ ]:
sales_data_orders.groupby("channel").aggregate({"quantity":"sum"})

         quantity
channel
Online       1411
Partner      1496
Store        1326

In [ ]:
sales_data_orders.groupby("channel").aggregate({"order_id": "count"})

         order_id
channel
Online        395
Partner       422
Store         391

In [11]:
sales_data_orders['revenue'] = sales_data_orders['revenue'].astype(str).str.replace("₹", "", regex=False).astype(float)

In [ ]:
sales_data_orders.groupby("channel").aggregate({"revenue":"sum"})

             revenue
channel
Online   17804956.26
Partner  17247193.82
Store    17024621.10

In [ ]:
sales_data_orders.groupby("channel").aggregate({"revenue":"mean"})

              revenue
channel
Online   45075.838633
Partner  40870.127536
Store    43541.230435

In [ ]:
sales_data_orders.columns

Index(['order_id', 'order_date', 'customer_id', 'product_id', 'quantity',
       'unit_price', 'discount_pct', 'channel', 'payment_method', 'revenue'],
      dtype='str')

In [ ]:
sales_data_orders.head()

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15
2,O00003,2025-11-13 00:00:00,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98
3,O00004,2025-10-29 00:00:00,C0049,P029,4,21540.38,0.0,Store,COD,86161.52
4,O00005,2025-02-20 00:00:00,C0073,P040,1,13262.69,10.0,Online,Card,11936.42

In [ ]:
sales_data_orders.head(5)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15
2,O00003,2025-11-13 00:00:00,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98
3,O00004,2025-10-29 00:00:00,C0049,P029,4,21540.38,0.0,Store,COD,86161.52
4,O00005,2025-02-20 00:00:00,C0073,P040,1,13262.69,10.0,Online,Card,11936.42

In [ ]:
sales_data_customers.head(5)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27
1,C0002,Customer 2,cust2@example.com,Wholesale,East,Patna,2023-05-04
2,C0003,Customer 3,NaN,Retail,South,Chennai,2024-08-25
3,C0004,Customer 4,NaN,Corporate,South,Chennai,2024-10-08
4,C0005,Customer 5,NaN,Retail,North,Chandigarh,2025-05-30

In [ ]:
sales_data_segment=sales_data_orders.join(
    sales_data_customers.set_index("customer_id"), 
    on="customer_id", 
    how="left"
)

In [ ]:
sales_data_segment.head()

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue,customer_name,email,segment,region,city,signup_date
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59,Customer 106,cust106@example.com,Corporate,East,Guwahati,2023-07-15
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15,Customer 20,NaN,Corporate,North,Jaipur,2024-05-03
2,O00003,2025-11-13 00:00:00,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98,Customer 72,cust72@example.com,Retail,West,Surat,2025-05-10
3,O00004,2025-10-29 00:00:00,C0049,P029,4,21540.38,0.0,Store,COD,86161.52,Customer 49,cust49@example.com,Corporate,North,Jaipur,2024-02-14
4,O00005,2025-02-20 00:00:00,C0073,P040,1,13262.69,10.0,Online,Card,11936.42,Customer 73,cust73@example.com,Wholesale,East,Patna,2024-03-26

In [ ]:
sales_data_segment.groupby("segment").aggregate({"customer_id":"count"}).rename(columns={"customer_id":"count"})

           count
segment
Corporate    411
Retail       349
Wholesale    440
retail         7

In [ ]:
sales_data_customers.head(5)

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27
1,C0002,Customer 2,cust2@example.com,Wholesale,East,Patna,2023-05-04
2,C0003,Customer 3,NaN,Retail,South,Chennai,2024-08-25
3,C0004,Customer 4,NaN,Corporate,South,Chennai,2024-10-08
4,C0005,Customer 5,NaN,Retail,North,Chandigarh,2025-05-30

In [ ]:
sales_data_customers.groupby("region").aggregate({"customer_id":"count"}).rename(columns={"customer_id":"Total_Customers"})

        Total_Customers
region
East                 31
North                35
South                27
West                 26
north                 1

In [ ]:
sales_data_customers.groupby("city").aggregate({"customer_id":"count"}).rename(columns={"customer_id":"Total_Customers"})

             Total_Customers
city
Ahmedabad                  6
Bengaluru                  5
Bhubaneswar                8
Chandigarh                12
Chennai                    6
Delhi                      8
Guwahati                   6
Hyderabad                  9
Jaipur                     9
Kochi                      6
Kolkata                    7
Lucknow                    6
MUMBAI                     1
Mumbai                     4
Patna                     10
Pune                      10
Surat                      7

In [ ]:
sales_data_products.head()

  product_id  product_name category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001  Grocery     2916.58     2252.96      True
1       P002  APP-Item-002  Apparel     3617.52     2100.87      True
2       P003  SPO-Item-003   Sports    10634.76     5944.18      True
3       P004  APP-Item-004  Apparel    12708.08     7090.61      True
4       P005  GRO-Item-005  Grocery    16299.63    11629.50      True

In [ ]:
sales_data_products.groupby("category").aggregate({"product_id":"count"}).rename(columns={"product_id":"Total_Products"})

             Total_Products
category
Apparel                  10
Beauty                    4
Electronics               5
Grocery                   9
Home                      6
Sports                    6

In [ ]:
sales_data_products.groupby("product_id").aggregate({"unit_price":"mean"}).rename(columns={"unit_price":"Avg_Product_Price"})

            Avg_Product_Price
product_id
P001                  2916.58
P002                  3617.52
P003                 10634.76
P004                 12708.08
P005                 16299.63
P006                 14793.25
P007                 17498.76
P008                 23936.74
P009                  2553.40
P010                 18283.83
P011                 13868.21
P012                  4928.37
P013                 24632.75
P014                  7057.64
P015                  9349.00
P016                 23425.87
P017                 18268.80
P018                 24739.66
P019                  8208.43
P020                 20571.79
P021                  1794.79
P022                 16437.65
P023                  6732.27
P024                 14676.96
P025                  5600.12
P026                 18931.19
P027                  4125.55
P028                  9633.24
P029                 21540.38
P030                 22136.99
P031                  7443.48
P032                 21914.95
P033                 22828.80
P034                 12765.42
P035                 13553.57
P036                  8205.28
P037                  6100.39
P038                 18337.90
P039                 16544.81
P040                 13262.69