In [60]:
import pandas as pd

In [61]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\Tranzita\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\Users\Tranzita\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [62]:
sales_data_orders=pd.read_excel(r"D:\Project\sales_data.xlsx", sheet_name="Orders")
sales_data_orders.head(5)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15
2,O00003,2025-11-13 00:00:00,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98
3,O00004,2025-10-29 00:00:00,C0049,P029,4,21540.38,0.0,Store,COD,86161.52
4,O00005,2025-02-20 00:00:00,C0073,P040,1,13262.69,10.0,Online,Card,11936.42

In [63]:
sales_data_customers=pd.read_excel(r"D:\Project\sales_data.xlsx", sheet_name="Customers")
#sales_data_customers.head(2)
sales_data_customers.tail(10)

,customer_id,customer_name,email,segment,region,city,signup_date
110,C0111,Customer 111,cust111@example.com,Corporate,East,Patna,2023-12-05
111,C0112,Customer 112,cust112@example.com,Wholesale,East,Patna,2023-08-25
112,C0113,Customer 113,cust113@example.com,Corporate,North,Chandigarh,2024-07-02
113,C0114,Customer 114,cust114@example.com,Wholesale,South,Chennai,2023-10-11
114,C0115,Customer 115,cust115@example.com,Wholesale,East,Kolkata,2023-08-21
115,C0116,Customer 116,cust116@example.com,Corporate,East,Bhubaneswar,2024-06-30
116,C0117,Customer 117,NaN,Retail,South,Hyderabad,2024-07-20
117,C0118,Customer 118,cust118@example.com,Wholesale,East,Bhubaneswar,2023-04-16
118,C0119,Customer 119,cust119@example.com,Wholesale,North,Jaipur,2023-12-15
119,C0120,Customer 120,cust120@example.com,Wholesale,South,Bengaluru,2023-04-27

In [64]:
sales_data_products=pd.read_excel(r"D:\Project\sales_data.xlsx", sheet_name="Products")
sales_data_products.head(10)

  product_id  product_name     category  unit_price  cost_price  in_stock
0       P001  GRO-Item-001      Grocery     2916.58     2252.96      True
1       P002  APP-Item-002      Apparel     3617.52     2100.87      True
2       P003  SPO-Item-003       Sports    10634.76     5944.18      True
3       P004  APP-Item-004      Apparel    12708.08     7090.61      True
4       P005  GRO-Item-005      Grocery    16299.63    11629.50      True
5       P006  BEA-Item-006       Beauty    14793.25    11728.52      True
6       P007  APP-Item-007      Apparel    17498.76    11410.51      True
7       P008  APP-Item-008      Apparel    23936.74    15582.30      True
8       P009  BEA-Item-009       Beauty     2553.40     2053.57      True
9       P010  ELE-Item-010  Electronics    18283.83    12997.40     False

In [65]:
sales_data_returns=pd.read_excel(r"D:\Project\sales_data.xlsx", sheet_name="Returns")
sales_data_returns.head(5)

  return_id order_id return_date            reason  refund_amount
0     R0001   O01050  2025-05-20     Late Delivery        1917.72
1     R0002   O00477  2025-02-11           Damaged       14780.26
2     R0003   O00062  2025-07-31     Late Delivery       14078.53
3     R0004   O00911  2025-03-03  Not as described       28091.19
4     R0005   O00069  2025-10-13  Not as described       33479.32

In [66]:
sales_data=r"D:\Project\sales_data.xlsx"
sheet_names=["Orders","Customers","Products","Returns"]

sheets_dict=pd.read_excel(sales_data,sheet_name=sheet_names)
for sheet_name, df in sheets_dict.items():
    rows, columns = df.shape
    print(f"Sheet: {sheet_name} has {rows} rows and {columns} columns.")

Sheet: Orders has 1208 rows and 10 columns.
Sheet: Customers has 120 rows and 7 columns.
Sheet: Products has 40 rows and 6 columns.
Sheet: Returns has 90 rows and 5 columns.

In [67]:
sales_data=r"D:\Project\sales_data.xlsx"
sheet_names=["Orders","Customers","Products","Returns"]

sheets_dict=pd.read_excel(sales_data,sheet_name=sheet_names)
for sheet_name, df in sheets_dict.items():
    columns = df.columns
    print(f"Sheet: {sheet_name} has {columns} columns.")

Sheet: Orders has Index(['order_id', 'order_date', 'customer_id', 'product_id', 'quantity',
       'unit_price', 'discount_pct', 'channel', 'payment_method', 'revenue'],
      dtype='str') columns.
Sheet: Customers has Index(['customer_id', 'customer_name', 'email', 'segment', 'region', 'city',
       'signup_date'],
      dtype='str') columns.
Sheet: Products has Index(['product_id', 'product_name', 'category', 'unit_price', 'cost_price',
       'in_stock'],
      dtype='str') columns.
Sheet: Returns has Index(['return_id', 'order_id', 'return_date', 'reason', 'refund_amount'], dtype='str') columns.

In [68]:
sales_data=r"D:\Project\sales_data.xlsx"
sheets_dict=pd.read_excel(sales_data,sheet_name="Orders")
print("Column Name : DataType")
for sheet_name, df in sheets_dict.items():
    columns = df.dtypes
    print(f"{sheet_name} : {columns}")

Column Name : DataType
order_id : str
order_date : object
customer_id : str
product_id : str
quantity : int64
unit_price : float64
discount_pct : float64
channel : str
payment_method : str
revenue : object

In [69]:
sheets_dict.describe

<bound method NDFrame.describe of      order_id           order_date customer_id product_id  quantity  \
0      O00001  2025-02-07 00:00:00       C0106       P005         4
1      O00002  2025-02-13 00:00:00       C0020       P010         5
2      O00003  2025-11-13 00:00:00       C0072       P027         5
3      O00004  2025-10-29 00:00:00       C0049       P029         4
4      O00005  2025-02-20 00:00:00       C0073       P040         1
...       ...                  ...         ...        ...       ...
1203   O00191  2025-07-08 00:00:00       C0004       P024         5
1204   O01084  2025-10-25 00:00:00       C0084       P031         6
1205   O00284  2025-03-15 00:00:00       C0077       P021         2
1206   O00818  2025-02-06 00:00:00       C0047       P015         5
1207   O00315  2025-04-26 00:00:00       C0052       P030         5

      unit_price  discount_pct  channel payment_method    revenue
0       16299.63           5.0  Partner            UPI   61938.59
1       18283.83           0.0   Online            UPI   91419.15
2        4125.55          10.0   Online         Wallet   18564.98
3       21540.38           0.0    Store            COD   86161.52
4       13262.69          10.0   Online           Card   11936.42
...          ...           ...      ...            ...        ...
1203    14676.96          10.0    Store         Wallet   66046.32
1204     7443.48          20.0  Partner           Card    35728.7
1205     1794.79           0.0  Partner         Wallet    3589.58
1206     9349.00          15.0   Online           Card   39733.25
1207    22136.99           0.0    Store            UPI  110684.95

[1208 rows x 10 columns]>

In [70]:
sales_data_customers=pd.read_excel(r"D:\Project\sales_data.xlsx", sheet_name="Customers")
sales_data_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    120 non-null    str
 1   customer_name  120 non-null    str
 2   email          109 non-null    str
 3   segment        120 non-null    str
 4   region         120 non-null    str
 5   city           120 non-null    str
 6   signup_date    120 non-null    datetime64[us]
dtypes: datetime64[us](1), str(6)
memory usage: 6.7 KB

In [71]:
sales_data_orders=pd.read_excel(r"D:\Project\sales_data.xlsx", sheet_name="Orders")
sales_data_orders.shape

(1208, 10)

In [72]:
sales_data_orders.head(5)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15
2,O00003,2025-11-13 00:00:00,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98
3,O00004,2025-10-29 00:00:00,C0049,P029,4,21540.38,0.0,Store,COD,86161.52
4,O00005,2025-02-20 00:00:00,C0073,P040,1,13262.69,10.0,Online,Card,11936.42

In [73]:
sales_data_orders["customer_id"].unique()

<StringArray>
['C0106', 'C0020', 'C0072', 'C0049', 'C0073', 'C9999', 'C0021', 'C0038',
 'C0010', 'C0055',
 ...
 'C0043', 'C0111', 'C0031', 'C0119', 'C0108', 'C0063', 'C0019', 'C0114',
 'C0095', 'C0085']
Length: 121, dtype: str

In [74]:
sales_data_orders["product_id"].unique()

<StringArray>
['P005', 'P010', 'P027', 'P029', 'P040', 'P006', 'P001', 'P003', 'P015',
 'P999', 'P037', 'P026', 'P039', 'P018', 'P031', 'P011', 'P036', 'P008',
 'P032', 'P009', 'P013', 'P020', 'P035', 'P030', 'P025', 'P021', 'P004',
 'P034', 'P038', 'P017', 'P019', 'P023', 'P002', 'P024', 'P016', 'P007',
 'P028', 'P014', 'P012', 'P022', 'P033']
Length: 41, dtype: str

In [75]:
sales_data_orders["channel"].unique()

<StringArray>
['Partner', 'Online', 'Store']
Length: 3, dtype: str

In [76]:
sales_data_orders[["order_id", "order_date", "revenue"]]

     order_id           order_date    revenue
0      O00001  2025-02-07 00:00:00   61938.59
1      O00002  2025-02-13 00:00:00   91419.15
2      O00003  2025-11-13 00:00:00   18564.98
3      O00004  2025-10-29 00:00:00   86161.52
4      O00005  2025-02-20 00:00:00   11936.42
...       ...                  ...        ...
1203   O00191  2025-07-08 00:00:00   66046.32
1204   O01084  2025-10-25 00:00:00    35728.7
1205   O00284  2025-03-15 00:00:00    3589.58
1206   O00818  2025-02-06 00:00:00   39733.25
1207   O00315  2025-04-26 00:00:00  110684.95

[1208 rows x 3 columns]

In [77]:
sales_order=sales_data_orders[["order_id","quantity","unit_price","revenue"]]
print(sales_order)

     order_id  quantity  unit_price    revenue
0      O00001         4    16299.63   61938.59
1      O00002         5    18283.83   91419.15
2      O00003         5     4125.55   18564.98
3      O00004         4    21540.38   86161.52
4      O00005         1    13262.69   11936.42
...       ...       ...         ...        ...
1203   O00191         5    14676.96   66046.32
1204   O01084         6     7443.48    35728.7
1205   O00284         2     1794.79    3589.58
1206   O00818         5     9349.00   39733.25
1207   O00315         5    22136.99  110684.95

[1208 rows x 4 columns]

In [78]:
#sales_data_orders[sales_data_orders["quantity"]>5]
#sales_data_orders[sales_data_orders["quantity"]==1]
sales_data_orders[sales_data_orders["unit_price"]>10000]

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15
3,O00004,2025-10-29 00:00:00,C0049,P029,4,21540.38,0.0,Store,COD,86161.52
4,O00005,2025-02-20 00:00:00,C0073,P040,1,13262.69,10.0,Online,Card,11936.42
5,O00006,2025-03-30 00:00:00,C9999,P006,2,14793.25,0.0,Partner,UPI,29586.5
...,...,...,...,...,...,...,...,...,...,...
1197,O01198,2025-05-04 00:00:00,C0026,P024,4,14676.96,0.0,Online,COD,58707.84
1200,O00637,2025-12-05 00:00:00,C0077,P004,6,12708.08,10.0,Store,NetBanking,68623.63
1202,O01034,2025-10-02 00:00:00,C0028,P034,4,12765.42,15.0,Online,Wallet,43402.43
1203,O00191,2025-07-08 00:00:00,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32
1207,O00315,2025-04-26 00:00:00,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95

In [79]:
sales_data_customers[sales_data_customers["region"]=="North"]

,customer_id,customer_name,email,segment,region,city,signup_date
4,C0005,Customer 5,NaN,Retail,North,Chandigarh,2025-05-30
8,C0009,Customer 9,cust9@example.com,Wholesale,North,Delhi,2024-03-09
10,C0011,Customer 11,cust11@example.com,Wholesale,North,Delhi,2025-03-30
11,C0012,Customer 12,cust12@example.com,Corporate,North,Chandigarh,2024-04-04
13,C0014,Customer 14,cust14@example.com,Corporate,North,Lucknow,2023-04-11
14,C0015,Customer 15,cust15@example.com,Retail,North,Delhi,2023-06-20
19,C0020,Customer 20,NaN,Corporate,North,Jaipur,2024-05-03
23,C0024,Customer 24,cust24@example.com,Corporate,North,Delhi,2024-08-01
31,C0032,Customer 32,cust32@example.com,Retail,North,Chandigarh,2025-01-30
38,C0039,Customer 39,cust39@example.com,Retail,North,Jaipur,2024-03-16
47,C0048,Customer 48,cust48@example.com,Wholesale,North,Chandigarh,2025-06-04
48,C0049,Customer 49,cust49@example.com,Corporate,North,Jaipur,2024-02-14
53,C0054,Customer 54,cust54@example.com,Retail,North,Chandigarh,2024-11-11
63,C0064,Customer 64,cust64@example.com,Corporate,North,Chandigarh,2025-05-20
64,C0065,Customer 65,cust65@example.com,Corporate,North,Lucknow,2024-08-12
66,C0067,Customer 67,cust67@example.com,Retail,North,Delhi,2023-06-30
73,C0074,Customer 74,cust74@example.com,Wholesale,North,Jaipur,2023-11-24
74,C0075,Customer 75,cust75@example.com,Wholesale,North,Chandigarh,2024-12-11
77,C0078,Customer 78,cust78@example.com,Wholesale,North,Lucknow,2023-11-02
80,C0081,Customer 81,cust81@example.com,Corporate,North,Lucknow,2025-03-28
82,C0083,Customer 83,cust83@example.com,Corporate,North,Lucknow,2023-01-28
83,C0084,Customer 84,cust84@example.com,Wholesale,North,Lucknow,2023-07-06
84,C0085,Customer 85,cust85@example.com,Retail,North,Jaipur,2024-04-10
87,C0088,Customer 88,cust88@example.com,Retail,North,Jaipur,2025-03-10
88,C0089,Customer 89,cust89@example.com,Retail,North,Delhi,2025-05-09
89,C0090,Customer 90,cust90@example.com,Wholesale,North,Chandigarh,2024-11-16
90,C0091,Customer 91,cust91@example.com,Wholesale,North,Chandigarh,2025-02-24
92,C0093,Customer 93,cust93@example.com,Retail,North,Chandigarh,2024-08-15
93,C0094,Customer 94,cust94@example.com,Wholesale,North,Jaipur,2024-02-11
95,C0096,Customer 96,cust96@example.com,Corporate,North,Jaipur,2025-04-04
96,C0097,Customer 97,cust97@example.com,Wholesale,North,Delhi,2024-11-08
106,C0107,Customer 107,cust107@example.com,Wholesale,North,Chandigarh,2024-07-22
108,C0109,Customer 109,cust109@example.com,Wholesale,North,Delhi,2024-12-09
112,C0113,Customer 113,cust113@example.com,Corporate,North,Chandigarh,2024-07-02
118,C0119,Customer 119,cust119@example.com,Wholesale,North,Jaipur,2023-12-15

In [80]:
sales_data_customers[sales_data_customers["city"]=="Lucknow"]

,customer_id,customer_name,email,segment,region,city,signup_date
13,C0014,Customer 14,cust14@example.com,Corporate,North,Lucknow,2023-04-11
64,C0065,Customer 65,cust65@example.com,Corporate,North,Lucknow,2024-08-12
77,C0078,Customer 78,cust78@example.com,Wholesale,North,Lucknow,2023-11-02
80,C0081,Customer 81,cust81@example.com,Corporate,North,Lucknow,2025-03-28
82,C0083,Customer 83,cust83@example.com,Corporate,North,Lucknow,2023-01-28
83,C0084,Customer 84,cust84@example.com,Wholesale,North,Lucknow,2023-07-06

In [81]:
sales_data_customers[sales_data_customers["segment"]=="Corporate"]

,customer_id,customer_name,email,segment,region,city,signup_date
0,C0001,Customer 1,cust1@example.com,Corporate,South,Hyderabad,2024-10-27
3,C0004,Customer 4,NaN,Corporate,South,Chennai,2024-10-08
6,C0007,Customer 7,cust7@example.com,Corporate,West,Pune,2024-08-07
11,C0012,Customer 12,cust12@example.com,Corporate,North,Chandigarh,2024-04-04
13,C0014,Customer 14,cust14@example.com,Corporate,North,Lucknow,2023-04-11
17,C0018,Customer 18,cust18@example.com,Corporate,West,Ahmedabad,2025-03-13
19,C0020,Customer 20,NaN,Corporate,North,Jaipur,2024-05-03
21,C0022,Customer 22,cust22@example.com,Corporate,South,Bengaluru,2025-06-01
22,C0023,Customer 23,cust23@example.com,Corporate,South,MUMBAI,2023-09-10
23,C0024,Customer 24,cust24@example.com,Corporate,North,Delhi,2024-08-01
24,C0025,Customer 25,cust25@example.com,Corporate,East,Guwahati,2023-11-18
25,C0026,Customer 26,cust26@example.com,Corporate,South,Hyderabad,2024-10-22
30,C0031,Customer 31,cust31@example.com,Corporate,East,Kolkata,2023-11-03
37,C0038,Customer 38,cust38@example.com,Corporate,West,Mumbai,2023-06-02
43,C0044,Customer 44,cust44@example.com,Corporate,East,Patna,2025-04-10
44,C0045,Customer 45,cust45@example.com,Corporate,South,Hyderabad,2023-04-21
48,C0049,Customer 49,cust49@example.com,Corporate,North,Jaipur,2024-02-14
51,C0052,Customer 52,cust52@example.com,Corporate,East,Patna,2023-04-29
52,C0053,Customer 53,cust53@example.com,Corporate,West,Pune,2024-03-22
56,C0057,Customer 57,cust57@example.com,Corporate,East,Bhubaneswar,2024-01-24
58,C0059,Customer 59,cust59@example.com,Corporate,East,Bhubaneswar,2024-09-13
59,C0060,Customer 60,cust60@example.com,Corporate,East,Patna,2023-08-07
63,C0064,Customer 64,cust64@example.com,Corporate,North,Chandigarh,2025-05-20
64,C0065,Customer 65,cust65@example.com,Corporate,North,Lucknow,2024-08-12
68,C0069,Customer 69,cust69@example.com,Corporate,South,Kochi,2024-09-01
69,C0070,Customer 70,cust70@example.com,Corporate,East,Patna,2024-05-31
70,C0071,Customer 71,cust71@example.com,Corporate,West,Surat,2025-06-01
78,C0079,Customer 79,cust79@example.com,Corporate,West,Surat,2024-07-13
80,C0081,Customer 81,cust81@example.com,Corporate,North,Lucknow,2025-03-28
82,C0083,Customer 83,cust83@example.com,Corporate,North,Lucknow,2023-01-28
91,C0092,Customer 92,cust92@example.com,Corporate,East,Bhubaneswar,2025-01-05
94,C0095,Customer 95,cust95@example.com,Corporate,South,Bengaluru,2023-09-06
95,C0096,Customer 96,cust96@example.com,Corporate,North,Jaipur,2025-04-04
99,C0100,Customer 100,cust100@example.com,Corporate,West,Pune,2024-06-18
100,C0101,Customer 101,cust101@example.com,Corporate,East,Patna,2024-08-29
102,C0103,Customer 103,cust103@example.com,Corporate,West,Pune,2024-09-16
105,C0106,Customer 106,cust106@example.com,Corporate,East,Guwahati,2023-07-15
110,C0111,Customer 111,cust111@example.com,Corporate,East,Patna,2023-12-05
112,C0113,Customer 113,cust113@example.com,Corporate,North,Chandigarh,2024-07-02
115,C0116,Customer 116,cust116@example.com,Corporate,East,Bhubaneswar,2024-06-30

In [82]:
sales_data_orders

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15
2,O00003,2025-11-13 00:00:00,C0072,P027,5,4125.55,10.0,Online,Wallet,18564.98
3,O00004,2025-10-29 00:00:00,C0049,P029,4,21540.38,0.0,Store,COD,86161.52
4,O00005,2025-02-20 00:00:00,C0073,P040,1,13262.69,10.0,Online,Card,11936.42
...,...,...,...,...,...,...,...,...,...,...
1203,O00191,2025-07-08 00:00:00,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32
1204,O01084,2025-10-25 00:00:00,C0084,P031,6,7443.48,20.0,Partner,Card,35728.7
1205,O00284,2025-03-15 00:00:00,C0077,P021,2,1794.79,0.0,Partner,Wallet,3589.58
1206,O00818,2025-02-06 00:00:00,C0047,P015,5,9349.00,15.0,Online,Card,39733.25
1207,O00315,2025-04-26 00:00:00,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95

In [83]:
sales_data_orders[["revenue", "quantity"]].dtypes

revenue     object
quantity     int64
dtype: object

In [84]:
sales_data_orders["revenue"] = pd.to_numeric(
    sales_data_orders["revenue"],
    errors="coerce"
)

In [85]:
sales_data_orders[(sales_data_orders["revenue"]>50000) & (sales_data_orders["quantity"]>3)]

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15
3,O00004,2025-10-29 00:00:00,C0049,P029,4,21540.38,0.0,Store,COD,86161.52
9,O00010,2025-11-28 00:00:00,C0055,P999,5,23936.74,0.0,Online,COD,119683.70
15,O00016,2025-03-31 00:00:00,C0098,P018,5,24739.66,0.0,Store,Wallet,123698.30
...,...,...,...,...,...,...,...,...,...,...
1192,O01193,2025-10-04 00:00:00,C0065,P020,4,20571.79,15.0,Store,Card,69944.09
1197,O01198,2025-05-04 00:00:00,C0026,P024,4,14676.96,0.0,Online,COD,58707.84
1200,O00637,2025-12-05 00:00:00,C0077,P004,6,12708.08,10.0,Store,NetBanking,68623.63
1203,O00191,2025-07-08 00:00:00,C0004,P024,5,14676.96,10.0,Store,Wallet,66046.32
1207,O00315,2025-04-26 00:00:00,C0052,P030,5,22136.99,0.0,Store,UPI,110684.95

In [86]:
sales_data_orders.sort_values(
    by="revenue",
    ascending=True
)
sales_data_orders.head(2)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15

In [87]:
sales_data_orders.sort_values(
    by="revenue",
    ascending=False
)
sales_data_orders.head(2)

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,channel,payment_method,revenue
0,O00001,2025-02-07 00:00:00,C0106,P005,4,16299.63,5.0,Partner,UPI,61938.59
1,O00002,2025-02-13 00:00:00,C0020,P010,5,18283.83,0.0,Online,UPI,91419.15

In [88]:
total_quantity=sales_data_orders["quantity"].sum()
print(total_quantity)

4233

In [89]:
sales_data_orders.groupby("channel").size()

channel
Online     395
Partner    422
Store      391
dtype: int64

In [90]:
revenue_by_channel=(sales_data_orders
                    .groupby("channel")["revenue"]
                    .sum()
                    .reset_index(name="total_revenue"))

revenue_by_channel

   channel  total_revenue
0   Online    17516679.29
1  Partner    16925654.08
2    Store    16543857.81

In [91]:
revenue_by_channel_average=(sales_data_orders
                    .groupby("channel")["revenue"]
                    .mean()
                    .reset_index(name="average_revenue"))

revenue_by_channel_average

   channel  average_revenue
0   Online     45262.737183
1  Partner     40982.213269
2    Store     43195.451201

In [92]:
quantity_by_channel=(sales_data_orders
                    .groupby("channel")["quantity"]
                    .sum()
                    .reset_index(name="total_quantity"))

quantity_by_channel

   channel  total_quantity
0   Online            1411
1  Partner            1496
2    Store            1326